// Generated by materialporter/tools/sync_fork.py from MaterialPorter.Core/Maps.cs (+ MapLandscape, ParamSet) - edit it there.
#nullable disable
using System.Globalization;
using System.Collections.Concurrent;
using System.Numerics;
using global::CUE4Parse.UE4.Assets.Exports;
using global::CUE4Parse.UE4.Assets.Exports.Component.StaticMesh;
using global::CUE4Parse.UE4.Objects.Core.Math;
using global::CUE4Parse.UE4.Objects.Core.Misc;
using global::CUE4Parse.UE4.Assets.Exports.Actor;
using global::CUE4Parse.UE4.Assets.Objects;
using global::CUE4Parse.UE4.Objects.Engine;
using global::CUE4Parse.UE4.Objects.UObject;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FortnitePorting.Exporting.MaterialPorter;

/// <summary>A mesh a map places: where (UE space, row vectors), and what its slots wear.</summary>
public sealed class MapMesh
{
    public string Mesh { get; init; }
    public Matrix4x4 World { get; init; }
    /// <summary>UE material index -> the material placed there instead (a component's override, a building's texture data).</summary>
    public Dictionary<int, string> Overrides { get; init; } = new();
    /// <summary>UE material index -> values over that slot's material (a dynamic instance's parameters).</summary>
    public Dictionary<int, ParamSet> Params { get; init; } = new();
    /// <summary>Values over every slot's material: a building's texture data (Diffuse, Normals, SpecularMasks by layer).</summary>
    public ParamSet AllSlots { get; init; }
    public string Actor { get; init; }
    /// <summary>UE's Custom Primitive Data: floats the component hands its materials (a tree's season tint); else null.</summary>
    public float[] PrimitiveData { get; init; }
    /// <summary>An instanced mesh's own custom data floats (PerInstanceSMCustomData; the materials' PerInstanceCustomData), or null.</summary>
    public float[] InstanceData { get; init; }
    /// <summary>The level file that places it.</summary>
    public string Level { get; init; }
    /// <summary>A spline mesh's bend (its mesh deformed along a Hermite segment), in the component's space; else null.</summary>
    public Dictionary<string, object> Spline { get; init; }
    /// <summary>What a big mesh covers (UE X/Y, world): an area keeps it when they overlap (water bodies); else null.</summary>
    public (float MinX, float MinY, float MaxX, float MaxY)? Area { get; init; }
    /// <summary>
    /// False when the component casts no shadow in the game (CastShadow, UE's master flag, off; or both bCastDynamicShadow and
    /// bCastStaticShadow off): a lamp's housing around its light.
    /// </summary>
    public bool CastShadow { get; init; } = true;
    /// <summary>Where it stands, for an area's test: its origin, a spline mesh's segment middle.</summary>
    public Vector3 Anchor
    {
        get
        {
            if (Spline?["p0"] is double[] a && Spline["p1"] is double[] b)
                return Vector3.Transform(new Vector3((float)(a[0] + b[0]) / 2, (float)(a[1] + b[1]) / 2, (float)(a[2] + b[2]) / 2), World);
            return World.Translation;
        }
    }
}

/// <summary>
/// A light a map places (point, spot or rect light component): where (UE space, row vectors, cm) and what the
/// engine reads of it, as stored (the level's values over its templates'); units and colour are converted by the
/// consumer (Unitless local lights are 1/625 candela per unit; spots and rects shine along their X axis).
/// </summary>
public sealed class MapLight
{
    /// <summary>"Point", "Spot" or "Rect".</summary>
    public string Kind { get; init; }
    public string Name { get; init; }
    public string Actor { get; init; }
    public string Level { get; init; }
    public Matrix4x4 World { get; init; }
    public float Intensity { get; init; }
    /// <summary>"Candelas", "Lumens", "Unitless", "EV" or "Nits": what Intensity is in when the light falls off by the inverse square.</summary>
    public string Units { get; init; }
    /// <summary>
    /// False: the older falloff (Intensity is a brightness, times (1 - (d / AttenuationRadius)^2)^FalloffExponent
    /// out to the radius, whatever the units say); true: candelas and the like, falling off with the square of the distance.
    /// </summary>
    public bool InverseSquared { get; init; } = true;
    public float FalloffExponent { get; init; } = 8f;
    /// <summary>The sRGB colour (LightColor).</summary>
    public FColor Color { get; init; }
    public bool UseTemperature { get; init; }
    public float Temperature { get; init; }
    /// <summary>cm: where the light ends.</summary>
    public float AttenuationRadius { get; init; }
    /// <summary>cm: a point or spot light's source sphere.</summary>
    public float SourceRadius { get; init; }
    public bool CastShadows { get; init; }
    /// <summary>A spot's cone, in degrees from its axis: where the light is full, where it ends.</summary>
    public float InnerConeAngle { get; init; }
    public float OuterConeAngle { get; init; }
    /// <summary>cm: a rect light's source.</summary>
    public float SourceWidth { get; init; }
    public float SourceHeight { get; init; }
    public float BarnDoorAngle { get; init; }
}

/// <summary>
/// A decal a map places (a DecalComponent: a DecalActor's, a Blueprint's): its world matrix (UE space, row vectors, cm; the
/// decal projects along its X axis) and what the engine reads of it. Its half extents are DecalSize times the matrix's scale.
/// </summary>
public sealed class MapDecal
{
    public string Name { get; init; }
    public string Actor { get; init; }
    public string Level { get; init; }
    public Matrix4x4 World { get; init; }
    /// <summary>cm: the half extents before the component's scale (X the depth along the projection, Y and Z the footprint); UE's 128, 256, 256 unless stored.</summary>
    public Vector3 DecalSize { get; init; }
    public int SortOrder { get; init; }
    public float FadeScreenSize { get; init; }
    /// <summary>The decal material's asset path (or a dynamic instance's parent asset's).</summary>
    public string Material { get; init; }
    /// <summary>The values a dynamic instance sets over the material; else null.</summary>
    public ParamSet Params { get; init; }
}

/// <summary>A particle system a map places (a NiagaraComponent: a NiagaraActor's, a Blueprint's): where, and its user parameters' overrides.</summary>
public sealed class MapEffect
{
    public string Name { get; init; }
    public string Actor { get; init; }
    public string Level { get; init; }
    public Matrix4x4 World { get; init; }
    /// <summary>The Niagara system's asset path.</summary>
    public string System { get; init; }
    /// <summary>The component's user parameter overrides by name (as the system names them: "x", not "User.x"): a float, an int, a bool, or floats (a vector, a colour); may be empty.</summary>
    public Dictionary<string, object> Parameters { get; init; } = new();
}

public sealed class MapOptions
{
    /// <summary>
    /// Also the cells external data layers add (game modes' and events' content,
    /// shipped in other plugins); without them, the map as its own cells have it.
    /// </summary>
    public bool DataLayers { get; set; }
    /// <summary>Instanced meshes: foliage, prop groups, scatter.</summary>
    public bool Instances { get; set; } = true;
    /// <summary>The landscape (terrain) too.</summary>
    public bool Landscape { get; set; } = true;
    /// <summary>Water bodies: ocean, lakes, rivers (their surface meshes), pools and waterfalls.</summary>
    public bool Water { get; set; } = true;
    /// <summary>Textures at most this size (the game's own smaller mips); 0: full size.</summary>
    public int TextureSize { get; set; }
    /// <summary>Only this area (UE cm, X/Y): the cells that touch it, and what they place inside it. Null: all of it.</summary>
    public MapRegion? Region { get; set; }
}

/// <summary>An area of a map, in UE centimetres.</summary>
public readonly record struct MapRegion(double MinX, double MinY, double MaxX, double MaxY)
{
    public bool Contains(double x, double y) => x >= MinX && x <= MaxX && y >= MinY && y <= MaxY;
    public bool Overlaps((float MinX, float MinY, float MaxX, float MaxY) a) => a.MaxX > MinX && a.MinX < MaxX && a.MaxY > MinY && a.MinY < MaxY;
    public bool Touches(MapCell c) => c.MaxX > MinX && c.MinX < MaxX && c.MaxY > MinY && c.MinY < MaxY;
}

/// <summary>One World Partition cell: its level file, and the area it streams in for.</summary>
public sealed class MapCell
{
    public string Key { get; init; }
    public string Grid { get; init; }
    /// <summary>0 for the finest cells; higher levels hold what spans several.</summary>
    public int Level { get; init; }
    /// <summary>False: always loaded, whatever the player's position.</summary>
    public bool Spatial { get; init; }
    public double MinX { get; init; }
    public double MinY { get; init; }
    public double MaxX { get; init; }
    public double MaxY { get; init; }
    public long Size { get; init; }
    /// <summary>Added by an external data layer (a game mode's or an event's content).</summary>
    public bool DataLayer { get; init; }
}

/// <summary>How far a map's export is: its stage (1-4: reading, meshes, materials, Blender), done of total.</summary>
public readonly record struct MapProgress(int Stage, string What, int Done, int Total)
{
    public const int Stages = 4;
    // where each stage starts in the whole, by the time they usually take (Blender's placing is most of it)
    static readonly double[] Starts = { 0, 0.10, 0.25, 0.35, 1.0 };
    /// <summary>The whole export's share done, 0..1.</summary>
    public double Overall
    {
        get
        {
            var s = Math.Clamp(Stage, 1, Stages);
            var f = Total > 0 ? Math.Clamp((double)Done / Total, 0, 1) : 0;
            return Starts[s - 1] + (Starts[s] - Starts[s - 1]) * f;
        }
    }
}

/// <summary>What reading a map found.</summary>
public sealed class MapScan
{
    public string Name { get; init; }
    public string Key { get; init; }
    public List<MapMesh> Meshes { get; set; } = new();
    /// <summary>Its point, spot and rect lights (visible ones).</summary>
    public List<MapLight> Lights { get; set; } = new();
    /// <summary>Its decals (visible ones with a material).</summary>
    public List<MapDecal> Decals { get; set; } = new();
    /// <summary>Its particle systems (visible ones with a system, not a device's).</summary>
    public List<MapEffect> Effects { get; set; } = new();
    /// <summary>The landscape pieces its levels hold (exported when the bundle is made).</summary>
    public List<MapLandscape> Landscapes { get; set; } = new();
    /// <summary>The area asked for, if any.</summary>
    public MapRegion? Region { get; set; }
    public int Levels { get; set; }
    public int Actors;
    /// <summary>What was left out, by kind, with counts (landscape, splines, HLODs...).</summary>
    public ConcurrentDictionary<string, int> Skipped { get; } = new();
    public int UniqueMeshes => Meshes.Select(m => m.Mesh).Distinct(StringComparer.OrdinalIgnoreCase).Count();
    internal void Skip(string what, int n = 1) => Skipped.AddOrUpdate(what, n, (_, c) => c + n);
}

/// <summary>
/// Maps (FortnitePorting's map export, but every material exact): a level's
/// actors, their components' meshes placed where the level puts them.
/// A placed Blueprint keeps only what it changes in the level; the rest
/// (its mesh, its materials, its components' offsets) comes from its
/// class's templates, read up the template chain. World Partition maps
/// are their persistent level plus their _Generated_ cells (and, asked,
/// the cells external data layers add); level instances and streamed
/// sublevels are read in place. A building's texture data (its wall/floor
/// skin) goes onto its materials as FortnitePorting does it: layer i's
/// textures as Diffuse/Normals/SpecularMasks (suffixed past the first),
/// its override material on slot 0.
/// </summary>

public sealed class MapLandscape
{
    public ALandscapeProxy Proxy { get; init; }
    public string Name { get; init; }
    public string Level { get; init; }
    /// <summary>Where it sits, rotation and translation only (UE, row vectors): its scale goes into the vertices.</summary>
    public Matrix4x4 World { get; init; }
    public Vector3 Scale { get; init; }
}


public sealed class ParamSet
{
    public List<string> Materials { get; set; } = new();
    public Dictionary<string, double> Scalars { get; set; } = new();
    public Dictionary<string, double[]> Vectors { get; set; } = new();
    public Dictionary<string, string> Textures { get; set; } = new();
    /// <summary>Static switches (a weapon wrap's: the customization effects it turns on).</summary>
    public Dictionary<string, bool> Switches { get; set; } = new();
    /// <summary>The option that set them, for the built material's name.</summary>
    public string Label { get; set; }
    readonly List<string> labels = new();

    public void MergeFrom(ParamSet o)
    {
        foreach (var kv in o.Scalars) Scalars[kv.Key] = kv.Value;
        foreach (var kv in o.Vectors) Vectors[kv.Key] = kv.Value;
        foreach (var kv in o.Textures) Textures[kv.Key] = kv.Value;
        foreach (var kv in o.Switches) Switches[kv.Key] = kv.Value;
        // "Default" and unnamed options say nothing in a name
        if (o.Label is { } l && l != "Default" && !l.StartsWith("Option ") && !labels.Contains(l)) labels.Add(l);
        Label = labels.Count == 0 ? "style" : string.Join(", ", labels.Take(3)) + (labels.Count > 3 ? $" +{labels.Count - 3}" : "");
    }

    /// <summary>A short stable key for the values, so a styled material builds once.</summary>
    public string Key()
    {
        var s = string.Join(";", Scalars.OrderBy(k => k.Key).Select(k => k.Key + "=" + k.Value.ToString("R", CultureInfo.InvariantCulture)))
              + "|" + string.Join(";", Vectors.OrderBy(k => k.Key).Select(k => k.Key + "=" + string.Join(",", k.Value.Select(x => x.ToString("R", CultureInfo.InvariantCulture)))))
              + "|" + string.Join(";", Textures.OrderBy(k => k.Key).Select(k => k.Key + "=" + k.Value));
        // (only when there are some: the keys of sets without switches stay what they were)
        if (Switches.Count > 0) s += "|" + string.Join(";", Switches.OrderBy(k => k.Key).Select(k => k.Key + "=" + (k.Value ? "1" : "0")));
        return Convert.ToHexString(System.Security.Cryptography.SHA1.HashData(System.Text.Encoding.UTF8.GetBytes(s)))[..8].ToLowerInvariant();
    }
}

public sealed class MapReader
{
    readonly MapGame game;
    readonly MapOptions options;
    readonly MapScan scan;
    readonly ConcurrentDictionary<string, Lazy<UObject>> templates = new(StringComparer.OrdinalIgnoreCase);
    readonly ConcurrentDictionary<string, byte> streamed = new(StringComparer.OrdinalIgnoreCase);
    public readonly ConcurrentBag<MapMesh> Placed = new();
    public readonly ConcurrentBag<MapLight> Lights = new();
    public readonly ConcurrentBag<MapDecal> Decals = new();
    public readonly ConcurrentBag<MapEffect> Effects = new();
    public readonly ConcurrentBag<MapLandscape> Landscapes = new();
    public int Count => Placed.Count;
    static readonly JsonSerializerSettings Ser = new() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

    public MapReader(MapGame game, MapOptions options, MapScan scan)
    {
        this.game = game;
        this.options = options;
        this.scan = scan;
    }

    // ------------------------------------------------------------ properties through the template chain

    /// <summary>A placed object's archetype: its class's template (cached; natives have none we can read).</summary>
    UObject Template(UObject o)
    {
        var t = o.Template;
        if (t == null) return null;
        string path;
        try { path = t.GetPathName(); }
        catch { return null; }
        if (string.IsNullOrEmpty(path) || path.StartsWith("/Script/", StringComparison.Ordinal)) return null;
        return templates.GetOrAdd(path, _ => new Lazy<UObject>(() =>
        {
            try { return t.Load(); }
            catch { return null; }
        })).Value;
    }

    IEnumerable<UObject> Chain(UObject o)
    {
        for (var i = 0; o != null && i < 12; i++, o = Template(o)) yield return o;
    }

    T Prop<T>(UObject o, string name, T fallback = default)
    {
        foreach (var x in Chain(o))
            if (x.TryGetValue(out T v, name)) return v;
        return fallback;
    }

    static FPackageIndex Ref(UObject o, string name) => o.TryGetValue(out FPackageIndex i, name) && !i.IsNull ? i : null;

    FPackageIndex RefChain(UObject o, string name)
    {
        foreach (var x in Chain(o))
            if (Ref(x, name) is { } i) return i;
        return null;
    }

    static string PathOf(FPackageIndex i)
    {
        try { return i?.ResolvedObject?.GetPathName(); }
        catch { return null; }
    }

    static string Package(string objectPath)
    {
        var dot = objectPath.LastIndexOf('.');
        return dot > objectPath.LastIndexOf('/') ? objectPath[..dot] : objectPath;
    }

    // ------------------------------------------------------------ levels

    public async Task LevelAsync(string path, Matrix4x4 parent, int depth, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        var pkg = await game.Provider.LoadPackageAsync(path);
        var exports = pkg.GetExports().ToList();
        var level = exports.OfType<ULevel>().FirstOrDefault();
        if (level == null) return;
        var world = exports.OfType<UWorld>().FirstOrDefault();

        // components by their actor (names are unique within a level)
        var byActor = new Dictionary<string, List<UObject>>(StringComparer.Ordinal);
        var levelOwned = new Dictionary<string, UObject>(StringComparer.Ordinal);
        foreach (var e in exports)
        {
            var outer = e.Outer?.Name.Text;
            if (outer == null) continue;
            if (outer == level.Name) levelOwned[e.Name] = e;
            else if (e.ExportType.Contains("Component", StringComparison.Ordinal))
            {
                if (!byActor.TryGetValue(outer, out var l)) byActor[outer] = l = new List<UObject>();
                l.Add(e);
            }
        }
        var ctx = new LevelContext(this, byActor, parent) { Level = path };
        foreach (var idx in level.Actors ?? Array.Empty<FPackageIndex>())
        {
            ct.ThrowIfCancellationRequested();
            if (idx == null || idx.IsNull || !levelOwned.TryGetValue(idx.Name, out var actor)) continue;
            Interlocked.Increment(ref scan.Actors);
            try { await ActorAsync(actor, ctx, depth, ct); }
            catch (OperationCanceledException) { throw; }
            catch (Exception e)
            {
                var why = (e.Message ?? "").Split('\n')[0];
                scan.Skip($"unreadable actors ({e.GetType().Name}: {(why.Length > 90 ? why[..90] : why)})");
            }
        }

        // a classic map's streamed sublevels, each where its streaming object puts it
        foreach (var sl in world?.StreamingLevels ?? Array.Empty<FPackageIndex>())
        {
            if (depth > 3 || sl == null || sl.IsNull) continue;
            UObject streaming;
            try { streaming = sl.Load(); }
            catch { continue; }
            if (streaming == null || streaming.ExportType.StartsWith("WorldPartition", StringComparison.Ordinal)) continue;
            if (!streaming.TryGetValue(out FSoftObjectPath wa, "WorldAsset") || wa.AssetPathName.IsNone) continue;
            var sub = Package(wa.AssetPathName.Text);
            if (!streamed.TryAdd(sub, 0)) continue;
            var t = streaming.TryGetValue(out FTransform lt, "LevelTransform") ? Of(lt) : Matrix4x4.Identity;
            try { await LevelAsync(sub, t * parent, depth + 1, ct); }
            catch (OperationCanceledException) { throw; }
            catch { scan.Skip("unreadable sublevels"); }
        }
    }

    sealed class LevelContext
    {
        readonly MapReader reader;
        readonly Dictionary<string, List<UObject>> byActor;
        public readonly Matrix4x4 Parent;
        public string Level { get; init; }
        readonly Dictionary<UObject, Matrix4x4> worlds = new(ReferenceEqualityComparer.Instance);

        public LevelContext(MapReader reader, Dictionary<string, List<UObject>> byActor, Matrix4x4 parent)
        {
            this.reader = reader;
            this.byActor = byActor;
            Parent = parent;
        }

        public List<UObject> Components(string actor) => byActor.TryGetValue(actor, out var l) ? l : new List<UObject>();

        /// <summary>A component's world matrix: its offsets, then its attach parent's, up to the level's.</summary>
        public Matrix4x4 World(UObject c, UObject root, int guard = 0)
        {
            if (worlds.TryGetValue(c, out var w)) return w;
            var local = reader.Local(c);
            UObject parent = null;
            // the level's own attachment only: a template's points into its Blueprint
            if (Ref(c, "AttachParent") is { } ap)
            {
                var owner = ap.ResolvedObject?.Outer?.Name.Text;
                var name = ap.Name;
                if (owner != null) parent = Components(owner).FirstOrDefault(x => x.Name == name);
            }
            if (parent == null && root != null && !ReferenceEquals(c, root)) parent = root;
            w = parent != null && guard < 32 ? local * World(parent, null, guard + 1) : local * Parent;
            worlds[c] = w;
            return w;
        }
    }

    /// <summary>Devices: nothing of theirs is placed (they play when someone interacts).</summary>
    static readonly string[] SkipActorPrefixes = { "Device_", "VerseDevice_" };
    /// <summary>Blueprint devices: their meshes and lights stay out too, but their particle systems play on their own (a mushroom bouncer's light beams).</summary>
    static readonly string[] EffectsOnlyPrefixes = { "BP_Device_" };

    async Task ActorAsync(UObject actor, LevelContext ctx, int depth, CancellationToken ct)
    {
        var type = actor.ExportType;
        if (type == "LODActor" || type.Contains("HLOD", StringComparison.Ordinal)) { scan.Skip("HLOD actors"); return; }
        if (actor is global::CUE4Parse.UE4.Assets.Exports.Actor.ALandscapeProxy lp && lp.LandscapeComponents is { Length: > 0 })
        {
            // World Partition keeps its landscape in streaming proxies; a classic map, in the landscape actor
            // (whose spline meshes - its roads - the component loop below still places)
            if (!options.Landscape) scan.Skip("landscape");
            else
            {
                var lcomps = ctx.Components(actor.Name);
                var lrootName = RefChain(actor, "RootComponent")?.Name;
                var lroot = lrootName == null ? null : lcomps.FirstOrDefault(c => c.Name == lrootName);
                var m = lroot != null ? ctx.World(lroot, null) : ctx.Parent;
                Matrix4x4.Decompose(m, out var sc, out var rot, out var tr);
                Landscapes.Add(new MapLandscape
                {
                    Proxy = lp, Name = actor.Name, Level = ctx.Level, Scale = sc,
                    World = Matrix4x4.CreateFromQuaternion(rot) * Matrix4x4.CreateTranslation(tr),
                });
            }
        }
        // a landscape spline actor holds the roads' shape; Fortnite's own World Partition cooks their meshes
        // into LandscapeSplineMeshesActors (spline meshes and control-point meshes), placed like any other. A UEFN
        // island keeps them on the spline actor itself (its spline mesh and control-point mesh components, attached to
        // its LandscapeSplinesComponent): those are read below like any actor's. Shape-only: nothing to place.
        else if (type == "LandscapeSplineActor" && !ctx.Components(actor.Name).Any(c => c.ExportType.Contains("MeshComponent", StringComparison.Ordinal)))
        {
            scan.Skip("landscape spline shapes (their meshes come separately)");
            return;
        }
        if (SkipActorPrefixes.Any(p => type.StartsWith(p, StringComparison.Ordinal) || actor.Name.StartsWith(p, StringComparison.Ordinal))) { scan.Skip("devices"); return; }
        if (Prop(actor, "bHidden", false)) { scan.Skip("hidden actors"); return; }
        // a zipline's cable is laid between its poles when the game runs (its saved root sits at the origin)
        if (type.Contains("ZipLine_Spline", StringComparison.OrdinalIgnoreCase)) { scan.Skip("ziplines (laid when the game runs)"); return; }

        var comps = ctx.Components(actor.Name);
        var rootName = RefChain(actor, "RootComponent")?.Name;
        var root = rootName == null ? null : comps.FirstOrDefault(c => c.Name == rootName);

        if (EffectsOnlyPrefixes.Any(p => type.StartsWith(p, StringComparison.Ordinal) || actor.Name.StartsWith(p, StringComparison.Ordinal)))
        {
            scan.Skip("devices");
            foreach (var c in comps)
                if (c.ExportType.EndsWith("NiagaraComponent", StringComparison.Ordinal)) Effect(c, actor, ctx, root);
            return;
        }

        // level instances and a foundation's extra worlds: those levels, placed here
        if (depth < 4)
        {
            var worlds = new List<string>();
            if (Prop<FSoftObjectPath?>(actor, "WorldAsset") is { } wa && !wa.AssetPathName.IsNone) worlds.Add(wa.AssetPathName.Text);
            if (Prop<FSoftObjectPath[]>(actor, "AdditionalWorlds") is { } aw)
                worlds.AddRange(aw.Where(x => !x.AssetPathName.IsNone).Select(x => x.AssetPathName.Text));
            var at = root != null ? ctx.World(root, null) : ctx.Parent;
            foreach (var w in worlds.Distinct())
            {
                try { await LevelAsync(Package(w), at, depth + 1, ct); }
                catch (OperationCanceledException) { throw; }
                catch { scan.Skip("unreadable level instances"); }
            }
        }

        // a water body: its surface mesh (WaterInfoMeshComponent: the ocean's, a lake's outline, a river's ribbon at
        // its real height) or a custom body's own mesh (pools, waterfalls), wearing the body's WaterMaterial; its other
        // components (hidden lake plane, river spline meshes, the dilated copy) are the game's runtime helpers
        var waterBody = comps.FirstOrDefault(x => x.ExportType.Contains("WaterBody", StringComparison.Ordinal)
                                                  && !x.ExportType.Contains("Mesh", StringComparison.Ordinal));
        if (waterBody != null && !options.Water) { scan.Skip("water bodies"); return; }
        var waterMaterial = waterBody == null ? null : PathOf(RefChain(waterBody, "WaterMaterial"));

        // a building's skin: texture data by layer, on its main mesh
        var mainName = RefChain(actor, "StaticMeshComponent")?.Name ?? rootName;
        var (skin, skinMaterial, skinTints) = TextureData(actor);

        foreach (var c in comps)
        {
            var ctype = c.ExportType;
            if (ctype.Contains("HLOD", StringComparison.Ordinal)) { scan.Skip("HLOD meshes"); continue; }
            var waterSurface = waterBody != null && (c.Name is "WaterInfoMeshComponent" or "CustomMeshComponent");
            if (waterBody != null && !waterSurface) continue;
            if (LightKind(c) is { } lightKind)
            {
                Light(c, lightKind, actor, ctx, root);
                continue;
            }
            if (ctype.EndsWith("DecalComponent", StringComparison.Ordinal))
            {
                Decal(c, actor, ctx, root);
                continue;
            }
            if (ctype.EndsWith("NiagaraComponent", StringComparison.Ordinal))
            {
                Effect(c, actor, ctx, root);
                continue;
            }
            if (!waterSurface && (ctype.StartsWith("ShadowProxy", StringComparison.Ordinal) || ctype.Contains("Landscape", StringComparison.Ordinal)
                || ctype.Contains("Water", StringComparison.Ordinal))) continue;
            var meshRef = RefChain(c, "StaticMesh") ?? RefChain(c, "SkeletalMesh") ?? RefChain(c, "SkeletalMeshAsset");
            if (meshRef == null) continue;
            Dictionary<string, object> spline = null;
            if (ctype.Contains("SplineMesh", StringComparison.Ordinal) && (spline = Spline(c)) == null)
            {
                scan.Skip("spline meshes shaped at runtime (ziplines...)");
                continue;
            }
            // (a water body's surface mesh is hidden: the game draws the water from it at run time)
            if (!waterSurface && (!Prop(c, "bVisible", true) || Prop(c, "bHiddenInGame", false))) continue;
            // drawn only into the terrain's runtime virtual texture (a dirt track the landscape shows), never on its own
            if (!Prop(c, "bRenderInMainPass", true)
                || (Prop(c, "VirtualTextureRenderPassType", new FName()).Text?.EndsWith("Never", StringComparison.Ordinal) == true
                    && Prop(c, "RuntimeVirtualTextures", Array.Empty<FPackageIndex>()).Length > 0))
            {
                scan.Skip("meshes drawn only into the terrain's virtual texture");
                continue;
            }
            var mesh = PathOf(meshRef);
            if (mesh == null) continue;

            var overrides = new Dictionary<int, string>();
            var ps = new Dictionary<int, ParamSet>();
            foreach (var (slot, idx) in OverrideSlots(c))
            {
                var (mp, mparams) = Material(idx);
                if (mp == null) continue;
                overrides[slot] = mp;
                if (mparams != null) ps[slot] = mparams;
            }
            var main = c.Name == mainName;
            if (main && skinMaterial != null) overrides[0] = skinMaterial;
            (float, float, float, float)? area = null;
            if (waterSurface)
            {
                if (waterMaterial != null) overrides[0] = waterMaterial;
                area = Covers(meshRef, ctx.World(c, root));
            }
            float[] cpd = null;
            foreach (var x in Chain(c))
                if (x.TryGetValue(out FStructFallback data, "CustomPrimitiveData") && data.TryGetValue(out float[] d, "Data") && d.Length > 0)
                {
                    cpd = d;
                    break;
                }
            // the game writes the texture data's tints into the main mesh's custom primitive data
            if (main && skinTints != null)
            {
                var all = new float[Math.Max(cpd?.Length ?? 0, skinTints.Keys.Max() + 1)];
                cpd?.CopyTo(all, 0);
                foreach (var (i, v) in skinTints) all[i] = v;
                cpd = all;
            }
            var world = ctx.World(c, root);
            var castShadow = Prop(c, "CastShadow", true) && (Prop(c, "bCastDynamicShadow", true) || Prop(c, "bCastStaticShadow", true));

            if (c is UInstancedStaticMeshComponent ism)
            {
                // the instances and their custom data come from the same component (the level's, else a template's)
                var owner = Chain(c).OfType<UInstancedStaticMeshComponent>().FirstOrDefault(t => t.PerInstanceSMData?.Length > 0);
                var data = owner?.PerInstanceSMData;
                if (data == null || data.Length == 0) continue;
                if (!options.Instances) { scan.Skip("instanced meshes", data.Length); continue; }
                var floats = Prop(c, "NumCustomDataFloats", 0);
                var custom = floats > 0 && owner.PerInstanceSMCustomData is { } cd && cd.Length >= data.Length * floats ? cd : null;
                // a building ISM stands in for building actors (TemplateActorClass): each instance's floats are
                // its building's custom primitive data (36 of them; texture data tints at 30/31/35)
                var perInstanceCpd = custom != null && ctype.Contains("BuildingInstancedStaticMesh", StringComparison.Ordinal);
                for (var i = 0; i < data.Length; i++)
                {
                    var mine = custom?[(i * floats)..((i + 1) * floats)];
                    Placed.Add(new MapMesh
                    {
                        Mesh = mesh, World = Of(data[i].TransformData) * world, Overrides = overrides, Params = ps,
                        AllSlots = main ? skin : null, Actor = actor.Name, Level = ctx.Level,
                        PrimitiveData = perInstanceCpd ? mine : cpd, InstanceData = mine, CastShadow = castShadow,
                    });
                }
                continue;
            }
            Placed.Add(new MapMesh { Mesh = mesh, World = world, Overrides = overrides, Params = ps, AllSlots = main ? skin : null, Actor = actor.Name, Level = ctx.Level, Spline = spline,
                               PrimitiveData = cpd, Area = area, CastShadow = castShadow });
        }
    }

    /// <summary>
    /// A spline mesh component's bend: SplineParams member by member (the
    /// level's, its templates', else the engine's defaults: a straight 100 cm
    /// along X), its forward axis, up direction and boundary. Null when
    /// nothing stores it.
    /// </summary>
    Dictionary<string, object> Spline(UObject c)
    {
        var structs = Chain(c).Select(x => x.TryGetValue(out FStructFallback s, "SplineParams") ? s : null).Where(s => s != null).ToList();
        // none stored: the Blueprint shapes it when the game runs (a zipline's cable)
        if (structs.Count == 0) return null;
        T Member<T>(string name, T fallback)
        {
            foreach (var s in structs)
                if (s.TryGetValue(out T v, name)) return v;
            return fallback;
        }
        static double[] V3(FVector v) => new double[] { v.X, v.Y, v.Z };
        static double[] V2(FVector2D v) => new double[] { v.X, v.Y };
        var axis = 0;
        foreach (var x in Chain(c))
        {
            if (x.TryGetValue(out FName e, "ForwardAxis")) { axis = e.Text.EndsWith("Y") ? 1 : e.Text.EndsWith("Z") ? 2 : 0; break; }
        }
        return new Dictionary<string, object>
        {
            ["axis"] = axis,
            ["up"] = V3(Prop(c, "SplineUpDir", new FVector(0, 0, 1))),
            ["min"] = Prop(c, "SplineBoundaryMin", 0f),
            ["max"] = Prop(c, "SplineBoundaryMax", 0f),
            ["smooth"] = Prop(c, "bSmoothInterpRollScale", false),
            ["p0"] = V3(Member("StartPos", new FVector(0, 0, 0))),
            ["t0"] = V3(Member("StartTangent", new FVector(100, 0, 0))),
            ["p1"] = V3(Member("EndPos", new FVector(100, 0, 0))),
            ["t1"] = V3(Member("EndTangent", new FVector(100, 0, 0))),
            ["s0"] = V2(Member("StartScale", new FVector2D(1, 1))),
            ["s1"] = V2(Member("EndScale", new FVector2D(1, 1))),
            ["r0"] = Member("StartRoll", 0f),
            ["r1"] = Member("EndRoll", 0f),
            ["o0"] = V2(Member("StartOffset", new FVector2D(0, 0))),
            ["o1"] = V2(Member("EndOffset", new FVector2D(0, 0))),
        };
    }

    // ------------------------------------------------------------ lights

    /// <summary>"Spot", "Rect" or "Point" for a light component (its class or a class it derives from), else null.</summary>
    static string LightKind(UObject c)
    {
        var k = c.Class;
        for (var i = 0; k != null && i < 10; i++, k = k.Super)
        {
            var n = k.Name.Text;
            if (n == null) continue;
            if (n.EndsWith("SpotLightComponent", StringComparison.Ordinal)) return "Spot";
            if (n.EndsWith("RectLightComponent", StringComparison.Ordinal)) return "Rect";
            if (n.EndsWith("PointLightComponent", StringComparison.Ordinal)) return "Point";
        }
        return null;
    }

    /// <summary>
    /// A point, spot or rect light: its world matrix and the values the engine reads (the level's own over its
    /// templates', else the engine's defaults: white, 6500 K, 1000 cm of reach, a 44 degree spot, a 64 cm rect,
    /// 8 candelas, the brightness a light is placed with). Fortnite's lights state no units unless they leave the
    /// project's default (a street lamp: 20, a floodlight: 8), and those figures are candelas: Unitless would make them
    /// 1/625 as bright. Hidden lights (bVisible, bHiddenInGame, bAffectsWorld) place nothing; lights of no brightness (a
    /// car's headlights, which its Blueprint turns on when it drives) are placed at 0.
    /// </summary>
    void Light(UObject c, string kind, UObject actor, LevelContext ctx, UObject root)
    {
        if (!Prop(c, "bVisible", true) || Prop(c, "bHiddenInGame", false) || !Prop(c, "bAffectsWorld", true))
        {
            scan.Skip("hidden lights");
            return;
        }
        var intensity = Prop(c, "Intensity", Prop(c, "Brightness", 8f));
        // (a light of no brightness stays: a car's headlights, which its Blueprint turns on when it drives, are lights at 0)
        if (intensity < 0 || !float.IsFinite(intensity))
        {
            scan.Skip("lights of negative brightness");
            return;
        }
        var unitsName = Prop(c, "IntensityUnits", new FName()).Text ?? "";
        var units = unitsName.Contains("Lumens", StringComparison.Ordinal) ? "Lumens"
                  : unitsName.Contains("Unitless", StringComparison.Ordinal) ? "Unitless"
                  : unitsName.EndsWith("EV", StringComparison.Ordinal) ? "EV"
                  : unitsName.Contains("Nits", StringComparison.Ordinal) ? "Nits"
                  : "Candelas";
        Lights.Add(new MapLight
        {
            Kind = kind, Name = c.Name, Actor = actor.Name, Level = ctx.Level, World = ctx.World(c, root),
            Intensity = intensity,
            Units = units,
            InverseSquared = kind == "Rect" || Prop(c, "bUseInverseSquaredFalloff", Prop(c, "InverseSquaredFalloff", true)),
            FalloffExponent = Prop(c, "LightFalloffExponent", 8f),
            Color = Prop(c, "LightColor", new FColor(255, 255, 255, 255)),
            UseTemperature = Prop(c, "bUseTemperature", false),
            Temperature = Prop(c, "Temperature", 6500f),
            AttenuationRadius = Prop(c, "AttenuationRadius", 1000f),
            SourceRadius = kind == "Rect" ? 0f : Prop(c, "SourceRadius", 0f),
            CastShadows = Prop(c, "CastShadows", true) && (Prop(c, "CastDynamicShadows", true) || Prop(c, "CastStaticShadows", true)),
            InnerConeAngle = kind == "Spot" ? Prop(c, "InnerConeAngle", 0f) : 0f,
            OuterConeAngle = kind == "Spot" ? Prop(c, "OuterConeAngle", 44f) : 0f,
            SourceWidth = kind == "Rect" ? Prop(c, "SourceWidth", 64f) : 0f,
            SourceHeight = kind == "Rect" ? Prop(c, "SourceHeight", 64f) : 0f,
            BarnDoorAngle = kind == "Rect" ? Prop(c, "BarnDoorAngle", 88f) : 0f,
        });
    }

    // ------------------------------------------------------------ decals and particle systems

    /// <summary>
    /// A decal: its world matrix (it projects along its X axis) and what the engine reads of it (DecalSize, the half extents
    /// before the component's scale: UE's 128, 256, 256 unless stored; SortOrder; FadeScreenSize), wearing DecalMaterial (a
    /// dynamic instance's values over its parent). Hidden decals and decals without a material place nothing.
    /// </summary>
    void Decal(UObject c, UObject actor, LevelContext ctx, UObject root)
    {
        if (!Prop(c, "bVisible", true) || Prop(c, "bHiddenInGame", false))
        {
            scan.Skip("hidden decals");
            return;
        }
        var (material, values) = RefChain(c, "DecalMaterial") is { } idx ? Material(idx) : (null, null);
        if (material == null)
        {
            scan.Skip("decals without a material");
            return;
        }
        var size = Prop(c, "DecalSize", new FVector(128f, 256f, 256f));
        Decals.Add(new MapDecal
        {
            Name = c.Name, Actor = actor.Name, Level = ctx.Level, World = ctx.World(c, root),
            DecalSize = new Vector3((float)size.X, (float)size.Y, (float)size.Z),
            SortOrder = Prop(c, "SortOrder", 0),
            FadeScreenSize = Prop(c, "FadeScreenSize", 0.01f),
            Material = material, Params = values,
        });
    }

    /// <summary>
    /// A particle system (NiagaraComponent): its world matrix, its system's path and the user parameters its overrides set.
    /// Hidden components and components without a system place nothing.
    /// </summary>
    void Effect(UObject c, UObject actor, LevelContext ctx, UObject root)
    {
        if (!Prop(c, "bVisible", true) || Prop(c, "bHiddenInGame", false))
        {
            scan.Skip("hidden effects");
            return;
        }
        var system = PathOf(RefChain(c, "Asset"));
        if (system == null)
        {
            scan.Skip("effects without a system");
            return;
        }
        Effects.Add(new MapEffect
        {
            Name = c.Name, Actor = actor.Name, Level = ctx.Level, World = ctx.World(c, root),
            System = system, Parameters = UserParametersSafe(c),
        });
    }

    Dictionary<string, object> UserParametersSafe(UObject c)
    {
        try { return UserParameters(c); }
        catch (Exception e)
        {
            scan.Skip($"effects whose parameters couldn't be read ({e.GetType().Name}: {(e.Message ?? "").Split('\n')[0]})");
            return new Dictionary<string, object>();
        }
    }

    /// <summary>
    /// A Niagara component's user parameter overrides: its OverrideParameters store (the level's, else its template's) is
    /// a byte block (ParameterData) and where each named parameter sits in it (SortedParameterOffsets: Offset, Name, TypeDef).
    /// Floats, ints, bools, vectors and colours are read; a store that names no parameters (or types read elsewhere) gives none.
    /// </summary>
    Dictionary<string, object> UserParameters(UObject c)
    {
        var found = new Dictionary<string, object>(StringComparer.Ordinal);
        foreach (var x in Chain(c))
        {
            // (read through the export's JSON, as a dynamic instance's values are: the struct's arrays come as plain tokens)
            if (JObject.Parse(JsonConvert.SerializeObject(x, Ser))["Properties"]?["OverrideParameters"] is not JObject store) continue;
            if (store["SortedParameterOffsets"] is not JArray offsets || offsets.Count == 0) continue;
            if (store["ParameterData"] is not JArray bytes || bytes.Count == 0) continue;
            var data = bytes.Select(b => (byte)b).ToArray();
            foreach (var entry in offsets)
            {
                var name = (string)entry["Name"];
                // (named as the system names them: the store says "User.x", the plugin sets "User." + name)
                if (name != null && name.StartsWith("User.", StringComparison.Ordinal)) name = name[5..];
                var offset = (int?)entry["Offset"] ?? -1;
                var typeName = (string)entry["TypeDef"]?["ClassStructOrEnum"]?["ObjectName"] ?? "";
                if (string.IsNullOrEmpty(name) || offset < 0) continue;
                // "Class'NiagaraFloat'" -> NiagaraFloat
                var q = typeName.IndexOf('\'');
                var type = q >= 0 && typeName.LastIndexOf('\'') > q ? typeName[(q + 1)..typeName.LastIndexOf('\'')] : typeName;
                var floats = type switch
                {
                    "NiagaraFloat" => 1,
                    "Vector2f" => 2,
                    "Vector3f" or "NiagaraPosition" => 3,
                    "Vector4f" or "LinearColor" or "Quat4f" => 4,
                    _ => 0,
                };
                if (floats > 0 && offset + floats * 4 <= data.Length)
                {
                    var v = new float[floats];
                    for (var i = 0; i < floats; i++) v[i] = BitConverter.ToSingle(data, offset + i * 4);
                    if (v.All(float.IsFinite)) found[name] = floats == 1 ? (object)v[0] : v;
                }
                else if (type is "NiagaraInt32" or "NiagaraBool" && offset + 4 <= data.Length)
                {
                    var n = BitConverter.ToInt32(data, offset);
                    found[name] = type == "NiagaraBool" ? n != 0 : n;
                }
            }
            break;
        }
        return found;
    }

    // ------------------------------------------------------------ materials

    /// <summary>A component's material overrides by slot: its own over its templates'.</summary>
    IEnumerable<(int Slot, FPackageIndex Material)> OverrideSlots(UObject c)
    {
        var r = new SortedDictionary<int, FPackageIndex>();
        foreach (var x in Chain(c))
            if (x.TryGetValue(out FPackageIndex[] arr, "OverrideMaterials"))
                for (var i = 0; i < arr.Length; i++)
                    if (arr[i] != null && !arr[i].IsNull) r.TryAdd(i, arr[i]);
        return r.Select(kv => (kv.Key, kv.Value));
    }

    /// <summary>
    /// A material reference: an asset's path, or (a dynamic instance the level
    /// made) its parent asset's path and the values it sets over it.
    /// </summary>
    (string Path, ParamSet Params) Material(FPackageIndex idx)
    {
        ParamSet ps = null;
        for (var guard = 0; idx != null && guard < 8; guard++)
        {
            if (!idx.IsExport) return (PathOf(idx), ps);
            UObject o;
            try { o = idx.Load(); }
            catch { return (null, null); }
            if (o == null) return (null, null);
            if (!o.ExportType.Contains("MaterialInstanceDynamic", StringComparison.Ordinal)) return (o.GetPathName(), ps);
            // the child's values win: collect them first, the parent's only where it's silent
            var mine = Values(o);
            if (ps == null)
            {
                ps = mine;
                ps.Label = o.Name;
            }
            else
            {
                foreach (var kv in mine.Scalars) ps.Scalars.TryAdd(kv.Key, kv.Value);
                foreach (var kv in mine.Vectors) ps.Vectors.TryAdd(kv.Key, kv.Value);
                foreach (var kv in mine.Textures) ps.Textures.TryAdd(kv.Key, kv.Value);
            }
            idx = Ref(o, "Parent");
        }
        return (null, null);
    }

    static ParamSet Values(UObject mid)
    {
        var p = JObject.Parse(JsonConvert.SerializeObject(mid, Ser))["Properties"] as JObject ?? new JObject();
        var ps = new ParamSet();
        static string Name(JToken e) => (string)e["ParameterInfo"]?["Name"] ?? (string)e["ParameterName"];
        foreach (var e in p["ScalarParameterValues"] ?? new JArray())
            if (Name(e) is { } n) ps.Scalars[n] = (double?)e["ParameterValue"] ?? 0;
        foreach (var e in p["VectorParameterValues"] ?? new JArray())
            if (Name(e) is { } n && e["ParameterValue"] is JObject v)
                ps.Vectors[n] = new[] { (double?)v["R"] ?? 0, (double?)v["G"] ?? 0, (double?)v["B"] ?? 0, (double?)v["A"] ?? 1 };
        foreach (var e in p["TextureParameterValues"] ?? new JArray())
            if (Name(e) is { } n && MaterialService.ObjectPath(e["ParameterValue"]) is { } t) ps.Textures[n] = t;
        return ps;
    }

    /// <summary>Custom primitive data index of each texture data layer's tint (the materials' CPD_PackedHSV_1/_2/_3).</summary>
    static readonly int[] TintIndex = [30, 31, 35];

    /// <summary>
    /// A colour as the materials' packed HSV float: the bits of
    /// hue degrees (12) | saturation * 1023 (10) | value * 1023 (10), which
    /// MF_ColorTint_Unpack reads back with asuint. HSV of the linear colour.
    /// </summary>
    static float PackedHsv(FColor c)
    {
        static float Lin(byte b) { var x = b / 255f; return x <= 0.04045f ? x / 12.92f : MathF.Pow((x + 0.055f) / 1.055f, 2.4f); }
        float r = Lin(c.R), g = Lin(c.G), b = Lin(c.B);
        float max = MathF.Max(r, MathF.Max(g, b)), min = MathF.Min(r, MathF.Min(g, b)), range = max - min;
        var h = max == min ? 0f
              : max == r ? ((g - b) / range * 60f + 360f) % 360f
              : max == g ? (b - r) / range * 60f + 120f
              : (r - g) / range * 60f + 240f;
        var s = max == 0 ? 0f : range / max;
        var bits = ((uint)MathF.Round(h) % 360u << 20) | ((uint)MathF.Round(s * 1023f) << 10) | (uint)MathF.Round(max * 1023f);
        return BitConverter.UInt32BitsToSingle(bits);
    }

    /// <summary>
    /// A building's texture data (by layer index, the level's over its class's):
    /// its textures as parameters, the first override material among them,
    /// and each layer's tint as custom primitive data (index, packed float).
    /// </summary>
    (ParamSet Skin, string Material, Dictionary<int, float> Tints) TextureData(UObject actor)
    {
        var layers = new SortedDictionary<int, FPackageIndex>();
        foreach (var x in Chain(actor))
            foreach (var tag in x.Properties)
            {
                if (tag.Name.Text != "TextureData") continue;
                if (tag.Tag?.GenericValue is FPackageIndex i && !i.IsNull) layers.TryAdd(tag.ArrayIndex, i);
            }
        if (layers.Count == 0) return (null, null, null);
        var ps = new ParamSet();
        string material = null;
        var tints = new Dictionary<int, float>();
        var names = new List<string>();
        foreach (var (index, idx) in layers)
        {
            UObject td;
            try { td = idx.Load(); }
            catch { continue; }
            if (td == null) continue;
            names.Add(td.Name);
            var ts = index > 0 ? $"_Texture_{index + 1}" : "";
            var ss = index > 0 ? $"_{index + 1}" : "";
            if (PathOf(Ref(td, "Diffuse")) is { } d) ps.Textures["Diffuse" + ts] = d;
            if (PathOf(Ref(td, "Normal")) is { } n) ps.Textures["Normals" + ts] = n;
            if (PathOf(Ref(td, "Specular")) is { } s) ps.Textures["SpecularMasks" + ss] = s;
            material ??= PathOf(Ref(td, "OverrideMaterial"));
            // a tint left out reads as none: white (cooked data stores explicit black, never white)
            if (index < TintIndex.Length)
                tints[TintIndex[index]] = PackedHsv(td.TryGetValue(out FColor tint, "TintColor") ? tint : new FColor(255, 255, 255, 255));
        }
        if (names.Count == 0) return (null, null, null);
        ps.Label = string.Join(", ", names);
        return (ps, material, tints.Count > 0 ? tints : null);
    }

    /// <summary>The X/Y a static mesh covers placed by `world` (its bounds' corners), or null when it has none.</summary>
    static (float, float, float, float)? Covers(FPackageIndex meshRef, Matrix4x4 world)
    {
        try
        {
            if (meshRef.Load() is not global::CUE4Parse.UE4.Assets.Exports.StaticMesh.UStaticMesh sm || sm.RenderData?.Bounds is not { } b) return null;
            float x0 = float.MaxValue, y0 = float.MaxValue, x1 = float.MinValue, y1 = float.MinValue;
            for (var i = 0; i < 8; i++)
            {
                var p = Vector3.Transform(new Vector3(
                    (float)(b.Origin.X + ((i & 1) == 0 ? -b.BoxExtent.X : b.BoxExtent.X)),
                    (float)(b.Origin.Y + ((i & 2) == 0 ? -b.BoxExtent.Y : b.BoxExtent.Y)),
                    (float)(b.Origin.Z + ((i & 4) == 0 ? -b.BoxExtent.Z : b.BoxExtent.Z))), world);
                x0 = Math.Min(x0, p.X); y0 = Math.Min(y0, p.Y); x1 = Math.Max(x1, p.X); y1 = Math.Max(y1, p.Y);
            }
            return (x0, y0, x1, y1);
        }
        catch { return null; }
    }

    // ------------------------------------------------------------ transforms

    Matrix4x4 Local(UObject c)
    {
        var l = Prop(c, "RelativeLocation", new FVector(0, 0, 0));
        // (a DecalActor's decal faces down unless the level stores another rotation: ADecalActor's constructor sets its pitch to -90)
        var r = Prop(c, "RelativeRotation", c.Outer?.Class?.Name.Text == "DecalActor" && c.ExportType.EndsWith("DecalComponent", StringComparison.Ordinal) ? new FRotator(-90, 0, 0) : new FRotator(0, 0, 0));
        var s = Prop(c, "RelativeScale3D", new FVector(1, 1, 1));
        var q = r.Quaternion();
        return Matrix4x4.CreateScale((float)s.X, (float)s.Y, (float)s.Z)
               * Matrix4x4.CreateFromQuaternion(Quaternion.Normalize(new Quaternion((float)q.X, (float)q.Y, (float)q.Z, (float)q.W)))
               * Matrix4x4.CreateTranslation((float)l.X, (float)l.Y, (float)l.Z);
    }

    static Matrix4x4 Of(FTransform t)
    {
        var q = t.Rotation;
        var quat = new Quaternion((float)q.X, (float)q.Y, (float)q.Z, (float)q.W);
        quat = quat.LengthSquared() > 1e-8f ? Quaternion.Normalize(quat) : Quaternion.Identity;
        return Matrix4x4.CreateScale((float)t.Scale3D.X, (float)t.Scale3D.Y, (float)t.Scale3D.Z)
               * Matrix4x4.CreateFromQuaternion(quat)
               * Matrix4x4.CreateTranslation((float)t.Translation.X, (float)t.Translation.Y, (float)t.Translation.Z);
    }
}

static class MaterialService
{
    /// <summary>"/Game/X/T_A.0" (CUE4Parse's export index) -> "/Game/X/T_A.T_A".</summary>
    public static string ObjectPath(JToken reference)
    {
        if (reference == null || reference.Type != JTokenType.Object) return null;
        var path = (string)reference["ObjectPath"];
        var name = (string)reference["ObjectName"] ?? "";
        if (string.IsNullOrEmpty(path)) return null;
        var q = name.IndexOf('\'');
        if (q >= 0) name = name[(q + 1)..].TrimEnd('\'');
        name = name.Split(':').Last().Split('.').Last();
        var dot = path.LastIndexOf('.');
        return dot > 0 && path[(dot + 1)..].All(char.IsDigit) ? path[..dot] + "." + name : path;
    }
}
