// Generated by materialporter/tools/sync_fork.py from MaterialPorter.Core/IslandProjects.cs - edit it there.
#nullable disable
using System.Collections.Concurrent;
using System.Text.RegularExpressions;
using global::CUE4Parse.FileProvider;
using global::CUE4Parse.UE4.Assets.Exports;
using global::CUE4Parse.UE4.Assets.Objects;
using global::CUE4Parse.UE4.Assets.Objects.Properties;
using global::CUE4Parse.UE4.Versions;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FortnitePorting.MaterialPorter;

/// <summary>
/// The creators' own UEFN projects, for an island's masters. A cooked island ships its materials without
/// their editor graphs (no &lt;path&gt;.o.uasset), so there is nothing to translate; the creator's uncooked
/// project has them (Content\...\M_X.uasset holds the Material and its MaterialEditorOnlyData with every
/// expression). A project folder is any folder under a configured root with a *.uefnproject file; its mount
/// (the "/Name/" its object paths start with) is its .uplugin's name. An island's cooked paths are
/// "/&lt;guid&gt;/&lt;rel&gt;": the project's graph is read from Content\&lt;rel&gt;.uasset and its mount
/// rewritten to the island's, so the textures and functions it names are the cooked pak's own.
/// </summary>
public static class IslandProjects
{
    /// <summary>The folders searched for projects (a setting); MATERIAL_PORTER_PROJECTS (semicolon-separated) always adds to them.</summary>
    public static IReadOnlyList<string> Roots
    {
        get => roots;
        set
        {
            lock (gate)
            {
                roots = (value ?? Array.Empty<string>()).Where(r => !string.IsNullOrWhiteSpace(r)).Select(r => r.Trim()).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
                Reset();
            }
        }
    }

    /// <summary>What the host shows (one line each: a pairing); and what only a trace needs (an asset taken from another project).</summary>
    public static Action<string> Log { get; set; } = _ => { };
    public static Action<string> Debug { get; set; } = _ => { };

    static readonly object gate = new();
    static IReadOnlyList<string> roots = Array.Empty<string>();
    static List<Project> projects;
    static readonly Dictionary<string, Project> pairs = new(StringComparer.OrdinalIgnoreCase);     // guid -> project (null: none)
    static readonly Dictionary<string, Hit> hits = new(StringComparer.OrdinalIgnoreCase);          // guid/rel -> where it comes from
    static readonly HashSet<string> own = new(StringComparer.OrdinalIgnoreCase), other = new(StringComparer.OrdinalIgnoreCase);

    static readonly Regex IslandPath = new(@"^/?([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(.+)$", RegexOptions.IgnoreCase);
    static readonly HashSet<string> NoDescend = new(StringComparer.OrdinalIgnoreCase)
        { "Content", "Saved", "Intermediate", "Binaries", "Resources", "Plugins", "Config", "Source", "node_modules" };

    /// <summary>A UEFN project on disk.</summary>
    public sealed class Project
    {
        public string Name { get; init; }
        public string Folder { get; init; }
        /// <summary>The name its object paths start with ("/Cristaline/...").</summary>
        public string Mount { get; init; }
        DefaultFileProvider provider;

        /// <summary>The project's uncooked asset file for a content-relative path ("A/B/M_X"), or null.</summary>
        public string FileOf(string rel)
        {
            var f = System.IO.Path.Combine(Folder, "Content", rel.Replace('/', System.IO.Path.DirectorySeparatorChar) + ".uasset");
            return File.Exists(f) ? f : null;
        }

        /// <summary>One provider over the project folder, made on first use (15,000 files: a couple of seconds).</summary>
        public DefaultFileProvider Provider
        {
            get
            {
                lock (this)
                {
                    if (provider != null) return provider;
                    var p = new DefaultFileProvider(Folder, SearchOption.AllDirectories, new VersionContainer(EGame.GAME_UE6_0), StringComparer.OrdinalIgnoreCase);
                    p.Initialize();
                    p.Mount();
                    return provider = p;
                }
            }
        }

        /// <summary>The provider's key of the package at a content-relative path (CUE4Parse prefixes a loose file with its root folder's name).</summary>
        public string KeyOf(string rel)
        {
            var files = Provider.Files;
            foreach (var k in new[] { System.IO.Path.GetFileName(Folder) + "/Content/" + rel + ".uasset", "Content/" + rel + ".uasset" })
                if (files.TryGetValue(k, out var f)) return f.Path;
            return null;
        }
    }

    /// <summary>Where an island asset's graph comes from.</summary>
    public sealed class Hit
    {
        public Project Project { get; init; }
        public string Guid { get; init; }
        /// <summary>The asset's path inside the island's Content ("A/B/M_X").</summary>
        public string Rel { get; init; }
        /// <summary>The island's own project (false: another configured project holding the same content-relative path, a pack's).</summary>
        public bool Own { get; init; }
        /// <summary>The project's file (its time says whether a cached graph is still good).</summary>
        public string File { get; init; }
    }

    // MATERIAL_PORTER_NO_PROJECTS=1: no project at all (tests of an island master's approximation)
    static IEnumerable<string> AllRoots() =>
        Environment.GetEnvironmentVariable("MATERIAL_PORTER_NO_PROJECTS") == "1" ? Array.Empty<string>() :
        roots.Concat((Environment.GetEnvironmentVariable("MATERIAL_PORTER_PROJECTS") ?? "").Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
             .Distinct(StringComparer.OrdinalIgnoreCase);

    static void Reset()
    {
        projects = null;
        pairs.Clear();
        hits.Clear();
        own.Clear();
        other.Clear();
    }

    /// <summary>Every project under the roots (each root, then three folder levels down; a project's own folders aren't searched).</summary>
    public static IReadOnlyList<Project> All
    {
        get
        {
            lock (gate)
            {
                if (projects != null) return projects;
                var found = new List<Project>();
                foreach (var root in AllRoots())
                    if (Directory.Exists(root)) Walk(root, 0, found);
                Log?.Invoke(found.Count == 0 ? "UEFN projects: none found under " + string.Join("; ", AllRoots())
                                              : $"UEFN projects: {found.Count} under {string.Join("; ", AllRoots())}");
                return projects = found;
            }
        }
    }

    static void Walk(string dir, int depth, List<Project> found)
    {
        try
        {
            var marks = Directory.GetFiles(dir, "*.uefnproject");
            if (marks.Length > 0)
            {
                if (found.Any(p => p.Folder.Equals(dir, StringComparison.OrdinalIgnoreCase))) return;
                var stem = System.IO.Path.GetFileNameWithoutExtension(marks[0]);
                var plugins = Directory.GetFiles(dir, "*.uplugin");
                var plugin = plugins.FirstOrDefault(f => System.IO.Path.GetFileNameWithoutExtension(f).Equals(stem, StringComparison.OrdinalIgnoreCase)) ?? plugins.FirstOrDefault();
                var folder = System.IO.Path.GetFileName(dir.TrimEnd('\\', '/'));
                found.Add(new Project
                {
                    Name = folder, Folder = dir,
                    Mount = plugin != null ? System.IO.Path.GetFileNameWithoutExtension(plugin) : folder,
                });
                return;
            }
            if (depth >= 3) return;
            foreach (var sub in Directory.GetDirectories(dir))
            {
                var name = System.IO.Path.GetFileName(sub);
                if (name.StartsWith('.') || name.StartsWith('$') || NoDescend.Contains(name)) continue;
                Walk(sub, depth + 1, found);
            }
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException) { /* a folder this user can't read */ }
    }

    /// <summary>"/&lt;guid&gt;/A/B/M_X.M_X" (or ".0", ".o") -> (guid, "A/B/M_X"); not an island path: null.</summary>
    public static (string Guid, string Rel)? Split(string path)
    {
        if (string.IsNullOrEmpty(path)) return null;
        var p = path.Trim();
        var dot = p.LastIndexOf('.');
        if (dot > p.LastIndexOf('/')) p = p[..dot];
        if (p.EndsWith(".o")) p = p[..^2];
        var m = IslandPath.Match(p);
        return m.Success ? (m.Groups[1].Value, m.Groups[2].Value) : null;
    }

    /// <summary>
    /// The island's project: the one holding the most of up to 50 packages sampled evenly from the island's
    /// cooked files (a pack several projects share only scores where the island's own project has it too).
    /// Said once; null with nothing near (under half of the sample: the island is somebody else's).
    /// </summary>
    static Project PairOf(IFileProvider game, string guid)
    {
        lock (gate)
        {
            if (pairs.TryGetValue(guid, out var done)) return done;
            var all = All;
            Project best = null;
            var sample = new List<string>();
            var score = 0;
            if (all.Count > 0)
            {
                var marker = "/" + guid + "/Content/";
                var keys = new List<string>();
                foreach (var key in game.Files.Keys)
                {
                    if (!key.EndsWith(".uasset", StringComparison.OrdinalIgnoreCase) || key.EndsWith(".o.uasset", StringComparison.OrdinalIgnoreCase)) continue;
                    var at = key.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
                    if (at >= 0) keys.Add(key[(at + marker.Length)..^".uasset".Length]);
                }
                keys.Sort(StringComparer.OrdinalIgnoreCase);
                var take = Math.Min(50, keys.Count);
                for (var i = 0; i < take; i++) sample.Add(keys[(int)((long)i * keys.Count / take)]);
                foreach (var p in all)
                {
                    var n = sample.Count(rel => p.FileOf(rel) != null);
                    if (n > score) (best, score) = (p, n);
                }
                if (best != null && score * 2 < sample.Count) best = null;
            }
            pairs[guid] = best;
            if (all.Count > 0)
                Log?.Invoke(best != null ? $"island {guid} is the UEFN project {best.Name} at {best.Folder} ({score} of {sample.Count} sampled packages)"
                                         : $"island {guid} matches none of the {all.Count} UEFN projects ({score} of {sample.Count} sampled packages at best)");
            return best;
        }
    }

    /// <summary>
    /// Where an island asset ("/&lt;guid&gt;/A/B/M_X.M_X") has its uncooked package: the island's project when it
    /// has it, else any configured project holding that exact content-relative path (a marketplace pack keeps
    /// its paths across the projects that own it). Null: not an island path, or no project has it.
    /// </summary>
    public static Hit Find(IFileProvider game, string path)
    {
        if (Split(path) is not { } s) return null;
        lock (gate)
        {
            if (!AllRoots().Any()) return null;
            var id = s.Guid + "/" + s.Rel;
            if (hits.TryGetValue(id, out var cached)) return cached;
            var all = All;
            if (all.Count == 0) return null;
            var paired = PairOf(game, s.Guid);
            Hit hit = null;
            if (paired?.FileOf(s.Rel) is { } f)
                hit = new Hit { Project = paired, Guid = s.Guid, Rel = s.Rel, Own = true, File = f };
            else
                foreach (var p in all)
                    if (p != paired && p.FileOf(s.Rel) is { } f2)
                    {
                        hit = new Hit { Project = p, Guid = s.Guid, Rel = s.Rel, Own = false, File = f2 };
                        Debug?.Invoke($"island {s.Guid}: {s.Rel} is not in its project{(paired == null ? "" : " " + paired.Name)}; read from the UEFN project {p.Name}");
                        break;
                    }
            if (hit == null) return null;      // (not cached: a project added since is looked at again)
            (hit.Own ? own : other).Add(id);
            return hits[id] = hit;
        }
    }

    /// <summary>What was read from where, so far: the assets of the island's own project and those of another.</summary>
    public static (int Own, int Other, string[] OtherAssets, Dictionary<string, string> Pairs) Counts()
    {
        lock (gate)
            return (own.Count, other.Count, other.OrderBy(x => x).ToArray(),
                    pairs.ToDictionary(kv => kv.Key, kv => kv.Value == null ? null : kv.Value.Name + " @ " + kv.Value.Folder));
    }

    /// <summary>
    /// The project's exports as ue_graph reads a graph dump (what an .o.uasset's exports give), with the
    /// project's mount named as the island's. Two things differ in an uncooked package: its object paths
    /// start with the project's mount, and its enum values are the bare member names ("FunctionInput_Scalar"
    /// where the cooked path, through the game's mappings, writes "EFunctionInputType::FunctionInput_Scalar":
    /// the translator compares those whole).
    /// </summary>
    public static string ToIsland(IEnumerable<UObject> exports, JsonSerializerSettings ser, Hit hit)
    {
        var list = exports.ToArray();
        var json = JArray.Parse(JsonConvert.SerializeObject(list, Formatting.None, ser));
        for (var i = 0; i < list.Length && i < json.Count; i++)
        {
            // (only the export's Properties: its own Type, Name... are not enum values)
            var enums = new Dictionary<string, EnumNode>(StringComparer.Ordinal);
            CollectEnums(list[i].Properties, enums);
            if (enums.Count > 0 && json[i]["Properties"] is JObject properties) QualifyEnums(properties, enums);
        }
        return ToIsland(json.ToString(Formatting.None), hit);
    }

    /// <summary>A property that holds an enum (its name), or a struct whose members may.</summary>
    sealed class EnumNode
    {
        public string Enum;
        public Dictionary<string, EnumNode> Fields;
    }

    static EnumNode Node(Dictionary<string, EnumNode> into, string name)
    {
        if (!into.TryGetValue(name, out var node)) into[name] = node = new EnumNode();
        return node;
    }

    /// <summary>Which properties of an export (and of the structs and arrays of structs inside it) are enum-valued, and of which enum.</summary>
    static void CollectEnums(IEnumerable<FPropertyTag> props, Dictionary<string, EnumNode> into)
    {
        foreach (var p in props)
            if (p.Tag != null) VisitEnum(p.Name.Text, p.Tag, p.TagData, into);
    }

    static void VisitEnum(string name, FPropertyTagType tag, FPropertyTagData data, Dictionary<string, EnumNode> into)
    {
        switch (tag)
        {
            case EnumProperty when data?.EnumName is { } en && !en.Equals("None", StringComparison.OrdinalIgnoreCase):
                Node(into, name).Enum = en;
                break;
            case StructProperty { Value.StructType: FStructFallback inner }:
                var node = Node(into, name);
                CollectEnums(inner.Properties, node.Fields ??= new Dictionary<string, EnumNode>(StringComparer.Ordinal));
                break;
            case ArrayProperty { Value: { } array }:
                foreach (var item in array.Properties)
                    if (item != null) VisitEnum(name, item, array.InnerTagData ?? data?.InnerTypeData, into);
                break;
        }
    }

    /// <summary>The bare enum values of these properties, qualified with the enum's name, down the structs that hold them.</summary>
    static void QualifyEnums(JObject obj, Dictionary<string, EnumNode> map)
    {
        static bool Bare(JToken t) => t is JValue { Type: JTokenType.String } v && (string)v is { Length: > 0 } text && text != "None" && !text.Contains("::");
        foreach (var prop in obj.Properties().ToList())
        {
            if (!map.TryGetValue(prop.Name, out var node)) continue;
            if (node.Enum != null)
            {
                if (Bare(prop.Value)) prop.Value = node.Enum + "::" + (string)(JValue)prop.Value;
                else if (prop.Value is JArray values)
                    foreach (var item in values.Where(Bare).ToList()) item.Replace(node.Enum + "::" + (string)(JValue)item);
            }
            if (node.Fields == null) continue;
            if (prop.Value is JObject one) QualifyEnums(one, node.Fields);
            else if (prop.Value is JArray many)
                foreach (var each in many.OfType<JObject>()) QualifyEnums(each, node.Fields);
        }
    }

    /// <summary>A dump's text with the project's mount named as the island's.</summary>
    public static string ToIsland(string json, Hit hit)
    {
        foreach (var quote in new[] { "\"/", "'/" })
            json = json.Replace(quote + hit.Project.Mount + "/", quote + hit.Guid + "/", StringComparison.OrdinalIgnoreCase);
        return json;
    }
}
