// Generated by materialporter/tools/sync_fork.py from MaterialPorter.Core/MaterialService.cs - edit it there.
#nullable disable
using global::CUE4Parse.UE4.Assets.Exports.Texture;
using global::CUE4Parse_Conversion.Options;
using global::CUE4Parse_Conversion.Textures;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FortnitePorting.MaterialPorter;

/// <summary>
/// Everything a Blender build needs about one material instance: its chain to
/// the master, the master's graph (dumped as ue_graph reads it) and asset
/// settings, and the parameter values the instance chain sets (child first).
/// </summary>
public sealed class MaterialInfo
{
    public string Name { get; set; }
    public string Path { get; set; }
    public string Master { get; set; }
    public string Graph { get; set; }
    public List<string> Chain { get; set; } = new();
    public Dictionary<string, object> Asset { get; set; } = new();
    public Dictionary<string, object> Overrides { get; set; } = new();
    public Dictionary<string, double> Scalars { get; set; } = new();
    public Dictionary<string, double[]> Vectors { get; set; } = new();
    public Dictionary<string, string> Textures { get; set; } = new();
    public Dictionary<string, bool> Switches { get; set; } = new();
    public Dictionary<string, bool[]> Masks { get; set; } = new();
    /// <summary>The Subsurface Profile skin scatters by (the nearest instance overriding it, else the master's).</summary>
    public SubsurfaceInfo Subsurface { get; set; }
    /// <summary>
    /// The master was cooked without its editor graph (a UEFN island's own
    /// material): nothing to translate, Blender builds an approximation from
    /// the textures and values.
    /// </summary>
    public bool Fallback { get; set; }
    /// <summary>Every texture the master samples, parameter or hard-coded (a fallback's only way to know the fixed ones).</summary>
    public List<string> ReferencedTextures { get; set; } = new();

    static readonly JsonSerializer Snake = JsonSerializer.Create(new JsonSerializerSettings
    {
        ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver
        {
            NamingStrategy = new Newtonsoft.Json.Serialization.SnakeCaseNamingStrategy(),
        },
    });

    /// <summary>As the Blender extension reads it (snake_case; parameter names as they are).</summary>
    public JObject ToJson() => JObject.FromObject(this, Snake);
}

/// <summary>
/// A Subsurface Profile, as Blender's subsurface wants it: Radius (per
/// channel, relative) and Scale (metres). UE's Burley profile scatters over
/// MeanFreePathColor x MeanFreePathDistance / WorldUnitScale cm (Fortnite's
/// skin: ~2.6 / 1.5 / 0.7 mm, measured skin's range); the legacy one over
/// FalloffColor x ScatterRadius x WorldUnitScale cm.
/// </summary>
public sealed class SubsurfaceInfo
{
    public string Profile { get; set; }
    public double[] Radius { get; set; }
    public double Scale { get; set; }
}

/// <summary>A texture on disk, as Blender should read it.</summary>
public sealed class TextureFile
{
    public string File { get; set; }
    public bool Srgb { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
    /// <summary>"2d", "cube", "volume" or "array"; volumes and arrays are stacks of slices, slice 0 on top.</summary>
    public string Kind { get; set; } = "2d";
    public int Depth { get; set; } = 1;
    public bool Hdr { get; set; }
    /// <summary>Sampled unfiltered (its Filter TF_Nearest, or the Pixels2D group): a LUT, a pixel grid.</summary>
    public bool Nearest { get; set; }
    /// <summary>How UE addresses it past 0..1, per axis (AddressX, AddressY): "Wrap", "Clamp" or "Mirror".</summary>
    public string AddressX { get; set; } = "Wrap";
    public string AddressY { get; set; } = "Wrap";
    /// <summary>The cooked pixel format (PF_DXT1, PF_BC5, ...).</summary>
    public string Format { get; set; }
}

public sealed class MaterialService
{
    readonly GameContext game;
    readonly string cache;
    readonly SemaphoreSlim gate = new(1, 1);   // CUE4Parse loads, one at a time
    readonly Dictionary<string, object> memo = new();

    static readonly JsonSerializerSettings Ser = new() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

    public MaterialService(GameContext game)
    {
        this.game = game;
        cache = Directory.CreateDirectory(System.IO.Path.Combine(GameContext.DataDir, "cache")).FullName;
    }

    string Dir(string sub) => Directory.CreateDirectory(System.IO.Path.Combine(cache, game.BuildVersion, sub)).FullName;

    static string Safe(string key) =>
        string.Join("~", key.Replace(".o.uasset", "").Replace(".uasset", "").Split('/', StringSplitOptions.RemoveEmptyEntries));

    // ------------------------------------------------------------ paths
    /// <summary>
    /// "/Game/..", "/Engine/..", "/Plugin/..", "Pkg.Object", "Pkg.0" or a file
    /// key -> the file key of "&lt;package&gt;&lt;ext&gt;" if the game has it.
    /// </summary>
    public string ResolveKey(string p, string ext)
    {
        var provider = game.Provider;
        p = p.Trim();
        var dot = p.LastIndexOf('.');
        if (dot > p.LastIndexOf('/')) p = p[..dot];
        if (p.EndsWith(".o")) p = p[..^2];
        var tries = new List<string>();
        if (p.StartsWith("/Game/")) tries.Add("FortniteGame/Content/" + p[6..]);
        else if (p.StartsWith("/Engine/")) tries.Add("Engine/Content/" + p[8..]);
        else if (!p.StartsWith("/")) tries.Add(p);
        try { tries.Add(provider.FixPath(p)); } catch { /* not a mount path */ }
        foreach (var t in tries)
        {
            var baseKey = t;
            var d2 = baseKey.LastIndexOf('.');
            if (d2 > baseKey.LastIndexOf('/')) baseKey = baseKey[..d2];
            var k = baseKey + ext;
            if (provider.Files.TryGetValue(k, out var f)) return f.Path;
        }
        // a plugin mount: "/Plugin/Rest/Name" -> a key ending ".../Rest/Name<ext>" under that plugin
        if (p.StartsWith("/"))
        {
            var parts = p.Trim('/').Split('/');
            var tail = "/" + string.Join('/', parts.Skip(1)) + ext;
            var hit = provider.Files.Keys.FirstOrDefault(k => k.EndsWith(tail, StringComparison.OrdinalIgnoreCase)
                                                             && k.Contains("/" + parts[0] + "/", StringComparison.OrdinalIgnoreCase));
            if (hit != null) return provider.Files[hit].Path;
        }
        return null;
    }

    /// <summary>"/Game/X/T_A.0" (CUE4Parse's export index) -> "/Game/X/T_A.T_A".</summary>
    public static string ObjectPath(JToken reference)
    {
        if (reference == null || reference.Type != JTokenType.Object) return null;
        var path = (string)reference["ObjectPath"];
        var name = (string)reference["ObjectName"] ?? "";
        if (string.IsNullOrEmpty(path)) return null;
        var q = name.IndexOf('\'');
        if (q >= 0) name = name[(q + 1)..].TrimEnd('\'');
        name = name.Split(':').Last().Split('.').Last();
        var dot = path.LastIndexOf('.');
        return dot > 0 && path[(dot + 1)..].All(char.IsDigit) ? path[..dot] + "." + name : path;
    }

    async Task<T> Locked<T>(Func<Task<T>> f)
    {
        await gate.WaitAsync();
        try { return await f(); }
        finally { gate.Release(); }
    }

    /// <summary>A package's main export (the one named after it), as JSON.</summary>
    async Task<JObject> MainExportAsync(string path)
    {
        var key = ResolveKey(path, ".uasset") ?? throw new FileNotFoundException("No package for " + path);
        var pkg = await game.Provider.LoadPackageAsync(key);
        var name = System.IO.Path.GetFileNameWithoutExtension(key);
        var obj = pkg.GetExports().FirstOrDefault(e => e.Name == name) ?? pkg.GetExports().First();
        return JObject.Parse(JsonConvert.SerializeObject(obj, Ser));
    }

    // ------------------------------------------------------------ graphs
    /// <summary>
    /// The expression graph of a material or material function (it lives in the
    /// editor-only package, &lt;path&gt;.o.uasset), dumped as ue_graph reads it.
    /// </summary>
    public Task<string> GraphAsync(string path) => Locked(async () =>
    {
        var key = ResolveKey(path, ".o.uasset") ?? throw new FileNotFoundException("No editor graph for " + path);
        var file = System.IO.Path.Combine(Dir("graphs"), Safe(key) + ".json");
        if (File.Exists(file)) return file;
        var pkg = await game.Provider.LoadPackageAsync(key);
        await File.WriteAllTextAsync(file, JsonConvert.SerializeObject(pkg.GetExports().ToArray(), Formatting.None, Ser));
        return file;
    });

    // ------------------------------------------------------------ instances
    /// <summary>An instance (or a material) and everything its chain sets, child first.</summary>
    public async Task<MaterialInfo> DescribeAsync(string path)
    {
        var sw = System.Diagnostics.Stopwatch.StartNew();
        var info = await Locked(() => ChainAsync(path));
        await Locked(async () => { SkyValues(info, await DayValuesAsync()); return true; });
        if (info.Master != null && ResolveKey(info.Master, ".o.uasset") == null)
        {
            info.Fallback = true;
            await Locked(() => CookedDefaultsAsync(info));
        }
        else if (info.Master != null) info.Graph = await GraphAsync(info.Master);
        Timing.Log("describe " + Bridge.ShortName(path), sw);
        return info;
    }

    /// <summary>
    /// A sky dome's material (a master named M_Sky*) and its sun and moon's (a master
    /// naming a moon) get what the day sequence gives the sky mesh's "Skydome" and "SunMoon"
    /// slots: the season's dome, whose parameters every M_Sky master shares.
    /// </summary>
    static void SkyValues(MaterialInfo info, DayValues day)
    {
        var master = (info.Master ?? "").Split('/').Last().Split('.')[0];
        var slot = master.StartsWith("M_Sky", StringComparison.OrdinalIgnoreCase) ? "Skydome"
                   : master.Contains("Moon", StringComparison.OrdinalIgnoreCase) ? "SunMoon" : null;
        if (slot == null || !day.Slots.TryGetValue(slot, out var set)) return;
        foreach (var (k, v) in set.Scalars) info.Scalars[k] = v;
        foreach (var (k, v) in set.Vectors) info.Vectors[k] = v;
    }

    async Task<MaterialInfo> ChainAsync(string path)
    {
        var info = new MaterialInfo { Path = path, Name = path.Split('/').Last().Split('.').Last() };
        var cur = path;
        string profile = null;
        for (var depth = 0; depth < 24 && cur != null; depth++)
        {
            var obj = await MainExportAsync(cur);
            info.Chain.Add(cur);
            var p = obj["Properties"] as JObject ?? new JObject();
            // an instance's profile counts when it overrides; the master's otherwise
            if (profile == null && ((string)obj["Type"] == "Material" || (bool?)p["bOverrideSubsurfaceProfile"] == true))
                profile = ObjectPath(p["SubsurfaceProfile"]);
            if ((string)obj["Type"] == "Material")
            {
                info.Master = cur;
                foreach (var k in new[] { "BlendMode", "ShadingModel", "TwoSided", "OpacityMaskClipValue", "bUseMaterialAttributes",
                                          "bTangentSpaceNormal", "MaterialDomain", "bIsSky", "bUsedWithSkeletalMesh",
                                          "TranslucencyLightingMode", "bAllowNegativeEmissiveColor" })
                    if (p[k] != null) info.Asset[k] = p[k].ToObject<object>();
                // UE's default, which the cooked asset leaves out (the add-on tells it from an older app's silence)
                info.Asset.TryAdd("TranslucencyLightingMode", "ETranslucencyLightingMode::TLM_VolumetricNonDirectional");
                // a master's own parameters are its graph's defaults: the translator reads those
                break;
            }
            Collect(p, info);
            cur = ObjectPath(p["Parent"]);
        }
        if (profile != null)
        {
            try { info.Subsurface = await ProfileAsync(profile); }
            catch { /* no profile to read: Blender's skin radius */ }
        }
        return info;
    }

    /// <summary>
    /// A cooked master's parameter defaults (CachedExpressionData: each runtime
    /// parameter type's names beside its values) where the instances set none,
    /// and every texture it references.
    /// </summary>
    async Task<bool> CookedDefaultsAsync(MaterialInfo info)
    {
        var obj = await MainExportAsync(info.Master);
        if (obj["CachedExpressionData"] is JObject ced)
        {
            JArray Names(int type) => ced[type == 0 ? "RuntimeEntries" : $"RuntimeEntries[{type}]"]?["ParameterInfoSet"] as JArray ?? new JArray();
            var scalars = ced["ScalarValues"] as JArray ?? new JArray();
            var vectors = ced["VectorValues"] as JArray ?? new JArray();
            var textures = ced["TextureValues"] as JArray ?? new JArray();
            var n = Names(0);
            for (var i = 0; i < n.Count && i < scalars.Count; i++)
                if ((string)n[i]["Name"] is { } name) info.Scalars.TryAdd(name, (double?)scalars[i] ?? 0);
            n = Names(1);
            for (var i = 0; i < n.Count && i < vectors.Count; i++)
                if ((string)n[i]["Name"] is { } name && vectors[i] is JObject v)
                    info.Vectors.TryAdd(name, new[] { (double?)v["R"] ?? 0, (double?)v["G"] ?? 0, (double?)v["B"] ?? 0, (double?)v["A"] ?? 1 });
            n = Names(3);
            for (var i = 0; i < n.Count && i < textures.Count; i++)
                if ((string)n[i]["Name"] is { } name && ObjectPath(textures[i]) is { } t) info.Textures.TryAdd(name, t);
        }
        try
        {
            if (await game.Provider.LoadPackageObjectAsync(info.Master) is global::CUE4Parse.UE4.Assets.Exports.Material.UMaterial m)
            {
                var list = new List<global::CUE4Parse.UE4.Assets.Exports.Material.UUnrealMaterial>();
                m.AppendReferencedTextures(list, false);
                foreach (var t in list.OfType<UTexture>().Concat(ImportedTextures(m)))
                    if (t.GetPathName() is { } tp && !info.ReferencedTextures.Contains(tp)) info.ReferencedTextures.Add(tp);
            }
        }
        catch { /* only the parameters' textures, then */ }
        foreach (var t in info.Textures.Values)
            if (!info.ReferencedTextures.Contains(t)) info.ReferencedTextures.Add(t);
        return true;
    }

    /// <summary>
    /// The textures a cooked material's package imports: the ones its graph samples
    /// directly. CUE4Parse fills ReferencedTextures this way only when the provider
    /// allows it (FortnitePorting's skips it), and an island's masters have no others.
    /// </summary>
    public static List<UTexture> ImportedTextures(global::CUE4Parse.UE4.Assets.Exports.UObject material)
    {
        var found = new List<UTexture>();
        if (material.Owner is not global::CUE4Parse.UE4.Assets.AbstractUePackage pkg) return found;
        for (var i = 0; i < pkg.ImportMapLength; i++)
        {
            try
            {
                var r = pkg.ResolvePackageIndex(new global::CUE4Parse.UE4.Objects.UObject.FPackageIndex(pkg, -i - 1));
                if (r?.Class?.Name.Text.StartsWith("Texture", StringComparison.OrdinalIgnoreCase) == true
                    && r.TryLoad(out var tex) && tex is UTexture t)
                    found.Add(t);
            }
            catch { /* an import this build can't resolve */ }
        }
        return found;
    }

    async Task<SubsurfaceInfo> ProfileAsync(string path)
    {
        var s = (await MainExportAsync(path))["Properties"]?["Settings"];
        if (s == null) return null;
        double F(string k, double d) => (double?)s[k] ?? d;
        double[] Rgb(string k) => s[k] is JObject c ? new[] { (double?)c["R"] ?? 1, (double?)c["G"] ?? 1, (double?)c["B"] ?? 1 } : new[] { 1.0, 0.2, 0.1 };
        var wus = Math.Max(1e-4, F("WorldUnitScale", 0.1));
        var burley = (bool?)s["bEnableBurley"] ?? true;
        var cm = burley ? F("MeanFreePathDistance", 1.2) / wus : F("ScatterRadius", 1.2) * wus;
        return new SubsurfaceInfo
        {
            Profile = path.Split('/').Last().Split('.').Last(),
            Radius = burley ? Rgb("MeanFreePathColor") : Rgb("FalloffColor"),
            Scale = cm * 0.01,
        };
    }

    /// <summary>One level of the chain: values the child didn't set already.</summary>
    static void Collect(JObject p, MaterialInfo info)
    {
        static string Name(JToken e) => (string)e["ParameterInfo"]?["Name"] ?? (string)e["ParameterName"];
        foreach (var e in p["ScalarParameterValues"] ?? new JArray())
            info.Scalars.TryAdd(Name(e), (double)e["ParameterValue"]);
        foreach (var e in p["VectorParameterValues"] ?? new JArray())
        {
            var v = e["ParameterValue"];
            info.Vectors.TryAdd(Name(e), new[] { (double)v["R"], (double)v["G"], (double)v["B"], (double?)v["A"] ?? 1.0 });
        }
        foreach (var e in p["TextureParameterValues"] ?? new JArray())
        {
            var t = ObjectPath(e["ParameterValue"]);
            if (t != null) info.Textures.TryAdd(Name(e), t);
        }
        // static values: UE 5 keeps them in StaticParametersRuntime (older builds, StaticParameters)
        foreach (var sp in new[] { p["StaticParametersRuntime"], p["StaticParameters"] })
        {
            if (sp == null) continue;
            foreach (var e in sp["StaticSwitchParameters"] ?? new JArray())
                info.Switches.TryAdd(Name(e), (bool?)e["Value"] ?? false);
            foreach (var e in sp["StaticComponentMaskParameters"] ?? new JArray())
                info.Masks.TryAdd(Name(e), new[] { (bool?)e["R"] ?? false, (bool?)e["G"] ?? false, (bool?)e["B"] ?? false, (bool?)e["A"] ?? false });
        }
        // an override set to the struct's default value (Opaque, DefaultLit, one-sided...)
        // isn't serialized, only its bOverride_ flag: that default is the override
        if (p["BasePropertyOverrides"] is JObject o)
            foreach (var (k, d) in OverrideDefaults)
                if ((bool?)o["bOverride_" + k] == true)
                    info.Overrides.TryAdd(k, o[k]?.ToObject<object>() ?? d);
    }

    /// <summary>FMaterialInstanceBasePropertyOverrides' defaults (its constructor).</summary>
    static readonly (string Key, object Default)[] OverrideDefaults =
    {
        ("BlendMode", "EBlendMode::BLEND_Opaque"), ("ShadingModel", "EMaterialShadingModel::MSM_DefaultLit"),
        ("TwoSided", false), ("OpacityMaskClipValue", 0.333333), ("bIsThinSurface", false),
    };

    // ------------------------------------------------------------ textures
    readonly System.Collections.Concurrent.ConcurrentDictionary<string, Lazy<Task<TextureFile>>> textures = new(StringComparer.OrdinalIgnoreCase);
    readonly SemaphoreSlim encoders = new(Math.Max(2, Environment.ProcessorCount / 2));

    /// <summary>
    /// A texture decoded to a file in the cache (PNG, or HDR for float
    /// formats), with a sidecar record so a later session reuses it. One task
    /// per texture: a prefetch and Blender's request share it.
    /// </summary>
    /// <summary>
    /// The largest mip textures are exported at (0: full size). A map import
    /// sets it for its duration: hundreds of full-size textures are what makes a
    /// map scene slow to show in Blender, and the smaller mips are often in the
    /// install already (no CDN download).
    /// </summary>
    public int MaxTextureSize { get; set; }

    /// <summary>A texture as a PNG (HDR for float formats): what the app shows and the Files page exports.</summary>
    public Task<TextureFile> TextureAsync(string path) => TextureAsync(path, false);

    /// <summary>
    /// A texture for Blender: where Blender reads the game's own compression
    /// (BC1/BC3/BC5/BC7, BGRA8) the mip's data as it is in a DDS - no decode,
    /// no encode, and Blender loads it faster than a PNG; else the PNG.
    /// </summary>
    public Task<TextureFile> BlenderTextureAsync(string path) => TextureAsync(path, true);

    Task<TextureFile> TextureAsync(string path, bool raw)
    {
        var cap = MaxTextureSize;
        var key = (cap > 0 ? path + "@" + cap : path) + (raw ? "#dds" : "");
        var lazy = textures.GetOrAdd(key, _ => new Lazy<Task<TextureFile>>(() =>
        {
            var t = Task.Run(() => ExportTextureAsync(path, cap, raw));
            // a failure isn't kept: the next ask tries again
            t.ContinueWith(_ => textures.TryRemove(key, out var _), TaskContinuationOptions.OnlyOnFaulted);
            return t;
        }));
        return lazy.Value;
    }

    /// <summary>The game's pixel formats Blender reads from a DDS as they are (DXGI format numbers).</summary>
    static readonly Dictionary<string, uint> RawFormats = new()
    {
        ["PF_DXT1"] = 71, ["PF_DXT3"] = 74, ["PF_DXT5"] = 77, ["PF_BC5"] = 83, ["PF_BC7"] = 98, ["PF_B8G8R8A8"] = 87,
    };

    /// <summary>One mip's data as a DDS file (DX10 header, a single 2D surface).</summary>
    static void WriteDds(string file, int width, int height, uint dxgi, byte[] data)
    {
        using var f = new BinaryWriter(File.Create(file));
        f.Write(0x20534444u);                                   // "DDS "
        f.Write(124u);
        f.Write(0x1u | 0x2u | 0x4u | 0x1000u | 0x80000u);       // caps, height, width, pixel format, linear size
        f.Write((uint)height);
        f.Write((uint)width);
        f.Write((uint)data.Length);
        f.Write(0u);                                            // depth
        f.Write(1u);                                            // mips
        for (var i = 0; i < 11; i++) f.Write(0u);
        f.Write(32u); f.Write(0x4u); f.Write(0x30315844u);      // pixel format: FourCC "DX10"
        for (var i = 0; i < 5; i++) f.Write(0u);
        f.Write(0x1000u); f.Write(0u); f.Write(0u); f.Write(0u); f.Write(0u);
        f.Write(dxgi); f.Write(3u); f.Write(0u); f.Write(1u); f.Write(0u);   // 2D texture, one
        f.Write(data);
    }

    /// <summary>Textures Blender will soon ask for, exported in the background meanwhile.</summary>
    public void Prefetch(IEnumerable<string> paths)
    {
        foreach (var p in paths.Where(p => !string.IsNullOrEmpty(p)))
            _ = BlenderTextureAsync(p).ContinueWith(t => _ = t.Exception, TaskContinuationOptions.OnlyOnFaulted);
    }

    /// <summary>Bumped when what a cached texture file holds changes.</summary>
    const int TextureCacheVersion = 2;

    /// <summary>
    /// Textures made here, not in the game (a LEGO figure's colour grids, an effect's exposed curve):
    /// /MaterialPorter/Generated/&lt;name&gt;.&lt;name&gt; is &lt;GeneratedDir&gt;/&lt;name&gt;.png (or .hdr,
    /// linear), named for its content; a name ending in _Lin is linear, else sRGB.
    /// </summary>
    public const string GeneratedRoot = "/MaterialPorter/Generated/";

    public string GeneratedDir => Directory.CreateDirectory(System.IO.Path.Combine(cache, "generated")).FullName;   // named for content: no version

    TextureFile GeneratedTexture(string path)
    {
        var name = path[GeneratedRoot.Length..].Split('.')[0];
        // an effect's curve past 1 (FortnitePorting's Effects.ExposedCurve): Radiance HDR, linear
        var hdr = System.IO.Path.Combine(GeneratedDir, name + ".hdr");
        if (File.Exists(hdr) && HdrSize(hdr) is (int w, int h))
            return new TextureFile { File = hdr, Width = w, Height = h, Srgb = false, Hdr = true };
        var file = System.IO.Path.Combine(GeneratedDir, name + ".png");
        if (!File.Exists(file)) throw new FileNotFoundException("no generated texture " + name);
        using var codec = SkiaSharp.SKCodec.Create(file);
        return new TextureFile
        {
            File = file, Width = codec.Info.Width, Height = codec.Info.Height,
            Srgb = !name.EndsWith("_Lin", StringComparison.OrdinalIgnoreCase),
        };
    }

    /// <summary>A Radiance HDR file's size, from its header's resolution line ("-Y h +X w"), or null.</summary>
    static (int Width, int Height)? HdrSize(string file)
    {
        using var reader = new StreamReader(file, System.Text.Encoding.ASCII);
        for (var i = 0; i < 32 && reader.ReadLine() is { } line; i++)
        {
            var parts = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 4 && parts[0] is "-Y" or "+Y" && int.TryParse(parts[1], out var h) && int.TryParse(parts[3], out var w))
                return (w, h);
        }
        return null;
    }

    async Task<TextureFile> ExportTextureAsync(string path, int cap = 0, bool raw = false)
    {
        if (path.StartsWith(GeneratedRoot, StringComparison.OrdinalIgnoreCase)) return GeneratedTexture(path);
        var sw = System.Diagnostics.Stopwatch.StartNew();
        var tex = await game.Provider.LoadPackageObjectAsync<UTexture>(path);
        var stem = System.IO.Path.Combine(Dir("textures"), Safe(ResolveKey(path, ".uasset") ?? path));
        // a copy made while the full-size mips couldn't stream is made again once they can
        var full = tex.PlatformData?.Mips?.FirstOrDefault()?.SizeX ?? 0;
        if (cap > 0 && full > cap)
        {
            stem += "@" + cap;      // kept apart from the full-size copy
            full = cap;
        }
        else cap = 0;
        var meta = stem + (raw ? ".dds" : "") + ".meta.json";
        try
        {
            if (File.Exists(meta))
            {
                var rec = JsonConvert.DeserializeObject<CachedTexture>(await File.ReadAllTextAsync(meta));
                if (rec?.Version == TextureCacheVersion && rec.Texture != null && File.Exists(rec.Texture.File) && rec.Texture.Width >= full)
                {
                    Timing.Log($"texture {Bridge.ShortName(path)} (cached)", sw);
                    return Sampling(rec.Texture, tex);
                }
            }
        }
        catch { /* a broken record: export again */ }

        // the mip's own data, when Blender reads its format: nothing to decode or encode
        if (raw && tex is UTexture2D t2 && t2.PlatformData is { } pd && pd.VTData == null && RawFormats.TryGetValue(pd.PixelFormat ?? "", out var dxgi))
        {
            try
            {
                var mip = pd.Mips.Where(m => cap <= 0 || m.SizeX <= cap).FirstOrDefault(m => m.EnsureValidBulkData(null, 0));
                if (mip?.BulkData?.Data is { Length: > 0 } bytes)
                {
                    var file = stem + ".dds";
                    WriteDds(file, mip.SizeX, mip.SizeY, dxgi, bytes);
                    var rec = Sampling(new TextureFile { File = file, Srgb = tex.SRGB, Width = mip.SizeX, Height = mip.SizeY }, tex);
                    await File.WriteAllTextAsync(meta, JsonConvert.SerializeObject(new CachedTexture { Version = TextureCacheVersion, Texture = rec }));
                    Timing.Log($"texture {Bridge.ShortName(path)} {mip.SizeX}x{mip.SizeY} {pd.PixelFormat} as DDS", sw);
                    return rec;
                }
            }
            catch (Exception e) { Timing.Log($"texture {Bridge.ShortName(path)}: raw copy failed ({e.Message}), decoded", sw); }
        }

        await encoders.WaitAsync();
        try
        {
            var tLoad = sw.Elapsed.TotalMilliseconds;
            var ct = (cap > 0 ? TextureDecoder.Decode(tex, cap, ETexturePlatform.DesktopMobile) : tex.Decode(ETexturePlatform.DesktopMobile))
                     ?? throw new InvalidDataException("Could not decode " + path);
            var tDecode = sw.Elapsed.TotalMilliseconds;
            var (data, ext) = EncodeTexture(ct);
            var tEncode = sw.Elapsed.TotalMilliseconds;
            var file = stem + "." + ext;
            await File.WriteAllBytesAsync(file, data);
            var kind = tex switch
            {
                UTextureCube => "cube",
                UVolumeTexture => "volume",
                UTexture2DArray => "array",
                _ => "2d",
            };
            var depth = kind is "volume" or "array" && ct.Width > 0 ? Math.Max(1, ct.Height / ct.Width) : 1;
            var result = Sampling(new TextureFile
            {
                File = file, Srgb = tex.SRGB, Width = ct.Width, Height = ct.Height, Kind = kind, Depth = depth,
                Hdr = ext == "hdr",
            }, tex);
            await File.WriteAllTextAsync(meta, JsonConvert.SerializeObject(new CachedTexture { Version = TextureCacheVersion, Texture = result }));
            Timing.Log($"texture {Bridge.ShortName(path)} {ct.Width}x{ct.Height} {ct.PixelFormat}: load {tLoad:0} decode {tDecode - tLoad:0} encode {tEncode - tDecode:0} ({data.Length / 1024} KB)", sw);
            return result;
        }
        finally { encoders.Release(); }
    }

    /// <summary>
    /// Whether UE samples a texture unfiltered: its Filter set to TF_Nearest (CUE4Parse's
    /// UTexture.Filter says TF_Nearest when the property isn't stored, where UE's default is
    /// TF_Default, so only the stored property counts), or TEXTUREGROUP_Pixels2D.
    /// </summary>
    /// <summary>A record's sampler state, read from the texture each time (cached records predate some of it).</summary>
    static TextureFile Sampling(TextureFile rec, UTexture tex)
    {
        if (tex.Format != EPixelFormat.PF_Unknown)
        {
            rec.Format = tex.Format.ToString();
            // UE decodes sRGB in the sampler, and only a format with an sRGB variant has one (BC1-3, BC7,
            // 8-bit RGBA): a BC4/BC5/BC6H/G8/float texture reads as stored whatever its SRGB flag says
            rec.Srgb = tex.SRGB && SrgbFormat(tex.Format);
        }
        rec.Nearest = Nearest(tex);
        rec.AddressX = Address(tex.GetTextureAddressX());
        rec.AddressY = Address(tex.GetTextureAddressY());
        return rec;
    }

    static bool SrgbFormat(EPixelFormat f) => f is EPixelFormat.PF_DXT1 or EPixelFormat.PF_DXT3 or EPixelFormat.PF_DXT5
        or EPixelFormat.PF_BC7 or EPixelFormat.PF_B8G8R8A8 or EPixelFormat.PF_R8G8B8A8 or EPixelFormat.PF_A8R8G8B8
        || f.ToString().StartsWith("PF_ASTC", StringComparison.Ordinal) || f.ToString().StartsWith("PF_ETC2", StringComparison.Ordinal);

    static string Address(TextureAddress a) => a switch
    {
        TextureAddress.TA_Clamp => "Clamp",
        TextureAddress.TA_Mirror => "Mirror",
        _ => "Wrap",
    };

    static bool Nearest(UTexture tex) =>
        tex.Properties.FirstOrDefault(p => p.Name.Text == "Filter")?.Tag?.GenericValue?.ToString()?.EndsWith("TF_Nearest", StringComparison.Ordinal) == true
        || tex.LODGroup == global::CUE4Parse.UE4.Assets.Exports.Texture.TextureGroup.TEXTUREGROUP_Pixels2D;

    sealed class CachedTexture
    {
        public int Version { get; set; }
        public TextureFile Texture { get; set; }
    }

    /// <summary>
    /// 8-bit colour straight to PNG with Skia at a fast setting (Sub filter,
    /// zlib 1): 3-6x quicker than the library's default (all filters, zlib 6)
    /// for files about a third bigger. Anything else goes through global::CUE4Parse.
    /// </summary>
    static (byte[] Data, string Ext) EncodeTexture(CTexture ct)
    {
        var type = ct.PixelFormat switch
        {
            EPixelFormat.PF_R8G8B8A8 => SkiaSharp.SKColorType.Rgba8888,
            EPixelFormat.PF_B8G8R8A8 => SkiaSharp.SKColorType.Bgra8888,
            _ => SkiaSharp.SKColorType.Unknown,
        };
        if (type != SkiaSharp.SKColorType.Unknown && ct.Data != null && ct.Data.Length >= ct.Width * ct.Height * 4)
        {
            var info = new SkiaSharp.SKImageInfo(ct.Width, ct.Height, type, SkiaSharp.SKAlphaType.Unpremul);
            var pin = System.Runtime.InteropServices.GCHandle.Alloc(ct.Data, System.Runtime.InteropServices.GCHandleType.Pinned);
            try
            {
                using var pm = new SkiaSharp.SKPixmap(info, pin.AddrOfPinnedObject());
                using var png = pm.Encode(new SkiaSharp.SKPngEncoderOptions(SkiaSharp.SKPngEncoderFilterFlags.Sub, 1));
                if (png != null) return (png.ToArray(), "png");
            }
            finally { pin.Free(); }
        }
        var opts = new ExportOptions(texturePlatform: ETexturePlatform.DesktopMobile, textureFormat: ETextureFormat.Png,
                                     exportHdrTexturesAsHdr: true);
        var data = ct.Encode(opts, out var ext);
        return (data, ext.Trim('.').ToLowerInvariant());
    }

    // ------------------------------------------------------------ collections
    /// <summary>
    /// A material parameter collection's values: {"scalars": {..}, "vectors": {..}}. Its
    /// defaults, and over them what the season's day sequence gives it at <see cref="TimeOfDay"/>
    /// (FortniteMaterialParameters' sky and cloud colours are black placeholders the sequence drives).
    /// </summary>
    public Task<JObject> CollectionAsync(string path) => Locked(async () =>
    {
        var p = (await MainExportAsync(path))["Properties"] as JObject ?? new JObject();
        var scalars = new JObject();
        var vectors = new JObject();
        foreach (var e in p["ScalarParameters"] ?? new JArray())
            scalars[(string)e["ParameterName"]] = (double?)e["DefaultValue"] ?? 0.0;
        foreach (var e in p["VectorParameters"] ?? new JArray())
        {
            // left out when it's the struct's own default, (0,0,0,0) (FCollectionVectorParameter: ForceInitToZero)
            var v = e["DefaultValue"];
            vectors[(string)e["ParameterName"]] = new JArray((double?)v?["R"] ?? 0, (double?)v?["G"] ?? 0, (double?)v?["B"] ?? 0, (double?)v?["A"] ?? 0);
        }
        var day = await DayValuesAsync();
        var name = path.Split('/').Last().Split('.')[0];
        if (day.Collections.TryGetValue(name, out var set))
        {
            foreach (var (k, v) in set.Scalars) scalars[k] = v;
            foreach (var (k, v) in set.Vectors) vectors[k] = new JArray(v);
        }
        return new JObject { ["scalars"] = scalars, ["vectors"] = vectors };
    });

    // ------------------------------------------------------------ time of day
    /// <summary>The in-game hour (0-24) whose day sequence values materials get.</summary>
    public double TimeOfDay { get; set; } = 12;

    sealed class ParamValues
    {
        public Dictionary<string, double> Scalars { get; } = new();
        public Dictionary<string, double[]> Vectors { get; } = new();
    }

    sealed class DayValues
    {
        /// <summary>A parameter collection (by asset name) -> the values the sequence gives it.</summary>
        public Dictionary<string, ParamValues> Collections { get; } = new(StringComparer.OrdinalIgnoreCase);
        /// <summary>A sky mesh's material slot ("Skydome", "SunMoon") -> the values the sequence gives its material.</summary>
        public Dictionary<string, ParamValues> Slots { get; } = new(StringComparer.OrdinalIgnoreCase);
        public double Hour;
    }

    DayValues day;

    /// <summary>
    /// The season's day sequence (the newest DS_BR_Ch&lt;n&gt;S&lt;n&gt;) evaluated at <see cref="TimeOfDay"/>:
    /// its parameter collection track and its sky mesh's material tracks. The sequence is a
    /// day long (its playback range is 24 in-game hours); a channel's keys are cubic,
    /// linear or constant, held before the first and after the last.
    /// </summary>
    async Task<DayValues> DayValuesAsync()
    {
        if (day != null && day.Hour == TimeOfDay) return day;
        var values = new DayValues { Hour = TimeOfDay };
        var sw = System.Diagnostics.Stopwatch.StartNew();
        try
        {
            var key = game.Provider.Files.Keys
                .Select(k => (Key: k, M: System.Text.RegularExpressions.Regex.Match(System.IO.Path.GetFileName(k), @"^DS_BR_Ch(\d+)S(\d+)\.uasset$", System.Text.RegularExpressions.RegexOptions.IgnoreCase)))
                .Where(x => x.M.Success)
                .OrderByDescending(x => int.Parse(x.M.Groups[1].Value)).ThenByDescending(x => int.Parse(x.M.Groups[2].Value))
                .Select(x => x.Key).FirstOrDefault();
            if (key != null)
            {
                var pkg = await game.Provider.LoadPackageAsync(key);
                // by export index: a sequence's names repeat (each track's section is "..._0")
                var exports = pkg.GetExports().Select(e => JObject.Parse(JsonConvert.SerializeObject(e, Ser))).ToList();
                var movie = exports.FirstOrDefault(e => (string)e["Type"] == "MovieScene")?["Properties"];
                var dayTicks = (double?)movie?["PlaybackRange"]?["Value"]?["UpperBound"]?["Value"]?["Value"] ?? 19200000;
                var t = TimeOfDay / 24.0 * dayTicks;
                JObject Section(JToken r) => ((string)r?["ObjectPath"])?.Split('.').Last() is { } i && int.TryParse(i, out var n) && n >= 0 && n < exports.Count
                    ? exports[n]["Properties"] as JObject : null;
                foreach (var e in exports)
                {
                    var p = e["Properties"];
                    ParamValues target = null;
                    if ((string)e["Type"] == "MovieSceneMaterialParameterCollectionTrack" && ((string)p?["MPC"]?["ObjectName"])?.Split('\'') is { Length: > 1 } mpc)
                        target = values.Collections.TryGetValue(mpc[1], out var c) ? c : values.Collections[mpc[1]] = new ParamValues();
                    else if ((string)e["Type"] == "MovieSceneComponentMaterialTrack" && (string)p?["MaterialInfo"]?["MaterialSlotName"] is { } slot)
                        target = values.Slots.TryGetValue(slot, out var s) ? s : values.Slots[slot] = new ParamValues();
                    if (target == null) continue;
                    foreach (var r in p["Sections"] ?? new JArray())
                    {
                        if (Section(r) is not { } sec) continue;
                        foreach (var sp in (sec["ScalarParameterNamesAndCurves"] ?? sec["ScalarParameterInfosAndCurves"]) ?? new JArray())
                            if (((string)sp["ParameterName"] ?? (string)sp["ParameterInfo"]?["Name"]) is { } n && Channel(sp["ParameterCurve"], t) is { } v)
                                target.Scalars[n] = v;
                        foreach (var cp in (sec["ColorParameterNamesAndCurves"] ?? sec["ColorParameterInfosAndCurves"]) ?? new JArray())
                        {
                            if (((string)cp["ParameterName"] ?? (string)cp["ParameterInfo"]?["Name"]) is not { } n) continue;
                            var rgba = new[] { Channel(cp["RedCurve"], t), Channel(cp["GreenCurve"], t), Channel(cp["BlueCurve"], t), Channel(cp["AlphaCurve"], t) };
                            if (rgba.All(x => x == null)) continue;
                            target.Vectors[n] = rgba.Select((x, i) => x ?? (i == 3 ? 1.0 : 0.0)).ToArray();
                        }
                    }
                }
                Timing.Log($"time of day {TimeOfDay:0.#} h from {System.IO.Path.GetFileNameWithoutExtension(key)}: {values.Collections.Sum(c => c.Value.Scalars.Count + c.Value.Vectors.Count)} collection and " +
                           $"{values.Slots.Sum(c => c.Value.Scalars.Count + c.Value.Vectors.Count)} sky values", sw);
            }
        }
        catch (Exception e) { Timing.Log("time of day: the day sequence didn't read (" + e.Message + ")", sw); }
        return day = values;
    }

    /// <summary>A movie scene float channel at tick t (null if it has no keys and no default).</summary>
    static double? Channel(JToken ch, double t)
    {
        if (ch is not JObject) return null;
        var times = (ch["Times"] as JArray ?? new JArray()).Select(x => (double?)x["Value"] ?? 0).ToArray();
        var keys = ch["Values"] as JArray ?? new JArray();
        if (times.Length == 0 || keys.Count == 0)
            return (bool?)ch["bHasDefaultValue"] == true ? (double?)ch["DefaultValue"] : null;
        double V(int i) => (double?)keys[i]["Value"] ?? 0;
        if (t <= times[0]) return V(0);
        var last = Math.Min(times.Length, keys.Count) - 1;
        if (t >= times[last]) return V(last);
        var k = 0;
        while (k + 1 < last && times[k + 1] <= t) k++;
        var dt = times[k + 1] - times[k];
        var a = dt > 0 ? (t - times[k]) / dt : 0;
        switch ((int?)keys[k]["InterpMode"] ?? 2)
        {
            case 1: return V(k);                                   // constant
            case 0: return V(k) + (V(k + 1) - V(k)) * a;           // linear
            default:
            {
                // cubic: a Bezier through the keys, tangents in value per tick
                var p0 = V(k); var p3 = V(k + 1);
                var p1 = p0 + ((double?)keys[k]["Tangent"]?["LeaveTangent"] ?? 0) * dt / 3;
                var p2 = p3 - ((double?)keys[k + 1]["Tangent"]?["ArriveTangent"] ?? 0) * dt / 3;
                var b = 1 - a;
                return b * b * b * p0 + 3 * b * b * a * p1 + 3 * b * a * a * p2 + a * a * a * p3;
            }
        }
    }

    /// <summary>
    /// The material assets with these names (an FP import keeps only its materials'
    /// names): name -> their object paths. One pass over the file table; a package
    /// counts when its main export is a material or a material instance.
    /// </summary>
    public Task<JObject> FindMaterialsAsync(IEnumerable<string> names) => Locked(async () =>
    {
        var wanted = new HashSet<string>(names.Where(n => !string.IsNullOrWhiteSpace(n)), StringComparer.OrdinalIgnoreCase);
        var found = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
        foreach (var key in game.Provider.Files.Keys)
        {
            if (!key.EndsWith(".uasset", StringComparison.OrdinalIgnoreCase) || key.EndsWith(".o.uasset", StringComparison.OrdinalIgnoreCase)) continue;
            var name = System.IO.Path.GetFileNameWithoutExtension(key);
            if (!wanted.Contains(name)) continue;
            if (!found.TryGetValue(name, out var l)) found[name] = l = new List<string>();
            if (!l.Contains(key)) l.Add(key);
        }
        var result = new JObject();
        foreach (var (name, keys) in found)
        {
            var paths = new JArray();
            foreach (var key in keys)
            {
                try
                {
                    var pkg = await game.Provider.LoadPackageAsync(key);
                    var main = pkg.GetExports().FirstOrDefault(e => e.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
                    if (main is global::CUE4Parse.UE4.Assets.Exports.Material.UMaterialInterface)
                        paths.Add(pkg.Name + "." + main.Name);
                }
                catch { /* a package that won't load isn't offered */ }
            }
            if (paths.Count > 0) result[name] = paths;
        }
        return result;
    });

    /// <summary>A package's main export as JSON (the details view shows it raw).</summary>
    public Task<JObject> RawAsync(string path) => Locked(() => MainExportAsync(path));
}
