# Generated by materialporter/tools/sync_fork.py from blender/material_porter/build.py - edit it there.
"""Materials from the app's bundles: translated, assembled into a Principled
BSDF the way UE's blend mode and shading model ask, laid out, and put where
the bundle says (the selected objects, or in place of an FP material).

A material holds one group node - its graph, a node group ("root") - into
the Material Output; the parameters are that node's inputs, with the
instance's values in them (env.MaterialEnv)."""
import hashlib
import json

import bpy

from . import layout
from .app_client import AppClient
from . import world
from .env import MaterialEnv, fit_socket
from .ue_graph import BOUNDS_CENTRE, CARRIED, SHADING_MODELS, Translator, Val

PREFIX = "MP "            # built materials: "MP MI_Foo"
KEY_PATH = "mp_path"      # the game object a built material translates
KEY_REV = "mp_rev"        # the build revision that made it (older ones are rebuilt, not reused)
BUILD_REVISION = 32       # 32: emissive clamped at 0 as UE; 31: DepthFade by max(FadeDistance, 0.0001) as UE; 30: a baked tangent where Blender gives none; 29: particle camera from the scene under Cycles; 28: effects' soft fade off under Cycles; 2: UE 5 translucent blend modes (glass); 3: custom primitive data; 5: landscape layers; 7: per-instance custom data; 9: images channel-packed (alpha as data); 10: Time runs from 100 s (hit flashes over), unfiltered textures sampled Closest; 11: LocalPosition and PreSkinnedPosition from the rest position (skinned meshes); 12: an additive material's light is Emissive * Opacity; 13: a particle's values from its instance (a replayed effect), a sprite's sub-image; 14: SphereMask and Distance between a float2 and a scalar (Z stays 0); 15: a particle's sprite rotation and direction, the 2D light march of raymarched smoke; 16: the ambient cubemap tint is white; 17: a particle material's World Position Offset (displacement), UE's division by zero; 18: a smoothstep over an empty range is a hard edge, Particle Random from the particle; 19: a Niagara decal's colour and fade (DecalColor, DecalLifetimeOpacity); 20: division by zero per component (a vector divisor); 21: view space is the shader camera space as is (Z forward), Object Position the bounds' centre; 22: Power clamps a negative base to 0 (PositiveClampedPow); 23: vector parameters that aren't colours on vector sockets (a colour socket clamps negatives); 24: BLEND_ColoredTransmittanceOnly is Modulate; 25: DepthFade and SceneDepth by a raycast behind a see-through pixel (Blender's Raycast node); 26: translucency lit from UE's volume: diffuse only, the Normal unused unless per-pixel directional; 27: the sun, the sky and collection values through the file's world groups (a time of day drives them), its height fog
                          # 4: instance overrides to the default (Opaque, DefaultLit, one-sided) honoured
                          # 6: vector parameters without a stored default are (0, 0, 0, 0), not alpha 1
                          # 8: single layer water (the medium, refraction, water info stand-ins); graph clip()s
KEY_REPLACES = "mp_replaces"
KEY_REPLACED_BY = "mp_replaced_by"
KEY_FP = "mp_fp"          # a function group's fingerprint, to share it
KEY_VARIANT = "mp_variant"  # a style's parameter values over the instance (their hash)
KEY_SHAPE = "mp_shape"    # what decides a build's trees beyond parameter values (build_like reuses it)
KEY_LAYOUT = "mp_layout_pending"  # a tree built without its layout: arranged when a node editor first shows it

# Map imports build hundreds of materials nobody opens: laying their trees out
# (cosmetic, and two thirds of a build) waits until a node editor shows one.
LAZY_LAYOUT = False
KEY_WATER = "mp_water"    # a water material (MSM_SingleLayerWater): its objects get the depth under them


def _enum(v, default):
    return str(v if v is not None else default).split("::")[-1]


def settings(entry):
    """Blend mode, shading model and the rest: the instance's overrides,
    else the master's asset, else UE's defaults."""
    asset, over = entry.get("asset") or {}, entry.get("overrides") or {}
    pick = lambda k, d: over.get(k, asset.get(k, d))
    return {
        "blend": _enum(pick("BlendMode", None), "BLEND_Opaque"),
        "shading": _enum(pick("ShadingModel", None), "MSM_DefaultLit"),
        "two_sided": bool(pick("TwoSided", False)),
        "clip": float(pick("OpacityMaskClipValue", 0.3333)),
        "tangent_normal": bool(asset.get("bTangentSpaceNormal", True)),
        # how a lit translucent material is lit (None from an app that doesn't say: as a surface)
        "lighting": _enum(asset["TranslucencyLightingMode"], "") if "TranslucencyLightingMode" in asset else None,
        # the Subsurface Profile skin scatters by: {"radius": [r, g, b], "scale": metres}
        "profile": entry.get("subsurface"),
    }


# ------------------------------------------------------------------ assembly
def assemble(tr, mat, a, s):
    """The attributes onto a Principled BSDF, UE -> Blender, into the tree's
    output: the Material Output, or a node group's "Surface" output."""
    moved = False       # whether its World Position Offset moves its vertices
    with tr.at("Output"):
        bsdf = tr.node("ShaderNodeBsdfPrincipled", "UE surface")
        if tr.tree == mat.node_tree:
            out = tr.node("ShaderNodeOutputMaterial", "output")
        else:
            tr.tree.interface.new_socket("Surface", in_out='OUTPUT', socket_type='NodeSocketShader')
            out = tr.node("NodeGroupOutput", "output")
        link = lambda v, name: tr.link(v, bsdf.inputs[name]) if v is not None else None
        shading = s["shading"]
        per_pixel = None
        if shading == "MSM_FromMaterialExpression":
            sm = a.get("ShadingModel")
            if sm is not None and not sm.const:
                # the graph picks the model per pixel (skin here, lit there): masks below
                per_pixel = sm
            shading = SHADING_MODELS[int(sm.s)] if sm is not None and sm.const and 0 <= int(sm.s) < len(SHADING_MODELS) \
                else "MSM_DefaultLit"
        # the water medium comes with the graph's SingleLayerWaterMaterialOutput
        water = shading == "MSM_SingleLayerWater" and "WaterAbsorption" in a

        # a translucent material UE lights from its translucency volume gets diffuse light only (no
        # specular; Metallic only darkens), and lit per vertex or without a direction its Normal goes
        # unused (smoke sprites' sphere normals would shade each puff as a ball)
        volumetric = s["blend"] in TRANSLUCENT and s.get("lighting") in VOLUMETRIC_LIGHTING
        flat = volumetric and s["lighting"] in NORMAL_UNUSED
        if not water:
            # (water: BaseColor and Metallic are its surface layer's, below)
            if volumetric:
                base, metal = a["BaseColor"], a["Metallic"]
                if base is not None and metal is not None and not (metal.const and _comps(metal.s)[0] == 0.0):
                    base = tr.vmath('SCALE', tr.as3(base), tr.math('SUBTRACT', tr.const(1.0), metal), out_w=3)
                link(base, "Base Color")
            else:
                link(a["BaseColor"], "Base Color")
                link(a["Metallic"], "Metallic")
        link(a["Roughness"], "Roughness")
        if volumetric:
            bsdf.inputs["Specular IOR Level"].default_value = 0.0
        elif not water:
            # UE's Specular 0.5 is F0 0.04, as is Blender's Specular IOR Level 0.5 (IOR 1.5)
            link(a["Specular"], "Specular IOR Level")
        emissive = a["EmissiveColor"]
        if not (emissive.const and not any(_comps(emissive.s)[:3])):
            link(emissive, "Emission Color")
            bsdf.inputs["Emission Strength"].default_value = 1.0

        n = a["Normal"]
        bsdf_n = None
        if not flat and not (n.const and _comps(n.s)[:3] == (0.0, 0.0, 1.0)):
            if s["tangent_normal"]:
                # UE's tangent space is DirectX (green down): flip Y, then
                # encode as the colour Blender's Normal Map node reads
                nm = tr.node("ShaderNodeNormalMap", "UE normal", space='TANGENT', uv_map="UV0")
                col = tr.vmath('ADD', tr.vmath('MULTIPLY', n, tr.const((0.5, -0.5, 0.5), 3), out_w=3),
                               tr.const((0.5, 0.5, 0.5), 3), out_w=3)
                tr.link(col, nm.inputs["Color"])
                bsdf_n = Val(nm.outputs["Normal"], 3)
            else:
                # a world-space normal, in UE space: back to Blender's
                bsdf_n = tr.vmath('NORMALIZE', tr.vmath('MULTIPLY', n, tr.const((1.0, -1.0, 1.0), 3), out_w=3), out_w=3)
            tr.link(bsdf_n, bsdf.inputs["Normal"])

        if per_pixel is not None:
            _per_pixel_models(tr, bsdf, a, per_pixel, s["profile"])
        elif shading in ("MSM_Subsurface", "MSM_TwoSidedFoliage"):
            # UE's subsurface models read Opacity as the scattering amount, SubsurfaceColor as its colour
            link(a["Opacity"], "Subsurface Weight")
            link(a["SubsurfaceColor"], "Subsurface Radius")
        elif shading in ("MSM_SubsurfaceProfile", "MSM_PreintegratedSkin"):
            # skin: the scattering comes from the Subsurface Profile, not SubsurfaceColor
            link(a["Opacity"], "Subsurface Weight")
            _profile(bsdf, s["profile"])
        elif shading == "MSM_ClearCoat":
            link(a["ClearCoat"], "Coat Weight")
            link(a["ClearCoatRoughness"], "Coat Roughness")
        elif shading == "MSM_Cloth":
            # Cloth: CustomData0 is the fuzz amount, SubsurfaceColor the fuzz colour
            link(a["ClearCoat"], "Sheen Weight")
            link(a["SubsurfaceColor"], "Sheen Tint")

        surface = Val(bsdf.outputs[0], 3)
        if water:
            surface = _water(tr, mat, a, bsdf, bsdf_n, out)
        if shading == "MSM_Unlit":
            em = tr.node("ShaderNodeEmission", "unlit")
            tr.link(emissive, em.inputs["Color"])
            surface = Val(em.outputs[0], 3)

        blend = s["blend"]
        if blend == "BLEND_Masked":
            m = a["OpacityMask"]
            cut = m if m.const else tr.math('GREATER_THAN', m, tr.const(s["clip"] - 1e-4), label="opacity mask clip")
            if cut.const:
                cut = tr.const(1.0 if cut.s > s["clip"] else 0.0)
            for keep in tr.clips:
                # the graph's own clip()s: not drawn where one is 0
                cut = tr.binop('MULTIPLY', cut, keep, label="clip()")
            if not (cut.const and cut.s == 1.0):
                if shading == "MSM_Unlit" or water:
                    surface = _with_alpha(tr, surface, cut)
                else:
                    link(cut, "Alpha")
        elif blend in TRANSLUCENT:
            mat.surface_render_method = 'BLENDED'
            _see_through_shadows(mat)
            if shading == "MSM_Unlit":
                surface = _with_alpha(tr, surface, a["Opacity"])
            else:
                link(a["Opacity"], "Alpha")
        elif blend in MODULATE:
            # the scene behind, multiplied by the emissive colour
            mat.surface_render_method = 'BLENDED'
            _see_through_shadows(mat)
            tp = tr.node("ShaderNodeBsdfTransparent", "modulate")
            tr.link(emissive, tp.inputs["Color"])
            surface = Val(tp.outputs[0], 3)
        elif blend == "BLEND_Additive":
            mat.surface_render_method = 'BLENDED'
            _see_through_shadows(mat)
            add = tr.node("ShaderNodeAddShader", "additive")
            tp = tr.node("ShaderNodeBsdfTransparent", "see-through")
            em = tr.node("ShaderNodeEmission", "additive light")
            # UE adds Emissive * Opacity to the scene (a flash's shape is its opacity)
            light, opacity = emissive, a["Opacity"]
            if not (opacity.const and _comps(opacity.s)[0] == 1.0):
                light = tr.binop('MULTIPLY', emissive, opacity, label="additive opacity")
            tr.link(light, em.inputs["Color"])
            tr.L.new(tp.outputs[0], add.inputs[0])
            tr.L.new(em.outputs[0], add.inputs[1])
            surface = Val(add.outputs[0], 3)
        tr.L.new(surface.s, out.inputs["Surface"])
        offset = a.get("WorldPositionOffset")
        if offset is not None and not (offset.const and not any(_comps(offset.s)[:3])) and tr.tree != mat.node_tree:
            # UE's World Position Offset (cm, UE's axes) moves each vertex: Eevee's displacement
            # does as much (no bump: the offset isn't a height)
            with tr.at("World Position Offset"):
                metres = tr.vmath('MULTIPLY', tr.as3(offset), tr.const((0.01, -0.01, 0.01), 3), out_w=3)
                move = tr.node("ShaderNodeVectorDisplacement", "world position offset", space='WORLD')
                tr.link(metres, move.inputs["Vector"])
                move.inputs["Midlevel"].default_value = 0.0
                move.inputs["Scale"].default_value = 1.0
            tr.tree.interface.new_socket("Displacement", in_out='OUTPUT', socket_type='NodeSocketVector')
            tr.L.new(move.outputs[0], out.inputs["Displacement"])
            mat.displacement_method = 'DISPLACEMENT'
            if hasattr(mat, "max_vertex_displacement"):
                mat.max_vertex_displacement = 50.0
            moved = True
    # (a strip its material thickens towards the camera has no side of its own, and the mirrored
    # import turns the one it is given away: both sides drawn)
    mat.use_backface_culling = not s["two_sided"] and not moved


# UE 5 names plain translucency BLEND_TranslucentGreyTransmittance (Substrate
# adds the coloured one); all of them blend by Opacity
TRANSLUCENT = ("BLEND_Translucent", "BLEND_TranslucentGreyTransmittance", "BLEND_TranslucentColoredTransmittance",
               "BLEND_AlphaComposite", "BLEND_AlphaHoldout")
# and Modulate BLEND_ColoredTransmittanceOnly (the same value: Tempest's eye glow multiplies its helmet)
MODULATE = ("BLEND_Modulate", "BLEND_ColoredTransmittanceOnly")
# translucency lighting from the translucency volume (UE's default the first): diffuse only; all but
# the per-pixel directional one leave the Normal unused
VOLUMETRIC_LIGHTING = ("TLM_VolumetricNonDirectional", "TLM_VolumetricPerVertexNonDirectional",
                       "TLM_VolumetricPerVertexDirectional", "TLM_VolumetricDirectional")
NORMAL_UNUSED = VOLUMETRIC_LIGHTING[:3]


def _see_through_shadows(mat):
    """A blended material's shadow follows its alpha, not its whole surface."""
    for prop in ("use_transparent_shadow", "use_transparency_overlap"):
        if hasattr(mat, prop):
            setattr(mat, prop, True)


SKIN_RADIUS = (1.0, 0.2, 0.1)


def _profile(bsdf, profile):
    """A Subsurface Profile's radius and scale on the BSDF (none: Blender's skin)."""
    radius = tuple(profile["radius"]) if profile else SKIN_RADIUS
    bsdf.inputs["Subsurface Radius"].default_value = radius
    if profile:
        bsdf.inputs["Subsurface Scale"].default_value = float(profile["scale"])
    return radius


def _per_pixel_models(tr, bsdf, a, sm, profile=None):
    """A shading model the graph picks per pixel: each model's lobe, weighted
    by a mask of where it's picked (subsurface, clear coat, cloth)."""
    def mask(*models):
        m = None
        for name in models:
            eq = tr.math('COMPARE', sm, tr.const(float(SHADING_MODELS.index(name))), tr.const(0.5),
                         label="shading model is " + name[4:])
            m = eq if m is None else tr.math('ADD', m, eq)
        return m

    def link(v, name):
        if v is not None:
            tr.link(v, bsdf.inputs[name])

    sss = mask("MSM_Subsurface", "MSM_TwoSidedFoliage", "MSM_SubsurfaceProfile", "MSM_PreintegratedSkin")
    link(tr.math('MULTIPLY', sss, a["Opacity"], label="subsurface amount"), "Subsurface Weight")
    # SubsurfaceColor for Subsurface / foliage; skin's profile radius elsewhere (its scale for all)
    skin = mask("MSM_SubsurfaceProfile", "MSM_PreintegratedSkin")
    radius = _profile(bsdf, profile)
    link(tr.lerp(a["SubsurfaceColor"], tr.const(radius, 3), skin, label="subsurface radius"), "Subsurface Radius")
    coat = mask("MSM_ClearCoat")
    link(tr.math('MULTIPLY', coat, a["ClearCoat"], label="clear coat amount"), "Coat Weight")
    link(a["ClearCoatRoughness"], "Coat Roughness")
    cloth = mask("MSM_Cloth")
    # Cloth: CustomData0 is the fuzz amount, SubsurfaceColor the fuzz colour
    link(tr.math('MULTIPLY', cloth, a["ClearCoat"], label="cloth fuzz amount"), "Sheen Weight")
    link(a["SubsurfaceColor"], "Sheen Tint")


IOR_WATER = 1.333
# a dielectric's reflectance at normal incidence from its IOR, as Blender's
# Principled BSDF makes it: ((n - 1) / (n + 1))^2
F0_WATER = ((IOR_WATER - 1.0) / (IOR_WATER + 1.0)) ** 2


def _water(tr, mat, a, bsdf, normal, out):
    """UE's single layer water (MSM_SingleLayerWater) in Eevee.

    UE lights the water surface itself (specular from Specular and
    Roughness, and a surface layer of BaseColor where Opacity > 0), then
    adds the water the view ray crosses to the scene behind it, per colour
    channel (coefficients per cm, path in cm):
        T = exp(-(Scattering + Absorption) * path)
        the scene behind * T * ColorScaleBehindWater
        + (1 - F) * Scattering (1 - T) / (Scattering + Absorption) * (sun * phase + ambient / 4 pi)
    Here the surface is a Principled BSDF refracting at water's IOR (Eevee's
    raytraced transmission shows the ground through it) with its
    transmission tinted T * ColorScaleBehindWater; the in-scattered light is
    a diffuse lobe lit by the scene, its albedo the scattered amount / 4
    (the isotropic phase 1 / 4 pi against a diffuse lobe's 1 / pi) * (1 - F).
    The path is the translator's (the env's depth over the view's
    steepness). Like UE's water meshes it casts no shadow (the ground under
    it stays lit). Returns the surface shader."""
    path = tr.water_path()
    zero3, one3 = tr.const((0.0, 0.0, 0.0), 3), tr.const((1.0, 1.0, 1.0), 3)
    # UE: max(0, coefficients)
    sc = tr.vmath('MAXIMUM', tr.as3(a["WaterScattering"]), zero3, label="scattering (per cm)", out_w=3)
    ab = tr.vmath('MAXIMUM', tr.as3(a["WaterAbsorption"]), zero3, label="absorption (per cm)", out_w=3)
    ext = tr.vmath('ADD', sc, ab, label="extinction", out_w=3)
    depth = tr.vmath('SCALE', ext, path, label="optical depth", out_w=3)
    trans = tr.combine([tr.math('EXPONENT', tr.binop('MULTIPLY', c, tr.const(-1.0))) for c in tr.comps(depth)])
    scattered = tr.vmath('DIVIDE', tr.vmath('MULTIPLY', sc, tr.vmath('SUBTRACT', one3, trans, out_w=3), out_w=3),
                         tr.vmath('MAXIMUM', ext, tr.const((1e-5,) * 3, 3), out_w=3), label="scattered amount", out_w=3)
    tint = trans
    cs = a["WaterColorScaleBehindWater"]
    if not (cs.const and _comps(cs.s)[:3] == (1.0, 1.0, 1.0)):
        tint = tr.vmath('MULTIPLY', trans, tr.vmath('MAXIMUM', tr.as3(cs), zero3, out_w=3), label="colour behind water",
                        out_w=3)
    # the surface: reflects, refracts the ground through the water's tint
    tr.link(tint, bsdf.inputs["Base Color"])
    bsdf.inputs["Transmission Weight"].default_value = 1.0
    bsdf.inputs["IOR"].default_value = IOR_WATER
    bsdf.label = "UE water surface"
    # UE's F0 is 0.08 * Specular; Blender's is F0(IOR) * 2 * Specular IOR Level
    tr.link(tr.binop('MULTIPLY', a["Specular"], tr.const(0.08 / (2.0 * F0_WATER)), label="specular level"),
            bsdf.inputs["Specular IOR Level"])
    # the water under the surface, lit
    fres = tr.node("ShaderNodeFresnel", "water fresnel")
    fres.inputs["IOR"].default_value = IOR_WATER
    if normal is not None:
        tr.link(normal, fres.inputs["Normal"])
    albedo = tr.vmath('SCALE', scattered, tr.binop('MULTIPLY', tr.binop('SUBTRACT', tr.const(1.0), Val(fres.outputs[0], 1)),
                                                   tr.const(0.25)), label="in-scattered albedo", out_w=3)
    medium = tr.node("ShaderNodeBsdfDiffuse", "water medium (in-scattered light)")
    tr.link(albedo, medium.inputs["Color"])
    add = tr.node("ShaderNodeAddShader", "water")
    tr.L.new(bsdf.outputs[0], add.inputs[0])
    tr.L.new(medium.outputs[0], add.inputs[1])
    surface = Val(add.outputs[0], 3)
    # Opacity: the surface layer (foam, debris) over the water
    op = a["Opacity"]
    if not (op.const and op.s <= 0.0):
        layer = tr.node("ShaderNodeBsdfPrincipled", "UE water surface layer")
        for name, pin in (("Base Color", "BaseColor"), ("Metallic", "Metallic"), ("Roughness", "Roughness"),
                          ("Specular IOR Level", "Specular")):
            tr.link(a[pin], layer.inputs[name])
        if normal is not None:
            tr.link(normal, layer.inputs["Normal"])
        mix = tr.node("ShaderNodeMixShader", "surface opacity")
        tr.link(tr.saturate(op), mix.inputs[0])
        tr.L.new(add.outputs[0], mix.inputs[1])
        tr.L.new(layer.outputs[0], mix.inputs[2])
        surface = Val(mix.outputs[0], 3)
    # UE's water meshes cast no shadow: the ground under the water stays sunlit
    path_node = tr.node("ShaderNodeLightPath", "light path")
    no_shadow = tr.node("ShaderNodeMixShader", "casts no shadow")
    see = tr.node("ShaderNodeBsdfTransparent", "see-through")
    tr.L.new(path_node.outputs["Is Shadow Ray"], no_shadow.inputs[0])
    tr.L.new(surface.s, no_shadow.inputs[1])
    tr.L.new(see.outputs[0], no_shadow.inputs[2])
    surface = Val(no_shadow.outputs[0], 3)
    _see_through_shadows(mat)
    # one refracting interface (the thickness 0), traced through the scene
    zero = tr.node("ShaderNodeValue", "thickness: one interface")
    zero.outputs[0].default_value = 0.0
    if tr.tree == mat.node_tree:
        tr.L.new(zero.outputs[0], out.inputs["Thickness"])
    else:
        tr.tree.interface.new_socket("Thickness", in_out='OUTPUT', socket_type='NodeSocketFloat')
        tr.L.new(zero.outputs[0], out.inputs["Thickness"])
    mat.surface_render_method = 'DITHERED'
    if hasattr(mat, "use_raytrace_refraction"):
        mat.use_raytrace_refraction = True
    mat[KEY_WATER] = 1
    return surface


def _with_alpha(tr, surface, alpha):
    mix = tr.node("ShaderNodeMixShader", "alpha")
    tp = tr.node("ShaderNodeBsdfTransparent", "see-through")
    tr.link(alpha, mix.inputs[0])
    tr.L.new(tp.outputs[0], mix.inputs[1])
    tr.L.new(surface.s, mix.inputs[2])
    return Val(mix.outputs[0], 3)


def _material_node(mat, root, label, values, width):
    """The material's tree: its group node, the parameters' values in its
    sockets, into the Material Output."""
    tree = mat.node_tree
    node = tree.nodes.new("ShaderNodeGroup")
    node.node_tree = root
    node.label = label
    node.width = width
    by_id = {s.identifier: s for s in node.inputs}
    for ident, value in values:
        sock = by_id.get(ident)
        if sock is not None:
            sock.default_value = fit_socket(sock, value) if isinstance(value, (tuple, list)) else value
    out = tree.nodes.new("ShaderNodeOutputMaterial")
    tree.links.new(node.outputs["Surface"], out.inputs["Surface"])
    if "Thickness" in node.outputs:
        tree.links.new(node.outputs["Thickness"], out.inputs["Thickness"])
    if "Displacement" in node.outputs:
        tree.links.new(node.outputs["Displacement"], out.inputs["Displacement"])
    node.location = (-width - 60.0, 0.0)
    out.location = (0.0, 0.0)
    tree.nodes.active = node


def _comps(s):
    """A constant's components (a scalar broadcasts, as UE casts it)."""
    return tuple(s) if isinstance(s, (tuple, list)) else (s, s, s)


# ------------------------------------------------------------------ sharing
def _fingerprint(tree, memo):
    """What a group computes (nodes, settings, values, wiring, images) - not
    where its nodes sit - so two builds of one function compare equal."""
    if tree.name in memo:
        return memo[tree.name]
    h = hashlib.sha1()
    skip = {"location", "width", "height", "dimensions", "select", "name", "label", "parent", "color",
            "use_custom_color", "show_options", "show_preview", "hide", "mute", "bl_idname", "location_absolute"}
    for n in sorted(tree.nodes, key=lambda n: n.name):
        if n.bl_idname in ("NodeFrame", "NodeReroute"):
            continue
        h.update(n.bl_idname.encode())
        for p in n.bl_rna.properties:
            if p.identifier in skip or p.is_readonly and p.identifier not in ("node_tree", "image"):
                continue
            v = getattr(n, p.identifier, None)
            if p.identifier == "node_tree" and v is not None:
                v = v.get(KEY_FP) or _fingerprint(v, memo)
            elif p.identifier == "image" and v is not None:
                v = v.filepath or v.name
            elif not isinstance(v, (int, float, str, bool)):
                continue
            h.update(("%s=%r;" % (p.identifier, v)).encode())
        for s in n.inputs:
            if not s.is_linked and hasattr(s, "default_value"):
                v = s.default_value
                h.update(repr(tuple(round(x, 6) for x in v) if hasattr(v, "__len__") else round(v, 6)).encode())
    wires = sorted("%s.%s>%s.%s" % (l.from_node.name, l.from_socket.identifier, l.to_node.name, l.to_socket.identifier)
                   for l in tree.links if l.from_node.bl_idname not in ("NodeReroute",) and l.to_node.bl_idname != "NodeReroute")
    h.update("|".join(wires).encode())
    for it in tree.interface.items_tree:
        if it.item_type == 'SOCKET':
            h.update(("%s:%s:%s" % (it.in_out, it.name, it.socket_type)).encode())
    memo[tree.name] = h.hexdigest()
    return memo[tree.name]


# fingerprint -> group, kept between builds: reading every group's fingerprint
# for each material grew with the scene (a map's hundreds of materials)
_KNOWN = None


def begin_session():
    """A new job: the known groups are read again from the file (groups may
    have come or gone since the last one), images checked against their files again."""
    global _KNOWN
    _KNOWN = None
    from . import env
    env._LOADED.clear()


def _known():
    global _KNOWN
    if _KNOWN is None:
        _KNOWN = {g[KEY_FP]: g for g in bpy.data.node_groups if KEY_FP in g}
    return _KNOWN


def _alive(g, fp):
    try:
        return g.get(KEY_FP) == fp
    except ReferenceError:
        return False


def share_groups(trees, owners=()):
    """Groups identical to one an earlier build made are replaced by it (in
    these trees and the owners', the only places a new group is used).
    Returns (how many were replaced, the ones kept)."""
    memo = {}
    known = _known()
    # innermost first: an outer group's fingerprint names its inner groups'
    order, seen = [], set()

    def visit(t):
        if t.name in seen:
            return
        seen.add(t.name)
        for n in t.nodes:
            if n.bl_idname == "ShaderNodeGroup" and n.node_tree is not None and n.node_tree in trees:
                visit(n.node_tree)
        order.append(t)
    for t in trees:
        visit(t)
    # the group nodes that may point at a new group; repointing them is what
    # user_remap did, without its walk over every datablock of the file
    users = [n for tr in list(trees) + list(owners) for n in tr.nodes
             if n.bl_idname == "ShaderNodeGroup" and n.node_tree is not None]
    shared, kept, gone = 0, [], []
    for t in order:
        fp = _fingerprint(t, memo)
        twin = known.get(fp)
        if twin is not None and not _alive(twin, fp):
            del known[fp]
            twin = None
        if twin is not None and twin != t:
            for n in users:
                if n.node_tree == t:
                    n.node_tree = twin
            gone.append(t)
            shared += 1
        else:
            t[KEY_FP] = fp
            known[fp] = t
            kept.append(t)
    if gone:
        bpy.data.batch_remove(gone)
    return shared, kept


# ------------------------------------------------------------------ layout when seen
def arrange_pending(tree):
    """Lay out a tree built with LAZY_LAYOUT (once; a failure only leaves it unarranged)."""
    if tree is None or KEY_LAYOUT not in tree:
        return False
    del tree[KEY_LAYOUT]
    try:
        layout.arrange(tree)
    except Exception as e:      # cosmetic
        print("[material_porter] layout of %s: %s" % (tree.name, e))
    return True


def _layout_in_view():
    """Timer: the trees node editors show (a material, the group entered) laid out if pending."""
    try:
        for win in bpy.context.window_manager.windows:
            for area in win.screen.areas:
                if area.type != 'NODE_EDITOR':
                    continue
                space = area.spaces.active
                done = False
                for tree in (getattr(space, "edit_tree", None), getattr(space, "node_tree", None)):
                    done |= arrange_pending(tree)
                if done:
                    area.tag_redraw()
    except Exception:
        pass        # no window (background), a closing file
    return 0.5


def ensure_layout_timer():
    if not bpy.app.timers.is_registered(_layout_in_view):
        bpy.app.timers.register(_layout_in_view, first_interval=0.5, persistent=True)


# ------------------------------------------------------------------ one material
def mark_bounds(objects):
    """UE's Object Position is an object's bounds centre: each mesh object carries its own (local,
    Blender metres), which its materials read (the materials stay shared between objects)."""
    for o in objects:
        if o is not None and o.type == 'MESH':
            o[BOUNDS_CENTRE] = [sum(c[i] for c in o.bound_box) / 8.0 for i in range(3)]


def build_one(entry, app, objects=(), make_env=None):
    """A Blender material for one bundle entry. Returns (material, notes). make_env(app, entry,
    objects): an env of the caller's own (a time of day's, whose values follow its hour)."""
    mark_bounds(objects)
    if not entry.get("graph"):
        # a master cooked without its graph (a UEFN island's own): an approximation
        from .fallback import build_fallback
        return build_fallback(entry, app, objects, MaterialEnv, settings,
                              (PREFIX, KEY_PATH, KEY_REV, BUILD_REVISION, KEY_VARIANT))
    mat = bpy.data.materials.new(PREFIX + entry["name"])
    tree = mat.node_tree
    tree.nodes.clear()
    root = bpy.data.node_groups.new(mat.name, "ShaderNodeTree")
    env = make_env(app, entry, objects) if make_env else MaterialEnv(app, entry, objects)
    env.root = root
    tr = Translator(root, env)
    env.h[0] = tr
    # a particle's material also moves its vertices (World Position Offset: a zero-width lightning
    # strip thickened towards the camera, a mesh bent along a spline)
    names = CARRIED + ("WorldPositionOffset",) if entry.get("particle") else CARRIED
    vals = tr.material_attributes(app.local(entry["graph"]), names)
    # UE clamps a material's emissive at 0 unless it allows a negative one (bAllowNegativeEmissiveColor):
    # a negative glow (a weapon's time-of-day emissive, -5 by day: the Bonerattler SMG) took its colour
    # away here, turning green magenta
    emissive = vals.get("EmissiveColor")
    if emissive is not None and not (entry.get("asset") or {}).get("bAllowNegativeEmissiveColor")             and not (emissive.const and min(_comps(emissive.s)[:3]) >= 0.0):
        vals["EmissiveColor"] = tr.vmath('MAXIMUM', tr.as3(emissive), tr.const((0.0, 0.0, 0.0), 3), out_w=3)
    assemble(tr, mat, vals, settings(entry))
    values = env.finish_parameters()
    groups = [ft.tree for ft in tr.functions.values()]
    # twins of earlier materials' groups go first: laying out a group that's
    # about to be thrown away was half of all layout time
    shared, kept = share_groups(groups, owners=[root])
    if LAZY_LAYOUT:
        for t in kept + [root]:
            t[KEY_LAYOUT] = 1
        ensure_layout_timer()
    else:
        for t in kept + [root]:
            try:
                layout.arrange(t)
            except Exception as e:     # layout is cosmetic: never lose a build to it
                env.note("layout of %s: %s" % (t.name, e))
    _material_node(mat, root, entry["name"], values, env.node_width())
    mat[KEY_PATH] = entry["path"]
    mat[KEY_REV] = BUILD_REVISION
    if entry.get("variant"):
        mat[KEY_VARIANT] = entry["variant"]
    if env.reusable:
        _record_shape(mat, root, env, entry)
    notes = list(env.notes) + sorted(set(w for w in tr.warnings + [w for ft in tr.functions.values()
                                                                    for w in ft.tr.warnings]))
    if shared:
        notes.append("%d function groups shared with earlier materials" % shared)
    # a time of day's height fog, where the file has one
    world.apply_fog(mat)
    return mat, notes


# ------------------------------------------------------------------ same shape, other values
def shape_key(entry):
    """What decides a build's node trees beyond its parameter values: its
    master's graph, static switches and masks, blend/shading overrides and
    subsurface profile. Instances alike in all of it differ only in their
    parameters' values (the material's group-node inputs) and their
    textures' images."""
    k = {g: entry.get(g) for g in ("graph", "master", "switches", "masks", "overrides", "asset", "subsurface", "sprite", "ribbon", "particle")}
    return hashlib.sha1(json.dumps(k, sort_keys=True, default=str).encode()).hexdigest()[:16]


def _reachable(root):
    out, todo = [], [root]
    while todo:
        t = todo.pop()
        if t in out:
            continue
        out.append(t)
        todo += [n.node_tree for n in t.nodes if n.bl_idname == "ShaderNodeGroup" and n.node_tree is not None]
    return out


def _record_shape(mat, root, env, entry):
    """Marks a build another instance of its shape can copy: each image node
    with the texture parameters it came from, each input with its parameter
    and graph default."""
    key_of = {img.name: key for key, img in env._images.items() if img is not None}
    for t in _reachable(root):
        for n in t.nodes:
            if n.bl_idname != "ShaderNodeTexImage" or n.image is None:
                continue
            key = key_of.get(n.image.name)
            if key in env.tex_params:
                # the parameter the translator says it samples; else every one that gave this texture
                exact = n.get("mp_tex_param")
                n["mp_tex"] = [exact] if exact else sorted(env.tex_params[key])
                n["mp_key"] = key
                n["mp_normal"] = key in env.tex_normal
    params = []
    for key, (item, _v, _value, _panel) in env._params.items():
        kind, name = key[0], key[3:]
        default = env.graph_defaults.get(("V: " if kind == "A" else key[:3]) + name)
        params.append([item.identifier, kind, name, list(default) if isinstance(default, tuple) else default])
    root["mp_params"] = json.dumps(params)
    mat["mp_tex_defaults"] = json.dumps(env.tex_default)
    mat[KEY_SHAPE] = shape_key(entry)


def _root_of(mat):
    return next((n.node_tree for n in mat.node_tree.nodes
                 if n.bl_idname == "ShaderNodeGroup" and n.node_tree is not None and "mp_params" in n.node_tree), None)


def find_shape(shape):
    """A material this file already built for that shape, current and copyable."""
    return next((m for m in bpy.data.materials if m.get(KEY_SHAPE) == shape and m.get(KEY_REV, 1) >= BUILD_REVISION
                 and _root_of(m) is not None), None)


def build_like(src, entry, app):
    """Another instance of src's shape without translating it: src's trees
    copied where its images differ (the images swapped), shared where they
    don't; the parameters' values on its own group node. None when a node's
    parameters now point at different textures (can't tell which it is)."""
    root1 = _root_of(src)
    if root1 is None:
        return None
    textures = entry.get("textures") or {}
    try:
        defaults = json.loads(src.get("mp_tex_defaults", "{}"))
        params = json.loads(root1["mp_params"])
    except (ValueError, KeyError):
        return None
    # a colour socket would clamp a negative value of this instance's: it is built anew
    colour = {it.identifier for it in root1.interface.items_tree
              if it.item_type == 'SOCKET' and it.in_out == 'INPUT' and it.socket_type == 'NodeSocketColor'}
    vectors = entry.get("vectors") or {}
    if any(kind == "V" and ident in colour and any(float(x) < 0.0 for x in tuple(vectors.get(name) or ())[:3])
           for ident, kind, name, _default in params):
        return None
    ambiguous = object()

    def new_key(names):
        keys = {textures.get(p, defaults.get(p)) for p in names}
        return keys.pop() if len(keys) == 1 else ambiguous
    changed = {}

    def changes(tree):
        if tree.name in changed:
            return changed[tree.name]
        changed[tree.name] = False      # a cycle can't change anything twice
        c = False
        for n in tree.nodes:
            if n.bl_idname == "ShaderNodeTexImage" and "mp_tex" in n:
                k = new_key(list(n["mp_tex"]))
                if k is ambiguous:
                    raise LookupError(n.name)
                c = c or k != n["mp_key"]
            elif n.bl_idname == "ShaderNodeGroup" and n.node_tree is not None:
                c = changes(n.node_tree) or c
        changed[tree.name] = c
        return c
    try:
        changes(root1)
    except LookupError:
        return None
    env = MaterialEnv(app, entry, [])
    copies = {}

    def clone(tree):
        if not changed.get(tree.name):
            return tree
        if tree.name in copies:
            return copies[tree.name]
        t2 = tree.copy()
        copies[tree.name] = t2
        if KEY_FP in t2:
            del t2[KEY_FP]      # not the twin of what it was copied from
        for n in t2.nodes:
            if n.bl_idname == "ShaderNodeTexImage" and "mp_tex" in n:
                k = new_key(list(n["mp_tex"]))
                if k != n["mp_key"]:
                    n.image = env.texture(k, "Normal" if n.get("mp_normal") else "")
                    n["mp_key"] = k
            elif n.bl_idname == "ShaderNodeGroup" and n.node_tree is not None:
                n.node_tree = clone(n.node_tree)
        return t2

    mat = src.copy()
    mat.name = PREFIX + entry["name"]
    root2 = clone(root1)
    if root2 is not root1:
        root2.name = mat.name
    node = next(n for n in mat.node_tree.nodes if n.bl_idname == "ShaderNodeGroup" and n.node_tree == root1)
    node.node_tree = root2
    node.label = entry["name"]
    scalars, vectors = entry.get("scalars") or {}, entry.get("vectors") or {}
    by_id = {s.identifier: s for s in node.inputs}
    for ident, kind, name, default in params:
        sock = by_id.get(ident)
        if sock is None:
            continue
        if kind == "P":
            sock.default_value = float(scalars.get(name, default if default is not None else sock.default_value))
        else:
            rgba = vectors.get(name, default)
            if rgba is None:
                continue
            rgba = tuple(rgba) + (1.0,) * (4 - len(rgba))
            sock.default_value = fit_socket(sock, rgba) if kind == "V" else float(rgba[3])
    mat[KEY_PATH] = entry["path"]
    mat[KEY_REV] = BUILD_REVISION
    mat["mp_copied_from"] = src.name
    if entry.get("variant"):
        mat[KEY_VARIANT] = entry["variant"]
    elif KEY_VARIANT in mat:
        del mat[KEY_VARIANT]
    world.apply_fog(mat)
    return mat, list(env.notes) + ["same shape as %s: copied, %d group(s) with other images" % (src.name, len(copies))]


# ------------------------------------------------------------------ bundles
def build_bundle(payload):
    """The app's POST /build: every material built and put in place."""
    app = AppClient(payload["app"])
    begin_session()
    built = []
    for entry in payload.get("materials", []):
        target = entry.get("target") or {}
        try:
            if "replace" in target:
                old = bpy.data.materials.get(target["replace"])
                objects = [o for o in bpy.data.objects
                           if old is not None and any(s.material == old for s in getattr(o, "material_slots", []))]
                mat, notes = build_one(entry, app, objects)
                if old is not None:
                    old.user_remap(mat)
                    old.use_fake_user = True          # kept, for Revert
                    old[KEY_REPLACED_BY] = mat.name
                    mat[KEY_REPLACES] = old.name
                built.append({"name": mat.name, "replaced": target["replace"], "notes": notes})
            else:
                objects = [o for o in bpy.context.selected_objects if o.type == 'MESH']
                mat, notes = build_one(entry, app, objects)
                for o in objects:
                    if not o.material_slots:
                        o.data.materials.append(mat)
                    else:
                        o.material_slots[o.active_material_index].material = mat
                built.append({"name": mat.name, "assigned": [o.name for o in objects], "notes": notes})
        except Exception as e:
            import traceback
            traceback.print_exc()
            built.append({"name": entry.get("name"), "error": "%s: %s" % (type(e).__name__, e)})
    return {"built": built}


def scene_materials():
    """The app's GET /scene: FP-imported materials still in use, with the
    textures FP loaded for them (to tell same-named game materials apart)."""
    out = []
    for m in bpy.data.materials:
        if "OriginalName" not in m or KEY_REPLACED_BY in m:
            continue
        users = m.users - (1 if m.use_fake_user else 0)
        if users <= 0:
            continue
        images = sorted({n.image.name.rsplit(".", 1)[0] for n in (m.node_tree.nodes if m.node_tree else [])
                         if n.type == 'TEX_IMAGE' and n.image is not None})
        out.append({"name": m.name, "original": m["OriginalName"], "users": users, "images": images})
    return {"materials": out}


def revert_all():
    """Every converted material back to FP's."""
    n = 0
    for m in [m for m in bpy.data.materials if KEY_REPLACES in m]:
        old = bpy.data.materials.get(m[KEY_REPLACES])
        if old is None:
            continue
        m.user_remap(old)
        old.use_fake_user = False
        if KEY_REPLACED_BY in old:
            del old[KEY_REPLACED_BY]
        bpy.data.materials.remove(m)
        n += 1
    return n
