# Generated by materialporter/tools/sync_fork.py from blender/material_porter/bundles.py - edit it there.
"""A function group's Material Attributes as bundles, as FP's own modules pass them.

A Material Attributes input or output of a UE function is one socket per attribute on its group
node ("Material: Base Color", "Material: Normal", ... "Result: Base Color", ...): twenty wires
from one module to the next. Once an import's groups are pruned (build.pruning), each such set
of two or more sockets becomes one Bundle socket: a Separate Bundle inside the group hands its
attributes out, a Combine Bundle gathers what the group sets; where the group is used, a Combine
Bundle gathers what goes in and a Separate Bundle hands out what comes out. A module's bundle
feeding the next one's attribute for attribute is then one wire (Pre FX -> Post FX). The shader
is the same: bundles resolve when the shader is compiled.
"""
import bpy

from .ue_graph import ATTRIBUTE_DEFAULT, ATTRIBUTE_WIDTH, BREAK_ORDER, CARRIED, pretty

KEY_FROM = "mp_bundled_from"    # a bundled group: the fingerprint (build.KEY_FP) it had before
TAG = "mp_bundle"               # on the bundle nodes this makes: "in" / "out" / "use_in" / "use_out" / "set" / "join"
ATTRIBUTE_NAMES = {pretty(a) for a in BREAK_ORDER}
# each attribute's item type, the same in every bundle (a module's Base Color and the next one's must
# match: a Separate Bundle reads an item of another type as 0)
ITEM_OF = {pretty(a): 'FLOAT' if ATTRIBUTE_WIDTH.get(a, 1) == 1 else 'VECTOR' for a in BREAK_ORDER}
# a module's whole Material Attributes: what it doesn't set, at UE's defaults (as FP's modules pass them)
COMPLETE = [(pretty(a), ITEM_OF[pretty(a)], ATTRIBUTE_DEFAULT.get(a)) for a in CARRIED]
PARAMETER_PREFIXES = ("P", "V")     # a parameter's socket ("P: Roughness"): not an attribute
ITEM_TYPE = {'VALUE': 'FLOAT', 'VECTOR': 'VECTOR', 'RGBA': 'RGBA', 'INT': 'INT', 'BOOLEAN': 'BOOLEAN'}


def _attribute_sets(tree, in_out):
    """{prefix: [interface socket, ...]} of the tree's attribute sockets, two or more a prefix."""
    sets = {}
    for it in tree.interface.items_tree:
        if it.item_type != 'SOCKET' or it.in_out != in_out or ": " not in it.name:
            continue
        prefix, attribute = it.name.rsplit(": ", 1)
        if attribute in ATTRIBUTE_NAMES and prefix not in PARAMETER_PREFIXES:
            sets.setdefault(prefix, []).append(it)
    return {p: items for p, items in sets.items() if len(items) >= 2}


def _item_type(sock):
    return ITEM_TYPE.get(sock.type, 'FLOAT')


def _value(sock):
    v = getattr(sock, "default_value", None)
    return tuple(v) if hasattr(v, "__len__") else v


def _set(sock, value):
    if value is None or not hasattr(sock, "default_value"):
        return
    try:
        if hasattr(sock.default_value, "__len__"):
            n = len(sock.default_value)
            vals = tuple(value) if hasattr(value, "__len__") else (value,) * n
            sock.default_value = (vals + (1.0,) * n)[:n]
        else:
            sock.default_value = value[0] if hasattr(value, "__len__") else value
    except (TypeError, ValueError):
        pass


def _users(group, trees):
    return [(t, n) for t in trees for n in t.nodes if n.bl_idname == "ShaderNodeGroup" and n.node_tree == group]


def _items(node, names, types):
    node.bundle_items.clear()
    for name in names:
        node.bundle_items.new(types[name], name)


def _bundle_group(group, trees):
    """Group's attribute socket sets as bundles, inside and where it is used. How many sets."""
    ins, outs = _attribute_sets(group, 'INPUT'), _attribute_sets(group, 'OUTPUT')
    if not ins and not outs:
        return 0
    users = _users(group, trees)
    iface = group.interface
    made = 0
    for in_out, sets in (('INPUT', ins), ('OUTPUT', outs)):
        for prefix, socks in sets.items():
            idents = {it.identifier: it.name.rsplit(": ", 1)[1] for it in socks}
            names = [idents[it.identifier] for it in socks]
            # what the group node's sockets carry, before they go: links and values
            types, recorded = {}, []
            for t, n in users:
                rec = {}
                sockets = n.inputs if in_out == 'INPUT' else n.outputs
                for s in sockets:
                    if s.identifier not in idents:
                        continue
                    name = idents[s.identifier]
                    types.setdefault(name, _item_type(s))
                    if in_out == 'INPUT':
                        rec[name] = (s.links[0].from_socket if s.is_linked else None, _value(s))
                    else:
                        rec[name] = [l.to_socket for l in s.links]
                recorded.append((t, n, rec))
            # and inside: the Group Inputs' links out of those sockets, the Group Output's into them
            inside = []
            for n in group.nodes:
                if in_out == 'INPUT' and n.bl_idname == "NodeGroupInput":
                    for s in n.outputs:
                        if s.identifier in idents and s.is_linked:
                            types.setdefault(idents[s.identifier], _item_type(s))
                            inside.append((n, idents[s.identifier], [l.to_socket for l in s.links]))
                elif in_out == 'OUTPUT' and n.bl_idname == "NodeGroupOutput":
                    for s in n.inputs:
                        if s.identifier in idents:
                            types.setdefault(idents[s.identifier], _item_type(s))
                            inside.append((n, idents[s.identifier], (s.links[0].from_socket if s.is_linked else None, _value(s))))
            for name in names:
                types[name] = ITEM_OF.get(name, types.get(name, 'FLOAT'))
            # the bundle socket, where the first of them was
            first = socks[0]
            parent, position = first.parent, first.position
            bundle = iface.new_socket(prefix, in_out=in_out, socket_type='NodeSocketBundle')
            if parent is not None and parent.name:
                iface.move_to_parent(bundle, parent, position)
            else:
                iface.move(bundle, position)
            for it in socks:
                iface.remove(it)
            ident = bundle.identifier
            # inside the group
            if in_out == 'INPUT':
                by_gi = {}
                for gi, name, targets in inside:
                    sep = by_gi.get(gi.name)
                    if sep is None:
                        sep = group.nodes.new("NodeSeparateBundle")
                        sep.label, sep[TAG] = prefix, "in"
                        sep.location = (gi.location.x + 60, gi.location.y)
                        _items(sep, names, types)
                        group.links.new(next(o for o in gi.outputs if o.identifier == ident), sep.inputs[0])
                        by_gi[gi.name] = sep
                    out = sep.outputs[name]
                    for target in targets:
                        group.links.new(out, target)
            else:
                outs_by_node = {}
                for go, name, (src, value) in inside:
                    comb = outs_by_node.get(go.name)
                    if comb is None:
                        comb = group.nodes.new("NodeCombineBundle")
                        comb.label, comb[TAG] = prefix, "out"
                        comb.location = (go.location.x - 160, go.location.y)
                        _items(comb, names, types)
                        group.links.new(comb.outputs[0], next(i for i in go.inputs if i.identifier == ident))
                        outs_by_node[go.name] = comb
                        for extra, kind, default in COMPLETE:
                            if extra not in names:
                                comb.bundle_items.new(kind, extra)
                                _set(comb.inputs[extra], default)
                    if src is not None:
                        group.links.new(src, comb.inputs[name])
                    else:
                        _set(comb.inputs[name], value)
            # where the group is used
            for t, n, rec in recorded:
                sock = next(s for s in (n.inputs if in_out == 'INPUT' else n.outputs) if s.identifier == ident)
                if in_out == 'INPUT':
                    comb = t.nodes.new("NodeCombineBundle")
                    comb.label, comb[TAG] = prefix, "use_in"
                    comb.location = (n.location.x - 180, n.location.y)
                    _items(comb, names, types)
                    for name, (src, value) in rec.items():
                        if src is not None:
                            t.links.new(src, comb.inputs[name])
                        else:
                            _set(comb.inputs[name], value)
                    t.links.new(comb.outputs[0], sock)
                else:
                    if not any(rec.values()):
                        continue
                    sep = t.nodes.new("NodeSeparateBundle")
                    sep.label, sep[TAG] = prefix, "use_out"
                    sep.location = (n.location.x + n.width + 40, n.location.y)
                    _items(sep, [nm for nm in names if rec.get(nm)], types)
                    t.links.new(sock, sep.inputs[0])
                    for name, targets in rec.items():
                        for target in targets:
                            t.links.new(sep.outputs[name], target)
            made += 1
    return made


def _zero(v):
    if v is None:
        return True
    vals = v if hasattr(v, "__len__") else (v,)
    return all(abs(float(x)) < 1e-9 for x in vals)


def _producer(sep):
    """{attribute: value, or None where computed} of the module bundle a Separate Bundle reads (its
    group's inner Combine Bundle), or None when unknown."""
    if not sep.inputs[0].is_linked:
        return None
    bundle = sep.inputs[0].links[0].from_socket
    g = bundle.node
    if g.bl_idname != "ShaderNodeGroup" or g.node_tree is None:
        return None
    comb = next((n for n in g.node_tree.nodes if n.get(TAG) == "out" and n.label == bundle.name), None)
    if comb is None:
        return None
    return {s.name: (None if s.is_linked else _value(s)) for s in comb.inputs if s.name and s.identifier != "__extend__"}


def _same(a, b):
    va = a if hasattr(a, "__len__") else (a,)
    vb = b if hasattr(b, "__len__") else (b,)
    n = min(len(va), len(vb), 3)
    return all(abs(float(va[i]) - float(vb[i])) < 1e-6 for i in range(n))


MISSING = object()


def _collapse(trees):
    """A Combine Bundle gathering what a module's bundle holds (through its Separate Bundle) takes
    that bundle instead, with what differs joined over it (a "set" bundle: what a module between
    changed, a value the bundle doesn't hold); the Separate goes once nothing else reads it."""
    n_done = 0
    for t in trees:
        for comb in [n for n in t.nodes if n.get(TAG) == "use_in"]:
            items = [s for s in comb.inputs if s.name and s.identifier != "__extend__" and s.enabled]
            counts = {}
            for s in items:
                if s.is_linked:
                    src = s.links[0].from_socket
                    if src.node.bl_idname == "NodeSeparateBundle" and src.node.get(TAG) == "use_out" and src.name == s.name:
                        counts[src.node] = counts.get(src.node, 0) + 1
            if not counts:
                continue
            source = max(counts, key=counts.get)
            if counts[source] < 2 or not source.inputs[0].is_linked:
                continue
            made = _producer(source) or {}
            overrides = []
            for s in items:
                if s.is_linked:
                    src = s.links[0].from_socket
                    if src.node == source and src.name == s.name:
                        continue
                    overrides.append((s, src, None))
                    continue
                v = _value(s)
                pv = made.get(s.name, MISSING)
                if pv is MISSING:
                    if _zero(v):
                        continue        # (missing from the bundle: 0, the same)
                elif pv is not None and _same(v, pv):
                    continue
                overrides.append((s, None, v))
            if len(overrides) * 2 > len(items):
                continue
            bundle = source.inputs[0].links[0].from_socket
            target = bundle
            if overrides:
                put = t.nodes.new("NodeCombineBundle")
                put.label, put[TAG] = "set", "set"
                put.location = (comb.location.x, comb.location.y - 120)
                put.bundle_items.clear()
                for s, src, v in overrides:
                    put.bundle_items.new(ITEM_OF.get(s.name, ITEM_TYPE.get(s.type, 'FLOAT')), s.name)
                for s, src, v in overrides:
                    if src is not None:
                        t.links.new(src, put.inputs[s.name])
                    else:
                        _set(put.inputs[s.name], v)
                join = t.nodes.new("NodeJoinBundle")
                join.label, join[TAG] = comb.label, "join"
                join.location = comb.location
                # (the bundle first, what's set over it after: the later one wins)
                t.links.new(bundle, join.inputs[0])
                t.links.new(put.outputs[0], join.inputs[0])
                target = join.outputs[0]
            for l in list(comb.outputs[0].links):
                t.links.new(target, l.to_socket)
            t.nodes.remove(comb)
            if not any(o.is_linked for o in source.outputs):
                t.nodes.remove(source)
            n_done += 1
    return n_done


def _all_trees():
    return [m.node_tree for m in bpy.data.materials if m.node_tree is not None] + list(bpy.data.node_groups)


def bundle_attributes(groups, key_fp=None, known=None):
    """The given function groups' attribute sockets as bundles (an import's, after pruning).
    key_fp/known: the sharing fingerprint key and its cache (build.KEY_FP, build._KNOWN): a bundled
    group no longer stands for its unbundled fingerprint. Returns (sets bundled, wires joined)."""
    trees = _all_trees()
    made = 0
    for g in groups:
        try:
            n = _bundle_group(g, trees)
        except ReferenceError:
            continue
        if n and key_fp and key_fp in g:
            old = g[key_fp]
            g[KEY_FROM] = old
            g[key_fp] = old + "+bundled"
            if known is not None and known.get(old) == g:
                del known[old]
        made += n
    joined = _collapse(trees) if made else 0
    return made, joined
