# Generated by materialporter/tools/sync_fork.py from blender/material_porter/env.py - edit it there.
"""What a UE material reads from the world, for a material on a mesh in Blender.

The translator (ue_graph) asks its env for everything outside the graph. This
one answers for a FortnitePorting import:

* UE space: FP mirrors Y and scales by 0.01, so a Blender world vector is
  (x, -y, z) in UE, and a position that times 100 (cm).
* A material's graph is one node group (its "root"); each parameter is an
  input of it - a float, a colour (and its alpha) - holding the instance's
  value on the material's group node, as a UE material instance shows them.
  Inputs sit in panels named after the function they're read through
  ("Material" for the master's own), alphabetical within; unused ones go.
  Inside a function group a parameter is a socket of that group ("P: Name"),
  so groups stay shareable between instances.
* Static switches, component masks and texture parameters come from the
  instance chain (the app merged it, child first).
* Graphs and textures come from the app, as the build reaches them.
* Mesh inputs use FP's names: UV maps "UV0", "UV1"..., vertex colour "COL0".
"""
import re

import bpy

from . import world
from .ue_graph import BOUNDS_MAX, BOUNDS_MIN, PIXEL_NORMAL, WATER_DEPTH_DEFAULT, Val

# a vector parameter that names a colour gets a colour socket (a picker); any other - an offset, a
# direction, a channel, a size - a vector socket: a colour socket clamps negatives to 0 (a sprite
# variant's sphere offset (0, -9.7, -23.5) was read as (0, 0, 0), its fade at the feet)
COLOURISH = re.compile(r"colou?r|tint|albedo|emissive|diffuse|glow|light|fog|sky|fresnelcol", re.IGNORECASE)


def vector_socket(name, *values):
    """'NodeSocketColor' or 'NodeSocketVector' for a vector parameter (its known values: none negative
    for a colour socket)."""
    negative = any(float(x) < 0.0 for v in values if v is not None for x in tuple(v)[:3])
    return 'NodeSocketColor' if COLOURISH.search(name or "") and not negative else 'NodeSocketVector'


def fit_socket(sock, value):
    """A vector parameter's value (r, g, b, a) as the socket takes it (a vector socket: x, y, z)."""
    value = tuple(value)
    n = len(sock.default_value)
    return value[:n] + (1.0,) * (n - len(value))

COLORSPACE_SRGB = "sRGB"
COLORSPACE_DATA = "Non-Color"
# a water surface's depth, baked by a map import (water.bake_water): x the
# metres down to the ground under each vertex, y 1 where it was baked
WATER_ATTRIBUTE = "mp_water"

# images this session loaded, by file: a map's hundreds of materials share
# textures, and images.load(check_existing=True) walks every image each time
_LOADED = {}


def _load(path, w, h):
    """An image for this file: the one loaded before (still there), else loaded
    (an older, smaller copy the file already had is reloaded; reading its size
    decodes it, so a fresh load isn't asked)."""
    img = _LOADED.get(path)
    if img is not None:
        try:
            img.name
            return img
        except ReferenceError:      # removed since
            pass
    known = len(bpy.data.images)
    img = bpy.data.images.load(path, check_existing=True)
    if len(bpy.data.images) == known and w and h and tuple(img.size) != (w, h):
        img.reload()
    _LOADED[path] = img
    return img


class MaterialEnv:
    nest_functions = True
    asset_paths = True          # textures and collections by object path
    replace_groups = False      # other materials' groups stay
    function_prefix = ""
    texture_closures = True     # image nodes at the root, functions' groups sample them through closures
    whole_functions = True      # a function's group has all its outputs: materials share one group

    def __init__(self, app, entry, objects=()):
        self.app, self.entry = app, entry
        self.objects = [o for o in objects if o is not None]
        self.h = [None]
        self._once = {}
        self._images = {}
        self._defaults = {}
        self.notes = []
        self.root = None        # the material's node group: parameters become its inputs
        self.caller = None      # the function a parameter is reached through (its panel)
        self._params = {}       # key -> (interface item, Val, value, panel name)
        self._claimed = {}      # (image, channel) -> the channel mask guessed onto it
        self._panels = {}
        self._textures = {}         # texture spec -> (interface item, its Group Input socket, (key, image, own sampler, address))
        # what another instance of the same shape needs to reuse this build (build.build_like):
        # which parameters each texture came from, each parameter's graph default, normal maps;
        # False when the trees hold more than parameter values (a guessed mask, the object's
        # bounds, a texture array's slices, a baked value)
        self.reusable = True
        self.tex_params = {}        # texture key -> {parameter names that resolved to it}
        self.tex_default = {}       # texture parameter -> its graph default key
        self.tex_normal = set()     # keys sampled as normal maps
        self.graph_defaults = {}    # "P: name" / "V: name" -> the graph's default

    # ------------------------------------------------------------ plumbing
    @property
    def tr(self):
        return self.h[0]

    def current(self):
        return self.h[0]

    def set_current(self, tr):
        self.h[0] = tr

    def once(self, key, make):
        k = (self.tr.tree.as_pointer(), key)
        if k not in self._once:
            self._once[k] = make()
        return self._once[k]

    def note(self, text):
        if text not in self.notes:
            self.notes.append(text)

    def _ue(self, v, scale=1.0):
        """A Blender vector in UE space (Y mirrored), times `scale`."""
        return self.tr.vmath('MULTIPLY', v, self.tr.const((scale, -scale, scale), 3), out_w=3)

    def _geo(self):
        return self.once("geo", lambda: self.tr.node("ShaderNodeNewGeometry", "geometry"))

    # ------------------------------------------------------------ view and world
    def _incoming(self):
        """From the shaded point towards the camera (Blender's axes). A particle's material also
        runs at the vertices (its World Position Offset), where the Geometry node's Incoming is
        zero: there it is the camera's view vector, turned into the world and back on itself."""
        if not self.entry.get("particle"):
            return Val(self._geo().outputs["Incoming"], 3)

        def make():
            cam = self.tr.node("ShaderNodeCameraData", "camera data")
            to_world = self.tr.node("ShaderNodeVectorTransform", "view to world", vector_type='VECTOR', convert_from='CAMERA', convert_to='WORLD')
            self.tr.L.new(cam.outputs["View Vector"], to_world.inputs[0])
            away = self.tr.vmath('NORMALIZE', Val(to_world.outputs[0], 3), out_w=3)
            seen = self.tr.vmath('SCALE', away, self.tr.const(-1.0), out_w=3)
            # Cycles works out a displacement once per mesh, without a camera: there, the camera's
            # direction the plugin keeps in the scene's ["mp_fx_cam_fwd"]
            fwd = self._scene_vector("mp_fx_cam_fwd", "the camera's direction (Cycles)")
            back = self.tr.vmath('SCALE', self.tr.vmath('NORMALIZE', fwd, out_w=3), self.tr.const(-1.0), out_w=3)
            return self._when_cycles(seen, back)
        return self.once("incoming", make)

    def _cycles(self):
        """1 while the scene renders with Cycles (the plugin's ["mp_fx_cycles"]), else 0."""
        return self.once("cycles flag", lambda: Val(self.tr.node(
            "ShaderNodeAttribute", "rendering with Cycles", attribute_type='VIEW_LAYER',
            attribute_name='["mp_fx_cycles"]').outputs["Fac"], 1))

    def _scene_vector(self, name, label):
        return self.once("scene " + name, lambda: Val(self.tr.node(
            "ShaderNodeAttribute", label, attribute_type='VIEW_LAYER', attribute_name='["%s"]' % name).outputs["Vector"], 3))

    def _when_cycles(self, eevee, cycles):
        """eevee, or cycles while the scene renders with Cycles."""
        return self.tr.vmath('ADD', eevee, self.tr.vmath('SCALE', self.tr.vmath('SUBTRACT', cycles, eevee, out_w=3),
                                                          self._cycles(), out_w=3), out_w=3)

    def camera_vector(self):
        return self.once("camvec", lambda: self._ue(self._incoming()))

    def world_position(self, camera_relative=False):
        p = self.once("wpos", lambda: self._ue(Val(self._geo().outputs["Position"], 3), 100.0))
        return self.tr.vmath('SUBTRACT', p, self.camera_position(), out_w=3) if camera_relative else p

    def camera_position(self):
        def make():
            # the camera is where the view ray leaves: P + Incoming * view distance
            cam = self.tr.node("ShaderNodeCameraData", "camera data")
            geo = self._geo()
            ray = self.tr.vmath('SCALE', self._incoming(), Val(cam.outputs["View Distance"], 1), out_w=3)
            at = self.tr.vmath('ADD', Val(geo.outputs["Position"], 3), ray, out_w=3)
            if self.entry.get("particle"):
                # (under Cycles, the camera's position the plugin keeps in the scene's ["mp_fx_cam_pos"])
                at = self._when_cycles(at, self._scene_vector("mp_fx_cam_pos", "the camera's position (Cycles)"))
            return self._ue(at, 100.0)
        return self.once("campos", make)

    def actor_position(self, camera_relative=False):
        def make():
            n = self.tr.node("ShaderNodeObjectInfo", "object info")
            return self._ue(Val(n.outputs["Location"], 3), 100.0)
        p = self.once("actor", make)
        return self.tr.vmath('SUBTRACT', p, self.camera_position(), out_w=3) if camera_relative else p

    def light_direction(self):
        """Towards the sun: the file's sun group (the scene's sun lamp, driven; a time of day's)."""
        return world.sun(self.tr)

    def light_color(self):
        """The sun's colour times its strength (UE's DirectionalLightColor): the sun group's."""
        return world.sun(self.tr, "Color")

    def view_luminance(self, direction):
        """The sky along a direction: the file's sky group (a time of day's atmosphere; a flat
        sky colour without one)."""
        return world.sky(self.tr, direction)

    def sky_light(self, direction, roughness):
        """UE's sky light along a direction: the same sky."""
        return world.sky(self.tr, direction)

    def aerial_perspective(self, position):
        """UE's SkyAtmosphereAerialPerspective at a point (UE cm): the light the air between the camera
        and it scatters in, and how much of the point shows through. UE reads a froxel volume; here
        the sky along the way, as much as the air crossed (an exponential atmosphere, 8 km scale
        height: path = H (1 - exp(-d z / H)) / z km) scatters: in-scattering 1 - exp(-path / 10),
        transmittance exp(-path / 30)."""
        tr = self.tr
        d = tr.vmath('SUBTRACT', tr.as3(position), self.camera_position(), out_w=3)
        km = tr.binop('DIVIDE', tr.vmath('LENGTH', d, out_w=1), tr.const(1e5))
        dirn = tr.vmath('NORMALIZE', d, out_w=3)
        z = tr.math('MAXIMUM', tr.comps(dirn)[2], tr.const(1e-3))
        path = tr.binop('DIVIDE', tr.binop('MULTIPLY', tr.const(8.0), tr.binop('SUBTRACT', tr.const(1.0), tr.math(
            'EXPONENT', tr.binop('DIVIDE', tr.binop('MULTIPLY', tr.binop('MULTIPLY', km, z), tr.const(-1.0)), tr.const(8.0))))), z)
        path = tr.math('MINIMUM', path, km)
        inscatter = tr.binop('SUBTRACT', tr.const(1.0), tr.math('EXPONENT', tr.binop('DIVIDE', path, tr.const(-10.0))))
        through = tr.math('EXPONENT', tr.binop('DIVIDE', path, tr.const(-30.0)))
        return tr.vmath('SCALE', world.sky(tr, dirn), inscatter, out_w=3), through

    # the game's clock is never near zero: what a material times from a moment (a hit's
    # flash, a spawn's fade: GameTime + the hit time, against Time) is over, as at rest
    TIME_OFFSET = 100.0

    def time(self):
        def make():
            with self.tr.at("Parameters"):
                n = self.tr.node("ShaderNodeValue", "Time (s)")
            d = n.outputs[0].driver_add("default_value").driver
            d.type = 'SCRIPTED'
            d.expression = "frame / %g + %g" % (bpy.context.scene.render.fps / bpy.context.scene.render.fps_base, self.TIME_OFFSET)
            return Val(n.outputs[0], 1)
        return self.once("time", make)

    def cloud_sample(self, out):
        return self.tr.const(0.0)

    # ------------------------------------------------------------ mesh
    def uv(self, index):
        def make():
            n = self.tr.node("ShaderNodeUVMap", "UV%d" % index)
            n.uv_map = "UV%d" % index
            u, v = self.tr.comps(Val(n.outputs[0], 3))[:2]
            # UE's V runs down
            v = self.tr.binop('SUBTRACT', self.tr.const(1.0), v)
            sprite = self.entry.get("sprite") if index == 0 else None
            if sprite and sprite[0] * sprite[1] > 1:
                u, v = self._sub_image(u, v, float(sprite[0]), float(sprite[1]))
            return self.tr.combine([u, v])
        return self.once("uv%d" % index, make)

    def _sub_image(self, u, v, across, down):
        """A sprite's UV0 over a flipbook: the sub-image its particle shows (mp_subimage on the
        object or the instance: the first where it has none), as UE's sprites carry it."""
        tr = self.tr
        index = tr.math('FLOOR', self._particle_attr("mp_subimage")[2])
        column = tr.math('FLOORED_MODULO', index, tr.const(across))
        row = tr.math('FLOORED_MODULO', tr.math('FLOOR', tr.math('DIVIDE', index, tr.const(across))), tr.const(down))
        return (tr.math('DIVIDE', tr.math('ADD', u, column), tr.const(across)),
                tr.math('DIVIDE', tr.math('ADD', v, row), tr.const(down)))

    def landscape_weight(self, name):
        """A landscape layer's weight: the exported landscape's colour layer of
        that name (a grey weight: its red channel); on another mesh, or where
        a component doesn't paint the layer, 0."""
        def make():
            n = self.tr.node("ShaderNodeVertexColor", "layer " + name)
            n.layer_name = name
            return self.tr.comps(Val(n.outputs["Color"], 3))[0]
        return self.once("layer " + name, make)

    def landscape_uv(self, index):
        """A landscape's texture coordinates (UV0: landscape-wide quads, as the
        export writes them)."""
        return self.uv(index)

    def vertex_color(self):
        def make():
            n = self.tr.node("ShaderNodeVertexColor", "COL0")
            n.layer_name = "COL0"
            return Val(n.outputs["Color"], 3), Val(n.outputs["Alpha"], 1)
        return self.once("col0", make)

    def water_depth(self):
        """How deep the water is under a water surface's pixel, UE cm - at
        run time the water info texture's water height less its ground
        height: the depth a map import bakes onto the surface mesh (the
        mp_water attribute), elsewhere the translator's default."""
        tr = self.tr

        def make():
            n = tr.node("ShaderNodeAttribute", "water depth (baked)")
            n.attribute_type = 'GEOMETRY'
            n.attribute_name = WATER_ATTRIBUTE
            metres, known = tr.comps(Val(n.outputs["Vector"], 3))[:2]
            return tr.lerp(tr.const(WATER_DEPTH_DEFAULT), tr.binop('MULTIPLY', metres, tr.const(100.0)), known,
                           label="water depth (cm)")
        return self.once("water depth", make)

    def local_bounds(self):
        """The object's bounding box, in UE cm: read from the object (mp_bounds_min / max, which
        the import sets on each object its material lands on), so a shared function's group holds
        no object's numbers (baked, every object made its own copy of every group above them).
        Unmarked: +-1 m."""
        tr = self.tr

        def make():
            lo = Val(tr.node("ShaderNodeAttribute", "bounds min", attribute_type='OBJECT', attribute_name=BOUNDS_MIN).outputs["Vector"], 3)
            hi = Val(tr.node("ShaderNodeAttribute", "bounds max", attribute_type='OBJECT', attribute_name=BOUNDS_MAX).outputs["Vector"], 3)
            # an object the import never marked: UE's default +-1 m
            unmarked = tr.binop('LESS_THAN', tr.vmath('DISTANCE', lo, hi), tr.const(1e-9))
            lo = tr.lerp(lo, tr.const((-1.0, -1.0, -1.0), 3), unmarked)
            hi = tr.lerp(hi, tr.const((1.0, 1.0, 1.0), 3), unmarked)
            # UE space (Y mirrored: Blender's top Y is UE's bottom), cm
            lx, ly, lz = tr.comps(lo)
            hx, hy, hz = tr.comps(hi)
            k = tr.const(100.0)
            mn = tr.combine([tr.binop('MULTIPLY', lx, k), tr.binop('MULTIPLY', hy, tr.const(-100.0)), tr.binop('MULTIPLY', lz, k)])
            mx = tr.combine([tr.binop('MULTIPLY', hx, k), tr.binop('MULTIPLY', ly, tr.const(-100.0)), tr.binop('MULTIPLY', hz, k)])
            return mn, mx
        return self.once("local bounds", make)

    # ------------------------------------------------------------ parameters
    def _at_root(self):
        return self.root is not None and self.tr.tree == self.root and self.tr.function is None

    def _root_input(self, key, label, socket_type, value, width, description):
        """A parameter as an input of the material's group (made once)."""
        if key in self._params:
            return self._params[key][1]
        item = self.root.interface.new_socket(label, description=description, in_out='INPUT', socket_type=socket_type)
        item.default_value = value
        if socket_type == 'NodeSocketFloat':
            item.min_value, item.max_value = -1e9, 1e9
        gi = self.once("parameters", lambda: self.tr.node("NodeGroupInput", "parameters"))
        v = Val(next(s for s in gi.outputs if s.identifier == item.identifier), width)
        self._params[key] = (item, v, value, self.caller or "Material")
        return v

    def root_texture(self, spec, tname, sampler, img, own, address):
        """A texture the material's group samples, as a Closure input of the group (Translator.
        texture_closure): its image node goes in the material's own tree, outside the group
        (build._texture_zones), the input in the group's Textures panel. Named for the texture
        parameter, else the texture."""
        if not self._at_root():
            return None
        if spec in self._textures:
            return self._textures[spec][1]
        taken = {it.name for it in self.root.interface.items_tree if it.item_type == 'SOCKET' and it.in_out == 'INPUT'}
        base = getattr(tname, "param", None) or str(tname).rsplit("/", 1)[-1].split(".")[0] or "Texture"
        name, i = base, 2
        while name in taken:
            name = "%s %d" % (base, i)
            i += 1
        item = self.root.interface.new_socket(name, description="UE texture " + base, in_out='INPUT',
                                              socket_type='NodeSocketClosure')
        gi = self.once("parameters", lambda: self.tr.node("NodeGroupInput", "parameters"))
        sock = next(s for s in gi.outputs if s.identifier == item.identifier)
        self._textures[spec] = (item, sock, (tname, img, own, address))
        return sock

    def finish_parameters(self):
        """Unused inputs go; the textures first, in their panel; the parameters in panels by
        function ("Material" first), alphabetical within - or one alphabetical list when
        there's one function and no texture (Blender keeps loose inputs above panels).
        Returns [(identifier, value)] for the group node's sockets."""
        if self.root is None:
            return []
        iface = self.root.interface
        # (a tree two envs translated into - a sky dome and its sun - has a group input node each)
        linked = {s.identifier for n in self.root.nodes if n.bl_idname == "NodeGroupInput" for s in n.outputs if s.is_linked}
        for key, (item, _v, _value, _panel) in list(self._params.items()):
            if item.identifier not in linked:
                iface.remove(item)
                del self._params[key]
        for spec, (item, _sock, _tex) in list(self._textures.items()):
            if item.identifier not in linked:
                iface.remove(item)
                del self._textures[spec]
        by_panel = {}
        for item, _v, _value, panel in self._params.values():
            by_panel.setdefault(panel, []).append(item)
        order = sorted(by_panel, key=lambda n: (n != "Material", n.lower()))
        if len(order) == 1 and not self._textures:
            for i, item in enumerate(sorted(by_panel[order[0]], key=lambda it: it.name.lower())):
                iface.move(item, i)
        else:
            for name in order:
                # a lone parameter panel opens: its inputs were loose before the textures came
                panel = iface.new_panel(name, default_closed=len(order) > 1)
                self._panels[name] = panel
                for i, item in enumerate(sorted(by_panel[name], key=lambda it: it.name.lower())):
                    iface.move_to_parent(item, panel, i)
        if self._textures:
            panel = iface.new_panel("Textures", default_closed=False)
            for i, (item, _sock, _tex) in enumerate(sorted(self._textures.values(), key=lambda t: t[0].name.lower())):
                iface.move_to_parent(item, panel, i)
            iface.move(panel, 0)
        return [(item.identifier, value) for item, _v, value, _panel in self._params.values()]

    def node_width(self):
        """Wide enough for the longest input's name and its value."""
        names = [item.name for item, _v, _value, _panel in self._params.values()] + list(self._panels)
        longest = max((len(n) for n in names), default=10)
        return max(240, min(700, int(7.4 * longest + 110)))

    # parameters the game drives as it plays (a hit's flash, an elimination's dissolve), which
    # nothing in Blender plays: built in at the instance's value, so what they'd switch on folds
    # away (merge_duplicates: a product with 0, a mix at 0)
    GAME_DRIVEN = {"HitGlow", "HitGlowOuter", "NewDissolveGradient"}

    def scalar(self, name, default):
        if not name:
            # an unnamed parameter ("None" in UE): nothing can set it, its default stands
            return self.tr.const(float(default or 0.0))
        if name in self.GAME_DRIVEN:
            return self.tr.const(float(self.entry.get("scalars", {}).get(name, default or 0.0)))
        v = float(self.entry.get("scalars", {}).get(name, default))
        self.graph_defaults.setdefault("P: " + name, float(default or 0.0))
        self._defaults["P: " + name] = v
        fn = self.tr.function
        if fn is not None:
            return fn.env_input("P: " + name, 'NodeSocketFloat', v, "UE scalar parameter " + name)
        if self._at_root():
            return self._root_input("P: " + name, name, 'NodeSocketFloat', v, 1, "UE scalar parameter")

        def make():
            self.reusable = False       # the value is baked into the tree
            with self.tr.at("Parameters"):
                n = self.tr.node("ShaderNodeValue", name)
            n.outputs[0].default_value = v
            return Val(n.outputs[0], 1)
        return self.once("P: " + name, make)

    # vector parameters the game sets while it runs (a blueprint, each frame): no instance
    # holds the value they get. Cyclo's storm core is centred on HeadSocketLocation, the head
    # socket's world position (left at its default: the world origin, the feet)
    RUNTIME_VECTORS = {"HeadSocketLocation"}

    def vector(self, name, rgba):
        if name in self.RUNTIME_VECTORS and name not in self.entry.get("vectors", {}):
            self.note("%s is set by the game at run time: the armature's head stands in" % name)
            return self.tr.head_socket(), self.tr.const(1.0)
        if name in self.GAME_DRIVEN:
            rgba = tuple(self.entry.get("vectors", {}).get(name, rgba))
        if not name or name in self.GAME_DRIVEN:
            rgba = tuple(rgba) + (1.0,) * (4 - len(rgba))
            return self.tr.const(tuple(float(x) for x in rgba[:3]), 3), self.tr.const(float(rgba[3]))
        self.graph_defaults.setdefault("V: " + name, tuple(float(x) for x in rgba) + (1.0,) * (4 - len(rgba)))
        graph_default = rgba
        rgba = tuple(self.entry.get("vectors", {}).get(name, rgba)) + (1.0,) * (4 - len(rgba))
        self._defaults["V: " + name] = rgba
        alpha = self.tr.const(float(rgba[3]))
        socket = vector_socket(name, graph_default, rgba)
        value = rgba if socket == 'NodeSocketColor' else tuple(rgba[:3])
        fn = self.tr.function
        if fn is not None:
            return fn.env_input("V: " + name, socket, value, "UE vector parameter " + name), alpha
        if self._at_root():
            return (self._root_input("V: " + name, name, socket, value, 3, "UE vector parameter"),
                    self._root_input("A: " + name, name + " (A)", 'NodeSocketFloat', float(rgba[3]), 1,
                                     "UE vector parameter, its alpha"))

        def make():
            self.reusable = False       # the value is baked into the tree
            with self.tr.at("Parameters"):
                n = self.tr.node("ShaderNodeRGB", name)
            n.outputs[0].default_value = rgba
            return Val(n.outputs[0], 3)
        return self.once("V: " + name, make), alpha

    def primitive_data(self, v, index, w):
        """UE's Custom Primitive Data: floats a placed component carries (a
        tree's season tint), read from the object's custom properties
        mp_cpd<index> (a map import sets them, with mp_cpd = 1); an object
        without them keeps the material's own value `v`."""
        tr = self.tr

        def attr(name):
            def make():
                with tr.at("Parameters"):
                    n = tr.node("ShaderNodeAttribute", name)
                n.attribute_type = 'OBJECT'
                n.attribute_name = name
                return Val(n.outputs["Fac"], 1)
            return self.once("attr " + name, make)
        flag = attr("mp_cpd")
        if w == 1:
            data = attr("mp_cpd%d" % index)
            return tr.math('ADD', v, tr.math('MULTIPLY', tr.math('SUBTRACT', data, v), flag))
        data = tr.combine([attr("mp_cpd%d" % (index + i)) for i in range(3)])
        return tr.vmath('ADD', v, tr.vmath('SCALE', tr.vmath('SUBTRACT', data, v, out_w=3), flag, out_w=3), out_w=3)

    def _particle_attr(self, name):
        """A particle's value (four floats) as (rgb, alpha, scalar) sockets: the instance's
        attribute where geometry nodes instance the object (a replayed effect's particles), else
        the object's own property. A ribbon's run along it: its mesh's attribute."""
        tr = self.tr

        def make():
            with tr.at("Parameters"):
                n = tr.node("ShaderNodeAttribute", name)
            n.attribute_type = 'GEOMETRY' if self.entry.get("ribbon") else 'INSTANCER'
            n.attribute_name = name
            return Val(n.outputs["Color"], 3), Val(n.outputs["Alpha"], 1), Val(n.outputs["Fac"], 1)
        return self.once("attr4 " + name, make)

    def particle_color(self):
        """UE's Particle Color: what a particle system gives each particle. An effect's objects
        carry it as mp_particle_color (four floats), used where mp_particle is 1; anything else
        is white and opaque, as a mesh outside a particle system is."""
        tr = self.tr
        rgb, alpha, _ = self._particle_attr("mp_particle_color")
        flag = self._particle_attr("mp_particle")[2]
        white = tr.const((1.0, 1.0, 1.0), 3)
        one = tr.const(1.0)
        return (tr.vmath('ADD', white, tr.vmath('SCALE', tr.vmath('SUBTRACT', rgb, white, out_w=3), flag, out_w=3), out_w=3),
                tr.math('ADD', one, tr.math('MULTIPLY', tr.math('SUBTRACT', alpha, one), flag)))

    def particle_time(self):
        """UE's Particle Relative Time: a particle's age over its lifetime (mp_age; 0 where there is none)."""
        return self._particle_attr("mp_age")[2]

    def particle_speed(self):
        """UE's Particle Speed: how fast a particle moves (mp_velocity's length; 0 where there is none)."""
        return self.tr.vmath('LENGTH', self._particle_attr("mp_velocity")[0], out_w=1)

    def depth_behind(self):
        """For UE's DepthFade and SceneDepth: how far the surface behind this pixel is along the view
        ray (UE cm) and whether there is one - Blender's Raycast node from the shading point away from
        the camera (in EEVEE, against the screen's depth: a blended surface leaves it to what is
        behind). None for an opaque or masked material, which is that surface itself."""
        asset, over = self.entry.get("asset") or {}, self.entry.get("overrides") or {}
        blend = str(over.get("BlendMode", asset.get("BlendMode", "")) or "")
        if not blend or "Opaque" in blend or "Masked" in blend:
            return None
        tr = self.tr

        def make():
            with tr.at("Parameters"):
                away = tr.node("ShaderNodeVectorMath", "away from the camera", operation='SCALE')
                away.inputs["Scale"].default_value = -1.0
                tr.L.new(self._geo().outputs["Incoming"], away.inputs[0])
                ray = tr.node("ShaderNodeRaycast", "the surface behind")
                tr.L.new(self._geo().outputs["Position"], ray.inputs["Position"])
                tr.L.new(away.outputs[0], ray.inputs["Direction"])
                ray.inputs["Length"].default_value = 100.0
                hit = Val(ray.outputs["Is Hit"], 1)
                if self.entry.get("particle"):
                    # Cycles' Raycast hits the other particles too (EEVEE's reads the screen's depth, which
                    # blended surfaces leave to what is behind): there, no surface behind - the plugin
                    # keeps the scene's ["mp_fx_cycles"] at 1 while it renders with Cycles
                    hit = tr.math('MULTIPLY', hit, tr.math('SUBTRACT', tr.const(1.0), self._cycles()))
            return (tr.math('MULTIPLY', Val(ray.outputs["Hit Distance"], 1), tr.const(100.0)), hit)
        return self.once("raycast behind", make)

    def decal_fade(self):
        """UE's Decal Lifetime Opacity on an effect's decal: its particle's DecalFade (mp_decal_fade; the
        still piece's own property, 1). None for anything else."""
        if not self.entry.get("particle"):
            return None
        return self._particle_attr("mp_decal_fade")[2]

    def particle_random(self):
        """UE's Particle Random: a particle's own random number, the same for its whole life
        (mp_random; an instance's index changes as particles die). None for anything else."""
        if not self.entry.get("particle"):
            return None
        return self._particle_attr("mp_random")[2]

    def particle_rotation(self):
        """UE's Particle Sprite Rotation: a sprite's turn in radians and in degrees (mp_spin, which
        runs Blender's way round; 0 where there is none)."""
        tr = self.tr
        turn = tr.math('MULTIPLY', self._particle_attr("mp_spin")[2], tr.const(-1.0))
        return tr.combine([turn, tr.math('MULTIPLY', turn, tr.const(57.29577951308232))])

    def particle_direction(self):
        """UE's Particle Direction: the way a particle moves, in UE's axes (mp_velocity, which is
        in Blender's; 0 where there is none)."""
        tr = self.tr
        ue = tr.vmath('MULTIPLY', self._particle_attr("mp_velocity")[0], tr.const((1.0, -1.0, 1.0), 3), out_w=3)
        return tr.vmath('NORMALIZE', ue, out_w=3)

    def particle_size(self):
        """UE's Particle Size: a sprite's width and height (mp_size; 1 m where there is none)."""
        tr = self.tr
        x, y = tr.comps(self._particle_attr("mp_size")[0])[:2]
        has = tr.math('GREATER_THAN', tr.math('ADD', x, y), tr.const(0.0))
        usual = tr.const(100.0)
        return tr.combine([tr.math('ADD', usual, tr.math('MULTIPLY', tr.math('SUBTRACT', v, usual), has)) for v in (x, y)])

    def dynamic_parameter(self, index, default=None):
        """UE's Dynamic Parameter <index>: four floats a particle system sets per particle, from
        mp_dynamic<index> where mp_dynamic (four flags, one per parameter) says the effect sets
        it; the expression's default elsewhere."""
        if default is None:
            return None
        tr = self.tr
        rgb, alpha, _ = self._particle_attr("mp_dynamic%d" % index)
        flags = self._particle_attr("mp_dynamic")
        flag = tr.comps(flags[0])[index] if index < 3 else flags[1]
        d3 = tr.mask(default, [0, 1, 2])
        da = default.a if default.a is not None else tr.const(1.0)
        out = tr.vmath('ADD', d3, tr.vmath('SCALE', tr.vmath('SUBTRACT', rgb, d3, out_w=3), flag, out_w=3), out_w=3)
        return Val(out.s, 4, tr.math('ADD', da, tr.math('MULTIPLY', tr.math('SUBTRACT', alpha, da), flag)))

    def instance_data(self, v, index, w):
        """UE's PerInstanceCustomData: an instanced mesh's own floats, from
        the object's mp_pic<index> properties; the material's default `v`
        where the instance has fewer than index + w of them (mp_pic: how
        many, 0 on other objects), as UE reads past NumCustomDataFloats."""
        tr = self.tr

        def attr(name):
            def make():
                with tr.at("Parameters"):
                    n = tr.node("ShaderNodeAttribute", name)
                n.attribute_type = 'OBJECT'
                n.attribute_name = name
                return Val(n.outputs["Fac"], 1)
            return self.once("attr " + name, make)
        has = tr.math('GREATER_THAN', attr("mp_pic"), tr.const(float(index + w - 1) + 0.5))
        if w == 1:
            data = attr("mp_pic%d" % index)
            return tr.math('ADD', v, tr.math('MULTIPLY', tr.math('SUBTRACT', data, v), has))
        data = tr.combine([attr("mp_pic%d" % (index + i)) for i in range(w)])
        return tr.vmath('ADD', v, tr.vmath('SCALE', tr.vmath('SUBTRACT', data, v, out_w=w), has, out_w=w), out_w=w)

    def view_size(self):
        """The render's size, followed (world.view_group: its drivers)."""
        return self.once("view size", lambda: world.view(self.tr, "View Size"))

    def view_property(self, name):
        """The camera's field of view, followed (world.view_group); None: the translator's own."""
        if name == "TanHalfFieldOfView":
            return self.once("tan half fov", lambda: world.view(self.tr, "Tan Half FOV"))
        if name == "FieldOfView":
            def make():
                tx, ty = self.tr.comps(self.view_property("TanHalfFieldOfView"))[:2]
                return self.tr.combine([self.tr.binop('MULTIPLY', self.tr.math('ARCTANGENT', tx), self.tr.const(2.0)),
                                        self.tr.binop('MULTIPLY', self.tr.math('ARCTANGENT', ty), self.tr.const(2.0))])
            return self.once("fov", make)
        if name in ("ViewSize", "BufferSize"):
            return self.view_size()
        return None

    def normal_mode(self):
        """(whether the Normal is lit, whether it's in tangent space): UE compiles an unlit
        material's Normal out (its PixelNormalWS is the vertex normal)."""
        asset, over = self.entry.get("asset") or {}, self.entry.get("overrides") or {}
        shading = str(over.get("ShadingModel", asset.get("ShadingModel")) or "").split("::")[-1]
        return shading != "MSM_Unlit", bool(asset.get("bTangentSpaceNormal", True))

    def group_input(self, key):
        """A function group's parameter socket, fed from where it's called."""
        if key == PIXEL_NORMAL:
            return self.tr.pixel_normal()
        if key.startswith("P: "):
            return self.scalar(key[3:], self._defaults.get(key, 0.0))
        if key.startswith("V: "):
            return self.vector(key[3:], self._defaults.get(key, (0.0, 0.0, 0.0, 1.0)))[0]
        return self.tr.const(0.0)

    def static_switch(self, name, default):
        return bool(self.entry.get("switches", {}).get(name, default))

    def static_mask(self, name, default):
        """The instance chain's mask, if it states one (None: it doesn't)."""
        m = self.entry.get("masks", {}).get(name)
        return tuple(m) if m else None

    def guess_mask(self, name, default, v):
        """A channel mask the instance doesn't state (its editor-only data, where UE 5 keeps the
        choice, missing from the game files). When its default channel
        is empty in the one texture behind it and another channel isn't, the
        artist picked that one (Dark Shield's cube mask: R empty, G painted)."""
        name = name or "(unnamed)"
        on = [i for i, b in enumerate(default[:3]) if b]
        sock = getattr(v, "s", None) if v is not None and not v.const else None
        # UV-offset masks shift an effect rather than place it: never guessed
        if len(on) != 1 or not hasattr(sock, "node") or "offset" in name.lower():
            return None
        images = self._images_upstream(sock)
        if len(images) != 1:
            return None
        # from here the choice depends on the texture's pixels: another instance's may differ
        self.reusable = False
        means = self._channel_means(images[0])
        if means is None or means[on[0]] > 0.003:
            return None
        best = max(range(3), key=lambda i: means[i])
        if means[best] < 0.02:
            return None
        # one painted channel places one effect: the first mask reaching it takes it
        # (another effect left on its empty default channel was likely unused)
        claim = (images[0].name, best)
        if self._claimed.setdefault(claim, name) != name:
            return None
        self.note("channel mask %s: the instance's choice isn't in cooked data; %s is empty in %s, %s used" % (
            name.strip(), "RGB"[on[0]], images[0].name, "RGB"[best]))
        return tuple(i == best for i in range(4))

    @staticmethod
    def _images_upstream(sock, limit=400):
        """The images a socket's value comes from, within its tree."""
        seen, found, todo = set(), [], [sock.node]
        while todo and len(seen) < limit:
            n = todo.pop()
            if n.name in seen:
                continue
            seen.add(n.name)
            if n.bl_idname == "ShaderNodeTexImage" and n.image is not None:
                if n.image not in found:
                    found.append(n.image)
                continue
            img = bpy.data.images.get(n.get("mp_image", "")) if n.bl_idname == "NodeEvaluateClosure" else None
            if img is not None:
                # a texture read through its closure (Translator.sample_node)
                if img not in found:
                    found.append(img)
                continue
            for i in n.inputs:
                for l in i.links:
                    todo.append(l.from_node)
        return found

    _means = {}

    @classmethod
    def _channel_means(cls, img):
        """R, G, B coverage of an image (a sparse sample), cached."""
        if img.name not in cls._means:
            try:
                import numpy as np
                px = np.empty(len(img.pixels), dtype=np.float32)
                img.pixels.foreach_get(px)
                cls._means[img.name] = tuple(float(x) for x in px.reshape(-1, 4)[::7, :3].mean(axis=0))
            except Exception:
                cls._means[img.name] = None
        return cls._means[img.name]

    def texture_parameter(self, name, default):
        key = self.entry.get("textures", {}).get(name, default)
        self.tex_params.setdefault(key, set()).add(name)
        self.tex_default.setdefault(name, default)
        return key

    def collection(self, name, path=None):
        """A material parameter collection's value for `name`: through the file's group of that
        collection, which a time of day makes follow its hour where its day sequence keys it."""
        if not path:
            self.note("collection parameter %s without its collection: 0" % name)
            return self.tr.const(0.0)
        c = self.app.collection(path)
        for kind in ("scalars", "vectors"):
            if name in c.get(kind, {}):
                default = float(c[kind][name]) if kind == "scalars" else tuple(c[kind][name])
                # without a time of day in the file a collection only holds its defaults (the
                # sun's direction aside: it follows the scene's lamp) - folded in as values, what
                # reads them folds away too (a character's TODColor Adjustment, Scalar Time of Day)
                if name not in world.LIVE and not world.has_day():
                    return self.tr.const(default)
                return world.collection(self.tr, path, name, default)
        self.note("collection %s has no %s: 0" % (path.split("/")[-1], name))
        return self.tr.const(0.0)

    # ------------------------------------------------------------ assets
    def function(self, name, objpath=None):
        return self.app.graph(objpath or name)

    def special_function(self, name, inputs):
        return None

    def _record(self, key):
        try:
            return self.app.texture(key)
        except Exception as e:
            self.note("texture %s: %s" % (key.split("/")[-1], e))
            return None

    def _image(self, key, rec, data=None):
        if key in self._images:
            return self._images[key]
        img = None
        if rec is not None:
            img = _load(rec["File"], int(rec.get("Width") or 0), int(rec.get("Height") or 0))
            short = key.rsplit("/", 1)[-1].split(".")[0]
            if not img.name.startswith(short):
                img.name = short
            srgb = rec.get("Srgb") and not rec.get("Hdr")
            if data is not None:
                srgb = srgb and data != "normal"
            space = COLORSPACE_SRGB if srgb else COLORSPACE_DATA
            try:
                # setting it (even to what it is) makes Blender refresh the image
                if img.colorspace_settings.name != space:
                    img.colorspace_settings.name = space
            except TypeError:
                pass
            # UE reads alpha as its own channel; Blender's default (straight alpha,
            # premultiplied inside) loses a texel's colour where its alpha is 0 - the
            # LEGO colour LUT (alpha: metallic, 0 for nearly all colours) read black
            if img.alpha_mode != 'CHANNEL_PACKED':
                img.alpha_mode = 'CHANNEL_PACKED'
        if img is None:
            img = bpy.data.images.get("MP missing") or bpy.data.images.new("MP missing", 4, 4)
        self._images[key] = img
        return img

    def texture(self, key, sampler):
        normal = "Normal" in str(sampler)
        if normal:
            self.tex_normal.add(key)
        return self._image(key, self._record(key), "normal" if normal else None)

    # a skinned mesh's importer turns on Object.add_rest_position_attribute: its vertices before
    # the armature (and shape keys) moved them, as the "rest_position" attribute
    REST_POSITION = "rest_position"

    def local_position(self):
        """UE's LocalPosition, and its PreSkinnedPosition: on a skinned mesh both are the vertex in
        the reference pose (the GPU skin vertex factory's unskinned position; a LEGO face's
        front/back and left/right print masks, saturate(position + 0.5), stay on the head while
        the figure sits or leans) - the "rest_position" attribute its importer keeps. Elsewhere
        (a static mesh, an object imported without it) the object-space position."""
        tr = self.tr

        def make():
            tc = tr.shared("texcoord", lambda: tr.node("ShaderNodeTexCoord", "texture coordinate"))
            local = tr.from_blender(Val(tc.outputs["Object"], 3), point=True)
            n = tr.node("ShaderNodeAttribute", "rest position")
            n.attribute_type = 'GEOMETRY'
            n.attribute_name = self.REST_POSITION
            raw = Val(n.outputs["Vector"], 3)
            has = tr.binop('GREATER_THAN', tr.vmath('LENGTH', raw), tr.const(1e-9), label="has rest position")
            return tr.lerp(local, tr.from_blender(raw, point=True), has, label="local position (reference pose)")
        return self.once("local position", make)

    def preskinned_position(self):
        return self.local_position()

    def texture_address(self, key):
        """UE's addressing of a texture per axis (the app's record: AddressX, AddressY)."""
        rec = self._record(key)
        if not rec:
            return ("Wrap", "Wrap")
        return (rec.get("AddressX") or "Wrap", rec.get("AddressY") or "Wrap")

    def texture_nearest(self, key):
        """Whether UE samples the texture unfiltered (the app's record: its Filter TF_Nearest)."""
        rec = self._record(key)
        return bool(rec and rec.get("Nearest"))

    def cube(self, key):
        self.reusable = False
        self.note("cube texture %s read as a flat image" % key.split("/")[-1])
        return self._image(key, self._record(key))

    def volume(self, key):
        self.reusable = False
        rec = self._record(key)
        img = self._image(key, rec)
        if rec is None:
            return img, 1, 1
        return img, int(rec.get("Width", 1)), int(rec.get("Depth", 1))

    def texture_slices(self, key, sampler):
        """A texture array: the app exports it as a stack of slices (slice 0 on
        top); each becomes an image of its own."""
        self.reusable = False
        rec = self._record(key)
        if rec is None or rec.get("Kind") != "array" or int(rec.get("Depth", 1)) < 2:
            return None
        stack = self._image(key, rec)
        w, h = stack.size
        depth = int(rec["Depth"])
        sh = h // depth
        px = list(stack.pixels[:])
        out = []
        for i in range(depth):
            name = "%s [%d]" % (key.split("/")[-1].split(".")[0], i)
            img = bpy.data.images.get(name) or bpy.data.images.new(name, w, sh, alpha=True, float_buffer=stack.is_float)
            img.alpha_mode = 'CHANNEL_PACKED'     # alpha is data, as in UE (see _image)
            # Blender's pixel rows run bottom up: slice 0 (the top) is the last rows
            top = h - (i + 1) * sh
            img.pixels[:] = px[top * w * 4:(top + sh) * w * 4]
            img.colorspace_settings.name = stack.colorspace_settings.name
            img.pack()
            out.append(img)
        return out
