# Generated by materialporter/tools/sync_fork.py from blender/material_porter/layout.py - edit it there.
"""Lays a built node group out as framed, left-to-right sections.

The builders used to place every node by a hand-typed coordinate, and as the
variants grew those coordinates drifted into one tangle. This pass throws them
away and derives the layout from the finished graph instead:

  * Every node carries the section the builder was in when it made it
    (nodelib's `sec()`). A section is a frame, nested the way its path is:
    "Reaper/Matcap UV" is a Matcap UV frame inside a Reaper frame.
  * Inside a frame the nodes are layered left to right by dataflow, ordered
    to keep wires from crossing and nudged so each wire runs as straight as
    its neighbours allow - the usual Sugiyama recipe. A frame is laid out
    before its parent and then placed there as one block, ports and all.
  * Pure input nodes (Group Input, Geometry, Texture Coordinate, the bundle
    split, ...) are copied into every frame that reads them - Blender's
    version of UE's local parameter nodes - so no wire crosses the whole
    graph just to fetch a socket.
  * Unused outputs are hidden, and nodes that no longer reach the output
    (the retired fade terms, kept on purpose - see sphere_only.simplify_fade)
    are parked in an "Unused" frame underneath.

It changes where nodes sit and what they draw, never what they compute. It
has to run last, after every insertion pass: those passes find their anchors
by label and by neighbour, and are gated by tree markers, so they never run
again on a group this has laid out.

Node sizes are an estimate: Blender only measures a node when it draws it,
and the build runs in the background. The table below was measured in a UI
session (tools/layout_measure.py) and is good to a few pixels.
"""
import colorsys
import zlib
from collections import Counter, defaultdict

from .nodelib import SECTION_KEY

UNUSED = "Unused"

# ------------------------------------------------------------------ metrics
# Height of a node with no visible sockets, by type (and data type where that
# changes the buttons drawn). Each visible socket row adds ROW; an unlinked
# vector input draws its three fields and adds VEC instead.
ROW = 22.4
VEC = 84.0
BASE_H = {
    "ShaderNodeMath": 81.6,
    ("ShaderNodeMix", "RGBA"): 131.2,
    ("ShaderNodeMix", "FLOAT"): 81.6,
    ("ShaderNodeMix", "VECTOR"): 106.4,
    ("ShaderNodeMapRange", "FLOAT"): 81.6,
    ("ShaderNodeMapRange", "FLOAT_VECTOR"): 106.4,
    "ShaderNodeVectorMath": 56.8,
    "ShaderNodeCombineColor": 54.4,
    "ShaderNodeSeparateColor": 54.4,
    "ShaderNodeCombineXYZ": 29.6,
    "ShaderNodeSeparateXYZ": 29.6,
    "NodeEvaluateClosure": 52.0,
    "ShaderNodeVectorTransform": 104.0,
    "ShaderNodeHueSaturation": 29.6,
    "ShaderNodeNormalMap": 128.8,
    "ShaderNodeTexWhiteNoise": 54.4,
    "NodeGroupInput": 17.6,
    "NodeGroupOutput": 26.4,
    "NodeSeparateBundle": 14.4,
    "NodeCombineBundle": 9.6,
    "ShaderNodeNewGeometry": 20.8,
    "ShaderNodeCameraData": 27.2,
    "ShaderNodeObjectInfo": 27.2,
    "ShaderNodeVectorRotate": 54.4,
    "ShaderNodeTexCoord": 76.8,
    "ShaderNodeValue": 27.2,
    "ShaderNodeUVMap": 81.6,
    "ShaderNodeTangent": 81.6,
    "ShaderNodeRGB": 128.8,
    "ShaderNodeTexVoronoi": 123.2,
    "ShaderNodeRGBToBW": 29.6,
    "ShaderNodeGamma": 3.2,
    "GeometryNodeMenuSwitch": 60.0,
    "NodeReroute": 0.0,
    # the sky's (tools/build_sky.py, build_fog.py, build_grade.py): estimates
    # on the generous side, since a gap reads better than an overlap
    "ShaderNodeFloatCurve": 262.0,
    "ShaderNodeTexImage": 206.0,
    "ShaderNodeAttribute": 58.0,
    "ShaderNodeVertexColor": 32.0,
    "ShaderNodeGroup": 32.0,
}
BASE_DEFAULT = 60.0
HEAD = 24.0     # node top to the first output row
FOOT = 6.0      # last input row to the node bottom

# frames: Blender draws a shrink-wrapped frame this far outside its children,
# plus the label on top. Kept a little generous so a drawn frame never
# reaches into its neighbour.
PAD = 34.0
LABEL = {1: 34, 2: 22}          # label_size by depth; deeper reuses the last
GAP_NODE_Y = 30.0
GAP_BOX_Y = 70.0
GAP_DUMMY_Y = 12.0
GAP_LANE_BOX = 30.0      # a lane or a loose node beside a frame
BUS_MIN = 60.0           # a wire that climbs less than this stays a plain wire
BUS_SNAP = 24.0          # bus taps closer than this merge
BUS_PAD = 40.0           # first bus this far into the gap
BUS_STEP = 24.0          # buses side by side in one gap
LANE_LIMIT = 1500        # reroutes a tree's lanes may make; past it, plain wires (each new node costs Blender a pass over the tree)
# Wires between frames as reroute buses (UE's wiring). Off: a material's dozens of
# parallel wires became ladders of reroute dots, harder to follow than the wires
ROUTE_BUSES = False
GAP_NODE_X = 45.0
GAP_BOX_X = 100.0

# Frame colours by top-level section. Anything not listed gets a stable hue
# from its name; sub-frames are a lighter shade of their parent.
PALETTE = {
    "Common": (0.20, 0.20, 0.22),
    "Golden": (0.40, 0.30, 0.07),
    "Shared · Cube Base": (0.10, 0.24, 0.23),
    "Cube": (0.08, 0.30, 0.27),
    "Shared · Billboard Plane": (0.16, 0.19, 0.28),
    "CheatMaster": (0.10, 0.30, 0.10),
    "LootHacker": (0.25, 0.12, 0.36),
    "Reaper": (0.07, 0.11, 0.30),
    "Galaxy": (0.22, 0.09, 0.32),
    "Gem": (0.04, 0.27, 0.35),
    "Holofoil": (0.35, 0.14, 0.30),
    "Quack": (0.36, 0.33, 0.06),
    "Candy": (0.40, 0.11, 0.19),
    "Variant Switch": (0.22, 0.22, 0.24),
    "Variant Fade": (0.26, 0.18, 0.11),
    "Output": (0.18, 0.18, 0.18),
    UNUSED: (0.10, 0.10, 0.10),
}

# Nodes with nothing but outputs whose value does not depend on where they
# sit, so a copy is the same node. Value and RGB are not here: those hold a
# number someone may edit, and editing one copy of it would be a trap. The
# scene-time Value is the exception and is recognised by its driver.
PURE_SOURCES = {
    "NodeGroupInput": (),
    "ShaderNodeNewGeometry": (),
    "ShaderNodeTexCoord": ("object", "from_instancer"),
    "ShaderNodeCameraData": (),
    "ShaderNodeObjectInfo": (),
    "ShaderNodeUVMap": ("uv_map", "from_instancer"),
    "ShaderNodeTangent": ("direction_type", "axis", "uv_map"),
    # a scene value (the hour, Time of Day, a slider) or the dome's paint
    "ShaderNodeAttribute": ("attribute_type", "attribute_name"),
    "ShaderNodeVertexColor": ("layer_name",),
}


# ------------------------------------------------------------------ sizes
def _vis(s):
    return s.enabled and not s.hide


def _tall(s):
    return s.type == 'VECTOR' and not s.is_linked and not s.hide_value


def _base(n):
    if STAND_IN in n:
        return BASE_H["NodeGroupInput"]
    key = (n.bl_idname, getattr(n, "data_type", None))
    if key in BASE_H:
        return BASE_H[key]
    return BASE_H.get(n.bl_idname, BASE_DEFAULT)


HIDDEN_H = 26.0     # a collapsed node: its header only


def node_height(n):
    if n.bl_idname == "NodeReroute":
        return 16.0
    if n.hide:
        return HIDDEN_H
    rows = sum(ROW for s in n.outputs if _vis(s))
    rows += sum(VEC if _tall(s) else ROW for s in n.inputs if _vis(s))
    return _base(n) + rows


def node_width(n):
    return 16.0 if n.bl_idname == "NodeReroute" else float(n.width)


def socket_offset(n, sock):
    """Distance from the node's top edge down to a socket's centre."""
    if n.bl_idname == "NodeReroute":
        return 8.0
    if n.hide:
        return HIDDEN_H * 0.5
    if sock.is_output:
        i = 0
        for s in n.outputs:
            if s == sock:
                return HEAD + ROW * (i + 0.5)
            if _vis(s):
                i += 1
        return HEAD
    below = 0.0
    h = node_height(n)
    for s in reversed(list(n.inputs)):
        if not _vis(s) and s != sock:
            continue
        r = VEC if _tall(s) else ROW
        if s == sock:
            return h - FOOT - below - r + ROW * 0.5
        below += r
    return h * 0.5


# ------------------------------------------------------------------ links
# Blender answers `socket.links` by walking every link in the tree, and any
# read after a link edit makes it rebuild its topology cache first. On the
# Variants group that turns a few thousand reads into a minute. So the links
# are read once into plain records, the passes below work on those, and each
# pass writes its edits back in one go.
#
# Sockets are kept by identifier, not by handle: a reroute rebuilds its
# sockets when the first link gives it a type, and a handle taken before that
# points at freed memory.
class _Wire:
    __slots__ = ("link", "a", "ia", "type", "b", "ib")

    def __init__(self, link, a, ia, type_, b, ib):
        self.link, self.a, self.ia, self.type, self.b, self.ib = link, a, ia, type_, b, ib


def _out(node, ident):
    return next(s for s in node.outputs if s.identifier == ident)


def _in(node, ident):
    return next(s for s in node.inputs if s.identifier == ident)


def _scan(tree):
    wires = []
    for l in tree.links:
        sa = l.from_socket
        wires.append(_Wire(l, l.from_node, sa.identifier, sa.type,
                           l.to_node, l.to_socket.identifier))
    return wires


def _adjacency(wires):
    ins, outs = defaultdict(list), defaultdict(list)
    for w in wires:
        outs[w.a.name].append(w)
        ins[w.b.name].append(w)
    return ins, outs


# ------------------------------------------------------------------ tags
def _read_tags(tree):
    tags = {}
    for n in tree.nodes:
        if n.bl_idname == "NodeFrame":
            continue
        raw = n.get(SECTION_KEY)
        tags[n.name] = None if raw is None else tuple(p for p in raw.split("/") if p)
    return tags


def _is_source(n, ins):
    if n.bl_idname in PURE_SOURCES:
        return True
    if n.bl_idname == "NodeSeparateBundle":
        feeds = ins.get(n.name, [])
        return bool(feeds) and all(w.a.type == 'GROUP_INPUT' for w in feeds)
    return n.bl_idname == "ShaderNodeValue" and _driver(n) is not None


def _resolve_untagged(tree, tags, wires):
    """Nodes an insertion pass added after the builder finished.

    They go with the node they read from, which is where every pass inserts:
    the mirror after the object-space read, the grade after the variant
    colour, the cell variation after the LootHacker base.
    """
    ins, outs = _adjacency(wires)
    pending = [n for n in tree.nodes if n.name in tags and tags[n.name] is None]
    while pending:
        rest, moved = [], False
        for n in pending:
            votes = Counter()
            for w in ins[n.name]:
                t = tags.get(w.a.name)
                if t is not None and not _is_source(w.a, ins):
                    votes[t] += 2
            for w in outs[n.name]:
                t = tags.get(w.b.name)
                if t is not None:
                    votes[t] += 1
            if votes:
                tags[n.name] = votes.most_common(1)[0][0]
                moved = True
            else:
                rest.append(n)
        if not moved:
            for n in rest:
                tags[n.name] = ()
            break
        pending = rest


def _park_dead(tree, tags, wires):
    """Tag whatever no longer reaches the output into the Unused frame."""
    ins, _ = _adjacency(wires)
    live = set()
    stack = [n.name for n in tree.nodes if n.type in ('GROUP_OUTPUT', 'OUTPUT_MATERIAL')]
    while stack:
        name = stack.pop()
        if name in live:
            continue
        live.add(name)
        stack.extend(w.a.name for w in ins[name])
    parked = 0
    for n in tree.nodes:
        if n.name not in tags or n.name in live or n.type == 'GROUP_INPUT':
            continue
        top = tags[n.name][0] if tags[n.name] else "Misc"
        tags[n.name] = (UNUSED, top)
        parked += 1
    return parked


# ------------------------------------------------------------------ sources
def _driver(n):
    ad = n.id_data.animation_data
    if ad is None:
        return None
    path = 'nodes["%s"].outputs[0].default_value' % n.name
    return next((fc for fc in ad.drivers if fc.data_path == path), None)


def _clone(tree, src):
    c = tree.nodes.new(src.bl_idname)
    c.label = src.label
    c.width = src.width
    for prop in PURE_SOURCES.get(src.bl_idname, ()):
        setattr(c, prop, getattr(src, prop))
    if src.bl_idname == "NodeSeparateBundle":
        c.bundle_items.clear()
        for it in src.bundle_items:
            c.bundle_items.new(it.socket_type, it.name)
        c.define_signature = src.define_signature
    if src.bl_idname == "ShaderNodeValue":
        c.outputs[0].default_value = src.outputs[0].default_value
        old = _driver(src)
        fc = c.outputs[0].driver_add("default_value")
        fc.driver.type = old.driver.type
        fc.driver.expression = old.driver.expression
        for v in old.driver.variables:
            nv = fc.driver.variables.new()
            nv.name, nv.type = v.name, v.type
            for i, t in enumerate(v.targets):
                nt = nv.targets[i]
                if v.type == 'SINGLE_PROP':
                    nt.id_type = t.id_type
                nt.id = t.id
                nt.data_path = t.data_path
    return c


def _key(n):
    props = tuple(str(getattr(n, p)) for p in PURE_SOURCES.get(n.bl_idname, ()))
    if n.bl_idname == "ShaderNodeValue":
        props = (_driver(n).driver.expression,)
    if n.bl_idname == "NodeSeparateBundle":
        props = tuple((it.name, it.socket_type) for it in n.bundle_items)
    return (n.bl_idname, props)


def _relink(tree, a, ia, b, ib):
    """Point input `ib` of `b` at output `ia` of `a`.

    A new link into a single input replaces the one already there, which
    saves the separate remove - every edit costs Blender a tree update.
    """
    sb = _in(b, ib)
    if sb.is_multi_input:
        for l in [l for l in tree.links if l.to_socket == sb]:
            tree.links.remove(l)
    return tree.links.new(_out(a, ia), sb)


# A Group Input carries every interface socket - 361 on the Variants group -
# and the cost of any link edit grows with the sockets in the tree. A hundred
# copies of it make every later edit ten times slower. So until the last edit
# is done a copy is stood in for by a Separate Bundle holding only the outputs
# that copy will show, drawn the same height and in the same order, and the
# real Group Input replaces it at the very end (_realize_inputs).
STAND_IN = "fpv4_group_input"


def _out_of(node, ident, stand_ins):
    """Output `ident` of a node, or of the Group Input a stand-in stands for."""
    idents = stand_ins.get(node.name)
    if idents is None:
        return _out(node, ident)
    outs = [s for s in node.outputs if s.identifier != "__extend__"]
    if ident in idents:
        return outs[idents.index(ident)]
    # Wires scanned after localizing name the stand-in's own outputs (Item_N),
    # not the Group Input's (Socket_N). A lane routed out of a stand-in into a
    # nested frame arrives here with one of those; the two never collide.
    return _out(node, ident)


def _stand_in(tree, gi, idents):
    ph = tree.nodes.new("NodeSeparateBundle")
    ph.bundle_items.clear()
    kept = []
    for s in gi.outputs:
        if s.identifier in idents:
            kind = {'VALUE': 'FLOAT', 'CUSTOM': 'FLOAT'}.get(s.type, s.type)
            ph.bundle_items.new(kind, s.name or s.identifier)
            kept.append(s.identifier)
    ph[STAND_IN] = 1
    ph.width = gi.width
    return ph, kept


def _localize_sources(tree, tags, wires):
    """Copy every pure input node into each frame that reads it - and a Group
    Input to each node that reads it, showing only what that node reads: a
    parameter sits beside its reader, where one Group Input feeding a whole
    frame sent dozens of wires across it.

    Returns (copies made, {stand-in name: Group Input output ids}).
    """
    ins, outs = _adjacency(wires)
    order = sorted((n for n in tree.nodes if n.name in tags and _is_source(n, ins)),
                   key=lambda n: 0 if n.bl_idname == "NodeSeparateBundle" else 1)
    sources = {n.name for n in order}
    # what each frame (or reader) will read from each source, so a stand-in can
    # be made with exactly those outputs; key (source, path, reader or None)
    stays, moves = set(), defaultdict(list)
    for src in order:
        own = tags[src.name]
        for w in outs[src.name]:
            if src.type == 'GROUP_INPUT' and w.b.name not in sources:
                moves[(src.name, tags[w.b.name], w.b.name)].append(w)
            elif tags[w.b.name] == own:
                stays.add(src.name)
            else:
                moves[(src.name, tags[w.b.name], None)].append(w)
    # the reader taking most of a Group Input's wires keeps the original
    best = {}
    for k, group in moves.items():
        if k[2] is not None and len(group) > len(moves.get(best.get(k[0]), ())):
            best[k[0]] = k
    for name, k in best.items():
        if name not in stays:
            stays.add(name)
            tags[name] = k[1]
            del moves[k]
    needs = defaultdict(set)
    for (name, path, reader), group in moves.items():
        src = tree.nodes[name]
        if src.type == 'GROUP_INPUT':
            needs[(_key(src), path, reader)].update(w.ia for w in group)
        elif src.bl_idname == "NodeSeparateBundle":
            feed = ins[name][0]
            needs[(_key(feed.a), path, None)].add(feed.ia)

    local, stand_ins = {}, {}

    def copy_in(src, path, reader=None):
        k = (_key(src), path, reader)
        if k not in local:
            if src.type == 'GROUP_INPUT':
                c, stand_ins_ids = _stand_in(tree, src, needs[k])
                stand_ins[c.name] = stand_ins_ids
            else:
                c = _clone(tree, src)
            tags[c.name] = path
            local[k] = c
            if src.bl_idname == "NodeSeparateBundle":
                feed = ins[src.name][0]
                gi = copy_in(feed.a, path)
                tree.links.new(_out_of(gi, feed.ia, stand_ins), c.inputs[0])
        return local[k]

    for (name, path, reader), group in moves.items():
        c = copy_in(tree.nodes[name], path, reader)
        for w in group:
            sb = _in(w.b, w.ib)
            tree.links.new(_out_of(c, w.ia, stand_ins), sb)
    # an original nothing reads any more is only clutter - but keep the
    # first Group Input, which older code looks the interface up through (a
    # material's own tree has none)
    keep = next((n for n in tree.nodes if n.type == 'GROUP_INPUT'), None)
    for src in order:
        if src != keep and src.name not in stays:
            del tags[src.name]
            tree.nodes.remove(src)
    return len(local), stand_ins


def _realize_inputs(tree, stand_ins):
    """Swap every stand-in for the Group Input it stands for."""
    N = tree.nodes
    feeds = defaultdict(list)
    for w in _scan(tree):
        if w.a.name in stand_ins:
            feeds[w.a.name].append(w)
    for name, idents in stand_ins.items():
        ph = N[name]
        gi = N.new("NodeGroupInput")
        gi.parent = ph.parent
        gi.location_absolute = ph.location_absolute
        for s in gi.outputs:
            s.hide = s.identifier not in idents
        outs = [s.identifier for s in ph.outputs if s.identifier != "__extend__"]
        for w in feeds[name]:
            _relink(tree, gi, idents[outs.index(w.ia)], w.b, w.ib)
        N.remove(ph)


# ------------------------------------------------------------------ ports
PORT_TYPES = {'VALUE', 'VECTOR', 'RGBA', 'INT', 'BOOLEAN'}
PORT_MARK = "▸ "
EXIT_MARK = " ▸"


def _port_name(node, src):
    """What a port shows: its source's label, marked, so that nothing that
    looks nodes up by exact label - the passes, the tests - ever takes a port
    for the node it carries."""
    name = node.label or node.name
    if name.startswith(PORT_MARK):
        name = name[len(PORT_MARK):]
    if name.endswith(EXIT_MARK):
        name = name[:-len(EXIT_MARK)]
    if node.bl_idname != "NodeReroute" and sum(1 for o in node.outputs if o.enabled) > 1:
        name += " · " + src.name
    return name


def _ports(tree, tags, wires):
    """Reroutes where a signal crosses a frame's edge, UE comment-box style.

    Exits first, inside out. A value made deep inside a frame and read
    outside it would otherwise leave from wherever its node sits and cut
    across the rest of the frame on its way out; when the part that makes it
    also feeds something else in the frame - so the layering cannot put it on
    the frame's right edge by itself - it goes out through a reroute that
    does sit there.

    Then entries, outside in. A value read by several nodes inside a frame
    arrives as one wire, to a labelled reroute on the frame's left edge, and
    fans out from there instead of arriving as one long wire per reader. So
    does a value read by one node that sits behind something else in the
    frame. A sub-frame gets its own entry, fed from its parent's.

    Pure inputs get neither - they are about to be copied into the frame.
    This runs before those copies exist, while a link edit is still cheap.
    Returns {reroute name: "first" | "last"}, the column each one is pinned to.
    """
    L = tree.links
    pins = {}
    ins, _ = _adjacency(wires)
    live = [w for w in wires if not _is_source(w.a, ins)]
    paths = {p[:k] for p in tags.values() if p for k in range(1, len(p) + 1)}
    paths = [p for p in paths if p[0] != UNUSED]

    def item(path, depth, node):
        return path[depth] if len(path) > depth else node.name

    def reroute(path, label, pin):
        r = tree.nodes.new("NodeReroute")
        r.label = label
        tags[r.name] = path
        pins[r.name] = pin
        return r

    def carry(group, r):
        """Feed `r` from the group's source and the group's readers from `r`."""
        node, ia, type_ = group[0].a, group[0].ia, group[0].type
        link = L.new(_out(node, ia), r.inputs[0])
        made = [_Wire(link, node, ia, type_, r, link.to_socket.identifier)]
        r_out = r.outputs[0].identifier
        for w in group:
            link = _relink(tree, r, r_out, w.b, w.ib)
            made.append(_Wire(link, r, r_out, type_, w.b, w.ib))
        return made

    for path in sorted(paths, key=lambda p: (-len(p), p)):
        depth = len(path)
        busy, groups = set(), defaultdict(list)
        for w in live:
            pu, pv = tags[w.a.name], tags[w.b.name]
            if pu[:depth] != path:
                continue
            if pv[:depth] == path:
                if item(pu, depth, w.a) != item(pv, depth, w.b):
                    busy.add(item(pu, depth, w.a))
            elif w.type in PORT_TYPES:
                groups[(w.a.name, w.ia)].append(w)
        gone, made = set(), []
        for group in groups.values():
            if item(tags[group[0].a.name], depth, group[0].a) not in busy:
                continue
            src = _out(group[0].a, group[0].ia)
            r = reroute(path, _port_name(group[0].a, src) + EXIT_MARK, "last")
            gone.update(id(w) for w in group)
            made += carry(group, r)
        live = [w for w in live if id(w) not in gone] + made

    for path in sorted(paths, key=lambda p: (len(p), p)):
        depth = len(path)
        fed, groups = set(), defaultdict(list)
        for w in live:
            pu, pv = tags[w.a.name], tags[w.b.name]
            if pv[:depth] != path:
                continue
            if pu[:depth] == path:
                if item(pu, depth, w.a) != item(pv, depth, w.b):
                    fed.add(item(pv, depth, w.b))
                continue
            if pu[:1] == (UNUSED,) or w.type not in PORT_TYPES:
                continue
            groups[(w.a.name, w.ia)].append(w)
        gone, made = set(), []
        for group in groups.values():
            # one reader on the frame's left edge can take the wire directly;
            # one further in would have it cross whatever sits in front
            deep = any(item(tags[w.b.name], depth, w.b) in fed for w in group)
            if len(group) < 2 and not deep:
                continue
            src = _out(group[0].a, group[0].ia)
            r = reroute(path, PORT_MARK + _port_name(group[0].a, src), "first")
            gone.update(id(w) for w in group)
            made += carry(group, r)
        live = [w for w in live if id(w) not in gone] + made
    return pins


# Nodes whose whole content is their wiring, when every input is wired: drawn collapsed
# (a row each), they stop taking the height of their socket list. A Separate/Combine Color in
# another mode than RGB keeps its mode on show, a node with a value typed in keeps it.
COLLAPSIBLE = {"ShaderNodeSeparateXYZ", "ShaderNodeCombineXYZ", "ShaderNodeSeparateColor",
               "ShaderNodeCombineColor", "NodeEvaluateClosure"}


def _collapse_trivial(tree, wires):
    fed = {(w.b.name, w.ib) for w in wires}
    for n in tree.nodes:
        if n.bl_idname not in COLLAPSIBLE or getattr(n, "mode", 'RGB') != 'RGB':
            continue
        if all((n.name, s.identifier) in fed for s in n.inputs if s.enabled and s.identifier != "__extend__"):
            n.hide = True


def _hide_unused_outputs(tree, wires):
    used = {(w.a.name, w.ia) for w in wires}
    for n in tree.nodes:
        if n.bl_idname in ("NodeFrame", "NodeReroute", "NodeGroupOutput"):
            continue
        outs = [s for s in n.outputs if s.enabled]
        if len(outs) < 2 and n.type != 'GROUP_INPUT':
            continue
        for s in outs:
            s.hide = (n.name, s.identifier) not in used


# ------------------------------------------------------------------ boxes
class Box:
    def __init__(self, path, parent):
        self.path = path
        self.parent = parent
        self.kids = {}
        self.nodes = []
        self.links = []
        self.x = self.y = 0.0
        self.w = self.h = 0.0
        self.off = {}                             # node name -> y below our top
        self.rel = {}                             # own node name -> (x, y) in content
        self.lanes = []
        self.order = 0

    @property
    def depth(self):
        return len(self.path)

    def pad_top(self):
        if not self.path:
            return 0.0
        return PAD + LABEL.get(self.depth, LABEL[2]) * 1.4

    def pad_side(self):
        return PAD if self.path else 0.0


def _build_boxes(tree, tags):
    root = Box((), None)
    index = {}
    for i, n in enumerate(tree.nodes):
        if n.name not in tags:
            continue
        index[n.name] = i
        b = root
        for d, part in enumerate(tags[n.name]):
            if part not in b.kids:
                b.kids[part] = Box(tags[n.name][:d + 1], b)
                b.kids[part].order = i
            b = b.kids[part]
        b.nodes.append(n)
    for link in tree.links:
        pu, pv = tags.get(link.from_node.name), tags.get(link.to_node.name)
        if pu is None or pv is None:
            continue
        k = 0
        while k < min(len(pu), len(pv)) and pu[k] == pv[k]:
            k += 1
        b = root
        for part in pu[:k]:
            b = b.kids[part]
        b.links.append((link, pu, pv, k))
    return root, index


# ------------------------------------------------------------------ sugiyama
class _It:
    __slots__ = ("key", "kind", "obj", "w", "h", "x", "y", "layer", "pos",
                 "order", "pin", "dot")

    def __init__(self, key, kind, obj, w, h, order, pin=False):
        self.key, self.kind, self.obj = key, kind, obj
        self.w, self.h = w, h
        self.x = self.y = 0.0
        self.layer = 0
        self.pos = 0.0
        self.order = order
        self.pin = pin
        # a reroute: its wire goes straight through, so it lines up by socket
        # rather than by top edge. Lanes line up by top edge like the nodes
        # they run beside - mixing the two lets a chain creep a socket's
        # height per sweep until it has drifted away from its neighbours.
        self.dot = kind == "node" and obj.bl_idname == "NodeReroute"


def _vgap(a, b):
    if a.kind == "box" and b.kind == "box":
        return GAP_BOX_Y
    if a.kind == "box" or b.kind == "box":
        return GAP_LANE_BOX
    if a.dot or b.dot or a.kind == "dummy" or b.kind == "dummy":
        return GAP_DUMMY_Y
    return GAP_NODE_Y


def _wmedian(cands):
    cands.sort()
    total = sum(w for _, w in cands)
    acc = 0.0
    for v, w in cands:
        acc += w
        if acc >= total * 0.5:
            return v
    return cands[-1][0]


def _settle(col, desired, weight):
    """Closest positions to `desired` that keep `col`'s order and gaps.

    Weighted isotonic regression (pool adjacent violators) on y minus each
    item's cumulative minimum offset from the top of the column.
    """
    n = len(col)
    c = [0.0] * n
    for i in range(1, n):
        c[i] = c[i - 1] + col[i - 1].h + _vgap(col[i - 1], col[i])
    blocks = []
    for i in range(n):
        blocks.append([desired[i] - c[i], weight[i], 1])
        while len(blocks) > 1 and blocks[-2][0] > blocks[-1][0]:
            t2, w2, n2 = blocks.pop()
            t1, w1, n1 = blocks.pop()
            blocks.append([(t1 * w1 + t2 * w2) / (w1 + w2), w1 + w2, n1 + n2])
    i = 0
    for t, _, k in blocks:
        for _ in range(k):
            col[i].y = t + c[i]
            i += 1


def _crossings(segs):
    """Pairs of (a, b) segments that cross: a Fenwick-tree inversion count."""
    if len(segs) < 2:
        return 0
    segs = sorted(segs)
    ranks = {v: i + 1 for i, v in enumerate(sorted({b for _, b in segs}))}
    tree = [0] * (len(ranks) + 1)
    count = 0
    for seen, (_, b) in enumerate(segs):
        r = ranks[b]
        # how many already placed have a larger b
        i, le = r, 0
        while i > 0:
            le += tree[i]
            i -= i & -i
        count += seen - le
        i = r
        while i < len(tree):
            tree[i] += 1
            i += i & -i
    return count


def _sugiyama(items, edges):
    """Place `items`, x and y relative to the block's top-left.

    edges: (u, v, u_port, v_port, weight, wire) with ports measured from each
    item's top edge and wire = (from node, output id, to node, input id).

    Returns (w, h, routes): the reroutes that carry wires between frames,
    each (source node, output id, [(x, y) per reroute], [(i, j) links between
    them], [(reader node, input id, i)]), with i = -1 for the source itself.
    """
    if not items:
        return 0.0, 0.0, []
    # --- break cycles (frames can feed each other both ways)
    succ = defaultdict(list)
    for e in edges:
        succ[id(e[0])].append(e[1])
    state, back = {}, set()
    for root in sorted(items, key=lambda it: it.order):
        if id(root) in state:
            continue
        stack = [(root, iter(succ[id(root)]))]
        state[id(root)] = 1
        while stack:
            u, it = stack[-1]
            v = next(it, None)
            if v is None:
                state[id(u)] = 2
                stack.pop()
                continue
            s = state.get(id(v))
            if s == 1:
                back.add((id(u), id(v)))
            elif s is None:
                state[id(v)] = 1
                stack.append((v, iter(succ[id(v)])))
    dag = [e for e in edges if (id(e[0]), id(e[1])) not in back]

    # --- layers, as late as possible: sinks on the right, everything else
    # just before its nearest consumer. Entry and exit ports then get a column
    # of their own on the far left and far right, the frame's edges.
    out = defaultdict(set)
    for e in dag:
        out[id(e[0])].add(e[1])
    rank = {}
    for it in sorted(items, key=lambda it: it.order):
        stack = [it]
        while stack:
            u = stack[-1]
            if id(u) in rank:
                stack.pop()
                continue
            pending = [v for v in out[id(u)] if id(v) not in rank]
            if pending:
                stack.extend(pending)
                continue
            rank[id(u)] = 1 + max((rank[id(v)] for v in out[id(u)]), default=-1)
            stack.pop()
    top = max(rank.values())
    first = 1 if any(it.pin == "first" for it in items) else 0
    for it in items:
        if it.pin == "first":
            it.layer = 0
        elif it.pin == "last":
            it.layer = top + first + 1
        else:
            it.layer = top - rank[id(it)] + first
    layers = [[] for _ in range(max(it.layer for it in items) + 1)]
    for it in items:
        layers[it.layer].append(it)
    layers = [col for col in layers if col]
    for l, col in enumerate(layers):
        for it in col:
            it.layer = l

    # --- long edges become chains of dummies, one chain per source socket,
    # shared by every reader of it
    segs = []                                     # (a, b, pa, pb, w)
    trunks = {}                                   # source socket -> chain
    reads = defaultdict(list)                     # source socket -> [(v, wire)]
    for u, v, pu, pv, w, wire in dag:
        if v.layer <= u.layer:
            continue
        if v.layer == u.layer + 1:
            segs.append((u, v, pu, pv, w))
            continue
        key = (wire[0], wire[1])
        chain = trunks.setdefault(key, [u])
        reads[key].append((v, wire))
        while chain[-1].layer < v.layer - 1:
            prev = chain[-1]
            d = _It(None, "dummy", None, 0.0, 0.0, u.order)
            d.layer = prev.layer + 1
            layers[d.layer].append(d)
            segs.append((prev, d, pu if prev is u else 0.0, 0.0, 3.0))
            chain.append(d)
        last = chain[v.layer - u.layer - 1]
        segs.append((last, v, pu if last is u else 0.0, pv, w))

    ins, outs = defaultdict(list), defaultdict(list)
    for s in segs:
        outs[id(s[0])].append(s)
        ins[id(s[1])].append(s)

    # --- order within layers: barycentre sweeps from creation order. Frames
    # keep the order the builder made them in - Golden above CheatMaster above
    # LootHacker reads better than whatever minimises a crossing count - and
    # only nodes and lanes move around them.
    def reorder(col, key):
        boxes = sorted((it for it in col if it.kind == "box"), key=lambda it: it.order)
        col.sort(key=key)
        slots = [i for i, it in enumerate(col) if it.kind == "box"]
        for i, b in zip(slots, boxes):
            col[i] = b
        for i, it in enumerate(col):
            it.pos = i

    for col in layers:
        reorder(col, lambda it: it.order)

    def frac(it, port):
        return 0.99 * port / it.h if it.h > 0 else 0.0

    def count_all():
        total = 0
        for col in layers:
            total += _crossings([(a.pos + frac(a, pa), b.pos + frac(b, pb))
                                 for a in col for (_, b, pa, pb, _) in outs[id(a)]])
        return total

    best = count_all()
    snapshot = [list(col) for col in layers]
    for sweep in range(16):
        down = sweep % 2 == 0
        rng = range(1, len(layers)) if down else range(len(layers) - 2, -1, -1)
        for l in rng:
            keys = {}
            for it in layers[l]:
                nb = ([s[0].pos + frac(s[0], s[2]) for s in ins[id(it)]] if down else
                      [s[1].pos + frac(s[1], s[3]) for s in outs[id(it)]])
                keys[id(it)] = sum(nb) / len(nb) if nb else it.pos
            reorder(layers[l], lambda it: keys[id(it)])
        c = count_all()
        if c < best:
            best, snapshot = c, [list(col) for col in layers]
    layers = snapshot
    for col in layers:
        for i, it in enumerate(col):
            it.pos = i

    # --- y: stack, then pull every item level with what it connects to.
    # Level means top edges, not sockets: Blender draws a node's outputs above
    # its inputs, so lining sockets up makes every chain climb a step per node
    # and a long one ends up a diagonal. Tops keep chains in rows, and the
    # wires between them only dip by a socket or two. Reroutes and lanes are
    # the exception - a wire goes straight through them, so they line up by
    # socket. Frames do not chase anything: they stay stacked from the top of
    # their column, which packs them like a masonry wall instead of leaving
    # holes wherever two frames tried to line up with different neighbours.
    for col in layers:
        y = 0.0
        for i, it in enumerate(col):
            if i:
                y += col[i - 1].h + _vgap(col[i - 1], it)
            it.y = y

    def target(it, other, p_it, p_other):
        if it.dot or other.dot:
            return other.y + p_other - p_it
        return other.y

    def pull(col, downward):
        desired, weight = [], []
        for it in col:
            if it.kind == "box":
                desired.append(it.y)
                weight.append(1e6)
                continue
            if downward:
                cands = [(target(it, s[0], s[3], s[2]), s[4]) for s in ins[id(it)]]
            else:
                cands = [(target(it, s[1], s[2], s[3]), s[4]) for s in outs[id(it)]]
            if cands:
                desired.append(_wmedian(cands))
                weight.append(sum(w for _, w in cands))
            else:
                desired.append(it.y)
                weight.append(0.01)
        _settle(col, desired, weight)

    for _ in range(10):
        for l in range(1, len(layers)):
            pull(layers[l], True)
        for l in range(len(layers) - 2, -1, -1):
            pull(layers[l], False)
    for l in range(1, len(layers)):
        pull(layers[l], True)

    # close any band no column uses: two chains that share nothing can end up
    # far apart, and the frame would carry the empty stretch between them
    hole = GAP_BOX_Y if any(it.kind == "box" for it in items) else 2 * GAP_NODE_Y
    shift, bottom = 0.0, None
    for it in sorted((it for col in layers for it in col), key=lambda it: it.y):
        if bottom is not None and it.y - shift > bottom + hole:
            shift += it.y - shift - bottom - hole
        it.y -= shift
        bottom = it.y + it.h if bottom is None else max(bottom, it.y + it.h)

    real = [it for col in layers for it in col if it.kind != "dummy"]
    y0 = min(it.y for it in real)
    for col in layers:
        for it in col:
            it.y -= y0

    # --- routes, only at a level that holds frames. There a wire between two
    # columns can have thousands of pixels to climb, and drawn straight it
    # cuts across every frame in between. Instead it leaves its socket level,
    # drops down a vertical bus in the gap after its column and turns into its
    # reader level - UE's wiring, built from reroutes. A lane (the chain of
    # dummies of a long edge) needs no reroute of its own: the bus before it
    # and the bus after it sit at the same height, so the wire between them
    # is already a straight line through the gap it reserved. Inside a plain
    # node frame none of this is worth its reroutes.
    routes, buses = [], defaultdict(list)
    if ROUTE_BUSES and any(it.kind == "box" for it in items):
        nets = {}
        for u, v, pu, pv, w, wire in dag:
            if v.layer <= u.layer:
                continue
            net = nets.setdefault((wire[0], wire[1]), (u, pu, defaultdict(list)))
            net[2][v.layer].append((v, pv, wire))
        for key, (u, pu, reads) in nets.items():
            lane = {d.layer: d for d in trunks.get(key, [])[1:]}
            points, links, feeds = [], [], []
            cur, cur_y = -1, u.y + pu
            for g in range(u.layer, max(reads)):
                dests = [(v.y + pv, wire) for v, pv, wire in reads.get(g + 1, [])]
                if g + 1 in lane:
                    dests.append((lane[g + 1].y, None))
                far = sorted({y for y, _ in dests if abs(y - cur_y) > BUS_MIN})
                at = {}
                if far:
                    bus = [g, cur_y, 0]               # gap, height, lane slot
                    buses[g].append(bus)
                    first = len(points)
                    points.append((bus, cur_y))
                    links.append((cur, first))
                    for side in (sorted((y for y in far if y < cur_y), reverse=True),
                                 sorted(y for y in far if y > cur_y)):
                        prev, prev_y = first, cur_y
                        for y in side:
                            # readers a socket or so apart share one tap
                            if prev != first and abs(y - prev_y) <= BUS_SNAP:
                                at[y] = prev
                                continue
                            points.append((bus, y))
                            links.append((prev, len(points) - 1))
                            prev, prev_y = len(points) - 1, y
                            at[y] = prev
                nxt = None
                for y, wire in dests:
                    i = at.get(y, cur)
                    if wire is None:
                        # the lane carries on at the height its wire really is
                        nxt = (i, points[i][1] if i != cur else cur_y)
                    else:
                        feeds.append((wire[2], wire[3], i))
                if nxt is not None:
                    cur, cur_y = nxt
            if points:
                routes.append((key, points, links, feeds))
        # buses whose wire starts higher take the slots further left
        for g, row in buses.items():
            for slot, bus in enumerate(sorted(row, key=lambda b: b[1])):
                bus[2] = slot

    # --- x: columns, wider gaps where more wires cross or buses run. Frames
    # sit on the column's left edge so the gap before them stays clear; nodes
    # sit on its right edge, so a column's outputs line up and a small node
    # sharing a column with a wide frame stays next to what it feeds.
    x, gap_at = 0.0, {}
    for l, col in enumerate(layers):
        width = max((it.w for it in col), default=0.0)
        for it in col:
            it.x = x if it.kind == "box" else x + width - it.w
        if l + 1 < len(layers):
            n_wires = sum(len(outs[id(it)]) for it in col)
            boxes = any(it.kind == "box" for it in col + layers[l + 1])
            gap = (GAP_BOX_X if boxes else GAP_NODE_X) + min(60.0, 2.0 * n_wires)
            if buses.get(l):
                gap = max(gap, 2 * BUS_PAD + BUS_STEP * (len(buses[l]) - 1))
            gap_at[l] = x + width
            x += width + gap
        else:
            x += width

    _pull_right(layers, dag)

    placed = []
    for (src, ident), points, links, feeds in routes:
        xy = [(gap_at[bus[0]] + BUS_PAD + BUS_STEP * bus[2], y) for bus, y in points]
        placed.append((src, ident, xy, links, feeds))
    return x, max(it.y + it.h for it in real), placed


def _pull_right(layers, dag):
    """Move each item right, to just before the nearest thing that reads it, as far as nothing
    in its rows is in the way. A column is as wide as its widest item: a short chain beside a
    long frame otherwise waits at the left end of a wire as long as the frame. Readers first,
    so a chain follows its last node; frame ports keep their edge columns."""
    real = [it for col in layers for it in col if it.kind != "dummy"]
    readers = defaultdict(list)
    for u, v, *_ in dag:
        if v.layer > u.layer:
            readers[id(u)].append(v)

    def gap(a, b):
        return GAP_BOX_X if a.kind == "box" or b.kind == "box" else GAP_NODE_X

    for it in sorted(real, key=lambda it: -it.layer):
        if it.pin or not readers[id(it)]:
            continue
        want = min(v.x - gap(it, v) for v in readers[id(it)]) - it.w
        if want <= it.x:
            continue
        top, bottom = it.y - GAP_DUMMY_Y, it.y + it.h + GAP_DUMMY_Y
        for o in real:
            # what's further right in the rows it spans stops it short
            if o is not it and o.x >= it.x + it.w and o.y < bottom and o.y + o.h > top:
                want = min(want, o.x - gap(it, o) - it.w)
        if want > it.x:
            it.x = want


# ------------------------------------------------------------------ layout
def _item_of(node, path, k):
    """The item at level k that holds `node`: itself, or a child box."""
    if len(path) > k:
        return ("box", path[k])
    return ("node", node.name)


def _layout(box, index, ports):
    for kid in box.kids.values():
        _layout(kid, index, ports)
    items = {}
    for name, kid in box.kids.items():
        # the retired terms go last, under whatever shares their column
        order = float("inf") if name == UNUSED else kid.order
        items[("box", name)] = _It(("box", name), "box", kid, kid.w, kid.h, order)
    for n in box.nodes:
        items[("node", n.name)] = _It(("node", n.name), "node", n, node_width(n),
                                      node_height(n), index[n.name],
                                      pin=ports.get(n.name))

    def port(it, node, sock):
        base = it.obj.off[node.name] if it.kind == "box" else 0.0
        return base + socket_offset(node, sock)

    edges = []
    for link, pu, pv, k in box.links:
        u = items.get(_item_of(link.from_node, pu, k))
        v = items.get(_item_of(link.to_node, pv, k))
        if u is None or v is None or u is v:
            continue
        main = (v.kind == "node"
                and next((s for s in v.obj.inputs if s.is_linked), None) == link.to_socket)
        wire = (link.from_node.name, link.from_socket.identifier,
                link.to_node.name, link.to_socket.identifier)
        edges.append((u, v, port(u, link.from_node, link.from_socket),
                      port(v, link.to_node, link.to_socket), 2.0 if main else 1.0, wire))

    w, h, box.lanes = _sugiyama(list(items.values()), edges)
    for it in items.values():
        if it.kind == "box":
            it.obj.x, it.obj.y = it.x, it.y
        else:
            box.off[it.obj.name] = box.pad_top() + it.y
            box.rel[it.obj.name] = (it.x, it.y)
    for kid in box.kids.values():
        for name, off in kid.off.items():
            box.off[name] = box.pad_top() + kid.y + off
    box.w = w + 2 * box.pad_side()
    box.h = h + box.pad_top() + box.pad_side()


def _colour(path):
    base = PALETTE.get(path[0])
    if base is None:
        hue = (zlib.crc32(path[0].encode()) % 360) / 360.0
        base = colorsys.hsv_to_rgb(hue, 0.55, 0.30)
    lift = 0.05 * (len(path) - 1)
    return tuple(min(1.0, c + lift) for c in base)


def _apply(tree, root, stand_ins):
    """Make the frames and lanes and move every node, in one bulk write.

    Assigning a location one node at a time costs Blender a tree update per
    node. `foreach_set` writes them all at once; the frames go first, one by
    one and parents before children, so each node's location is taken
    relative to a frame that is already where it will stay.
    """
    N = tree.nodes
    where = {}
    routed = []

    def lane_points(box):
        return sum(len(lane[2]) for lane in box.lanes) + sum(lane_points(k) for k in box.kids.values())

    # a big flat graph can ask for thousands of reroutes (a face material: 9,000 for 875
    # nodes); made one by one they take Blender minutes, so such a tree keeps plain wires
    route = lane_points(root) <= LANE_LIMIT

    def place(box, ox, oy, parent_frame):
        frame = None
        if box.path:
            frame = N.new("NodeFrame")
            frame.name = "/".join(box.path)
            frame.label = box.path[-1]
            frame.label_size = LABEL.get(box.depth, LABEL[2])
            frame.shrink = True
            frame.use_custom_color = True
            frame.color = _colour(box.path)
            frame.parent = parent_frame
            frame.location_absolute = (ox, -oy)
            where[frame.name] = (ox, -oy)
        cx, cy = ox + box.pad_side(), oy + box.pad_top()
        for n in box.nodes:
            n.parent = frame
            x, y = box.rel[n.name]
            x, y = cx + x, cy + y
            if n.bl_idname == "NodeReroute":
                # a reroute's location is its dot, not a corner
                x, y = x + 8.0, y + 8.0
            where[n.name] = (x, -y)
        for src, ident, points, links, feeds in (box.lanes if route else ()):
            dots = []
            for x, y in points:
                r = N.new("NodeReroute")
                r.parent = frame
                where[r.name] = (cx + x, -(cy + y))
                dots.append(r)
            routed.append((src, ident, dots, links, feeds))
        for kid in box.kids.values():
            place(kid, cx + kid.x, cy + kid.y, frame)

    place(root, 0.0, 0.0, None)
    flat = []
    for n in N:
        flat.extend(where.get(n.name, tuple(n.location_absolute)))
    N.foreach_set("location_absolute", flat)

    # wired from the source outwards: a reroute takes its type from its input
    for src, ident, dots, links, feeds in routed:
        def out_of(i):
            if i < 0:
                return _out_of(N[src], ident, stand_ins)
            return dots[i].outputs[0]
        for i, j in links:
            tree.links.new(out_of(i), dots[j].inputs[0])
        for to, to_ident, i in feeds:
            tree.links.new(out_of(i), _in(N[to], to_ident))
    _realize_inputs(tree, stand_ins)
    return sum(len(r[2]) for r in routed)


def arrange(tree):
    """Frame, place and tidy every node of `tree`. Returns a short report."""
    for n in [n for n in tree.nodes if n.bl_idname == "NodeFrame"]:
        tree.nodes.remove(n)
    tags = _read_tags(tree)
    untagged = sum(1 for t in tags.values() if t is None)
    wires = _scan(tree)
    _resolve_untagged(tree, tags, wires)
    parked = _park_dead(tree, tags, wires)
    ports = _ports(tree, tags, wires)
    copies, stand_ins = _localize_sources(tree, tags, _scan(tree))
    wires = _scan(tree)
    _hide_unused_outputs(tree, wires)
    _collapse_trivial(tree, wires)
    root, index = _build_boxes(tree, tags)
    _layout(root, index, ports)
    lanes = _apply(tree, root, stand_ins)
    for n in tree.nodes:
        if SECTION_KEY in n:
            del n[SECTION_KEY]
    # a node made from Python starts selected; ship the group with none lit up
    tree.nodes.foreach_set("select", [False] * len(tree.nodes))
    frames = sum(1 for n in tree.nodes if n.bl_idname == "NodeFrame")
    return ("%d frames, %d local input copies, %d ports, %d bus reroutes, "
            "%d placed by neighbour, %d unused parked, %.0f x %.0f"
            % (frames, copies, len(ports), lanes, untagged, parked, root.w, root.h))
