# Generated by materialporter/tools/sync_fork.py from blender/material_porter/world.py - edit it there.
"""What exact materials read from the world, one node group each per file, which every material links:

    MP World Sun           Direction, towards the sun (UE space: Y mirrored), and Color, the light's
                           colour times its strength - the scene's sun lamp's, driven (a time of day's
                           own sun once one is imported); straight overhead and white without one.
    MP World Sky           Direction (UE space) -> Luminance: UE's SkyAtmosphereViewLuminance and its
                           sky light. A flat sky colour until a time of day fills it with its baked
                           atmosphere.
    MP Collection <name>   one output per parameter of that material parameter collection that a
                           material read (a vector's alpha: "<name> (A)"): its default, or the day's
                           curve where a time of day keys it.
    MP World Fog           a time of day's height fog: Factor and Fog Color for the shaded point
                           (Receiver Distance 0: its own distance), laid over each exact material's
                           surface (apply_fog).

A time of day stores its day (tod.parse) in the Text "MP Time of Day" and refills the groups, so a
map imported before it follows its hour as well as one imported after.
"""
import json

import bpy

from .ue_graph import Val

SUN = "MP World Sun"
SKY = "MP World Sky"
FOG = "MP World Fog"
COLLECTION = "MP Collection "
DAY_TEXT = "MP Time of Day"
HOUR = "mp_tod_hour"            # the scene's hour (a time of day's)
KEY_FOG = "mp_fog"              # on a fogged material's root tree, and on the nodes put in
FLAT_SKY = (0.4, 0.5, 0.7)


def day():
    """The time of day in the file (tod.parse's data), or None."""
    t = bpy.data.texts.get(DAY_TEXT)
    if t is None:
        return None
    try:
        return json.loads(t.as_string())
    except Exception:
        return None


def set_day(data):
    t = bpy.data.texts.get(DAY_TEXT) or bpy.data.texts.new(DAY_TEXT)
    t.clear()
    t.write(json.dumps(data))


def _new_group(name, inputs=(), outputs=()):
    """The group, made or emptied - its sockets kept (the materials that use it stay linked), the
    missing ones added."""
    t = bpy.data.node_groups.get(name)
    if t is None:
        t = bpy.data.node_groups.new(name, "ShaderNodeTree")
    else:
        t.nodes.clear()
    have = {(it.name, it.in_out) for it in t.interface.items_tree if it.item_type == 'SOCKET'}
    for n, kind in inputs:
        if (n, 'INPUT') not in have:
            t.interface.new_socket(n, in_out='INPUT', socket_type=kind)
    for n, kind in outputs:
        if (n, 'OUTPUT') not in have:
            t.interface.new_socket(n, in_out='OUTPUT', socket_type=kind)
    return t


def _drive(sock, index, obj, path, expression=None, extra=()):
    drv = sock.driver_add("default_value", index).driver if index is not None else sock.driver_add("default_value").driver
    drv.type = 'SCRIPTED' if expression else 'AVERAGE'
    if expression:
        drv.expression = expression
    for name, p in ((("v", path),) + tuple(extra)):
        var = drv.variables.new()
        var.name = name
        var.type = 'SINGLE_PROP'
        var.targets[0].id_type = 'OBJECT'
        var.targets[0].id = obj
        var.targets[0].data_path = p
    return drv


# ------------------------------------------------------------------ the sun
def scene_sun():
    scene = bpy.context.scene
    return next((o for o in scene.objects if o.type == 'LIGHT' and o.data.type == 'SUN'), None) if scene else None


def sun_group(sun=None):
    """The sun group, made on first use (following the scene's sun lamp), or remade to follow `sun`."""
    t = bpy.data.node_groups.get(SUN)
    if t is not None and sun is None:
        followed = bpy.data.objects.get(t.get("mp_sun") or "")
        # (one made with no sun lamp in the scene, or whose lamp is gone, follows the one there now)
        if (followed is not None and followed.type == 'LIGHT') or scene_sun() is None:
            return t
    sun = sun or scene_sun()
    t = _new_group(SUN, outputs=(("Direction", 'NodeSocketVector'), ("Color", 'NodeSocketColor'), ("Side", 'NodeSocketVector')))
    N, L = t.nodes, t.links
    go = N.new("NodeGroupOutput"); go.location = (500, 0)
    d = N.new("ShaderNodeCombineXYZ"); d.label = "the sun lamp's +Z"; d.location = (-300, 100)
    side = N.new("ShaderNodeCombineXYZ"); side.label = "the sun lamp's +X"; side.location = (-300, 300)
    c = N.new("ShaderNodeCombineColor"); c.label = "the sun lamp's colour x strength"; c.location = (-300, -150)
    if sun is not None:
        for i in range(3):
            # RNA's matrix storage is column-major: column 2 (+Z, towards the sun) is [2][i]
            _drive(d.inputs[i], None, sun, "matrix_world[2][%d]" % i)
            _drive(side.inputs[i], None, sun, "matrix_world[0][%d]" % i)
            _drive(c.inputs[i], None, sun, "data.color[%d]" % i, "v * e", (("e", "data.energy"),))
        t["mp_sun"] = sun.name
    else:
        d.inputs[2].default_value = 1.0
        side.inputs[0].default_value = 1.0
        for i in range(3):
            c.inputs[i].default_value = 1.0
    ue = N.new("ShaderNodeVectorMath"); ue.operation = 'MULTIPLY'; ue.location = (-100, 100)
    ue.inputs[1].default_value = (1.0, -1.0, 1.0)
    L.new(d.outputs[0], ue.inputs[0])
    nm = N.new("ShaderNodeVectorMath"); nm.operation = 'NORMALIZE'; nm.location = (100, 100)
    L.new(ue.outputs[0], nm.inputs[0])
    L.new(nm.outputs[0], go.inputs["Direction"])
    L.new(c.outputs[0], go.inputs["Color"])
    sue = N.new("ShaderNodeVectorMath"); sue.operation = 'MULTIPLY'; sue.location = (-100, 300)
    sue.inputs[1].default_value = (1.0, -1.0, 1.0)
    L.new(side.outputs[0], sue.inputs[0])
    L.new(sue.outputs[0], go.inputs["Side"])
    return t


def sun(tr, output="Direction"):
    """The sun group's output in the translator's tree (a Val, UE space)."""
    n = tr.node("ShaderNodeGroup", "World Sun")
    n.node_tree = sun_group()
    return Val(n.outputs[output], 3)


# ------------------------------------------------------------------ the view
VIEW = "MP World View"
# tan of half the field of view across and up the render (the sensor fits the frame's larger side
# when Auto, its width or its height when told; the other side follows the frame's aspect), and
# the render's size in pixels - plain arithmetic, which drivers evaluate without Python
_RX = "(rx * ax)"
_RY = "(ry * ay)"
_TX = ("(f == 0) * sw / (2 * l) * %(x)s / max(%(x)s, %(y)s) + (f == 1) * sw / (2 * l)"
       " + (f == 2) * sh / (2 * l) * %(x)s / %(y)s") % {"x": _RX, "y": _RY}
_TY = ("(f == 0) * sw / (2 * l) * %(y)s / max(%(x)s, %(y)s) + (f == 1) * sw / (2 * l) * %(y)s / %(x)s"
       " + (f == 2) * sh / (2 * l)") % {"x": _RX, "y": _RY}
_VIEW_VARS = (("rx", "render.resolution_x"), ("ry", "render.resolution_y"), ("ax", "render.pixel_aspect_x"),
              ("ay", "render.pixel_aspect_y"), ("pc", "render.resolution_percentage"), ("l", "camera.data.lens"),
              ("sw", "camera.data.sensor_width"), ("sh", "camera.data.sensor_height"), ("f", "camera.data.sensor_fit"))


def view_group():
    """The view group, made on first use: the scene camera's field of view and the render's size,
    driven - what UE's ViewProperty and ViewSize read, followed when the camera's lens or the
    render's size change after the import (frozen, a screen-space glow drifted off its head)."""
    t = bpy.data.node_groups.get(VIEW)
    if t is not None:
        return t
    t = _new_group(VIEW, outputs=(("Tan Half FOV", 'NodeSocketVector'), ("View Size", 'NodeSocketVector')))
    go = t.nodes.new("NodeGroupOutput"); go.location = (300, 0)
    tan = t.nodes.new("ShaderNodeCombineXYZ"); tan.label = "tan of half the field of view (across, up)"; tan.location = (0, 100)
    size = t.nodes.new("ShaderNodeCombineXYZ"); size.label = "render size (pixels)"; size.location = (0, -100)
    scene = bpy.context.scene
    if scene is not None and scene.camera is not None:
        for sock, expression in ((tan.inputs[0], _TX), (tan.inputs[1], _TY),
                                 (size.inputs[0], "rx * pc / 100"), (size.inputs[1], "ry * pc / 100")):
            drv = sock.driver_add("default_value").driver
            drv.type = 'SCRIPTED'
            drv.expression = expression
            for name, path in _VIEW_VARS:
                var = drv.variables.new()
                var.name, var.type = name, 'SINGLE_PROP'
                var.targets[0].id_type = 'SCENE'
                var.targets[0].id = scene
                var.targets[0].data_path = path
    else:
        tan.inputs[0].default_value, tan.inputs[1].default_value = 0.7, 0.39
        size.inputs[0].default_value, size.inputs[1].default_value = 1920.0, 1080.0
    t.links.new(tan.outputs[0], go.inputs["Tan Half FOV"])
    t.links.new(size.outputs[0], go.inputs["View Size"])
    return t


def view(tr, output):
    """A view group output in the translator's tree (x, y in a float2 Val)."""
    n = tr.node("ShaderNodeGroup", "World View")
    n.node_tree = view_group()
    return Val(n.outputs[output], 2)


# ------------------------------------------------------------------ the sky
def sky_group():
    t = bpy.data.node_groups.get(SKY)
    if t is not None:
        return t
    t = _new_group(SKY, inputs=(("Direction", 'NodeSocketVector'),), outputs=(("Luminance", 'NodeSocketColor'),))
    go = t.nodes.new("NodeGroupOutput"); go.location = (300, 0)
    rgb = t.nodes.new("ShaderNodeRGB"); rgb.label = "flat sky (no time of day)"; rgb.location = (0, 0)
    rgb.outputs[0].default_value = FLAT_SKY + (1.0,)
    t.links.new(rgb.outputs[0], go.inputs[0])
    t.nodes.new("NodeGroupInput").location = (-300, 0)
    return t


def sky(tr, direction):
    n = tr.node("ShaderNodeGroup", "World Sky")
    n.node_tree = sky_group()
    tr.link(direction, n.inputs["Direction"])
    return Val(n.outputs["Luminance"], 3)


# ------------------------------------------------------------------ collections
def _collection_name(path):
    return COLLECTION + path.rsplit("/", 1)[-1]


def _hour_fraction(t):
    a = t.nodes.new("ShaderNodeAttribute"); a.attribute_type = 'VIEW_LAYER'; a.attribute_name = '["%s"]' % HOUR
    a.location = (-900, 300)
    m = t.nodes.new("ShaderNodeMath"); m.operation = 'FLOORED_MODULO'; m.inputs[1].default_value = 24.0
    m.location = (-700, 300)
    t.links.new(a.outputs["Fac"], m.inputs[0])
    d = t.nodes.new("ShaderNodeMath"); d.operation = 'DIVIDE'; d.inputs[1].default_value = 24.0
    d.location = (-550, 300); d.label = "day fraction"
    t.links.new(m.outputs[0], d.inputs[0])
    return d.outputs[0]


def _curve(t, ch, x, label, loc):
    n = t.nodes.new("ShaderNodeFloatCurve"); n.label = label; n.location = loc
    mp = n.mapping
    mp.use_clip = False
    cv = mp.curves[0]
    from . import tod      # (a time of day's own module: only reached once one is in the file)
    pts = tod.samples(ch)
    cv.points[0].location = pts[0]
    cv.points[1].location = pts[-1]
    for px, py in pts[1:-1]:
        cv.points.new(px, py)
    for pt in cv.points:
        pt.handle_type = 'VECTOR'
    mp.update()
    n.inputs["Factor"].default_value = 1.0
    t.links.new(x, n.inputs["Value"])
    return n.outputs["Value"]


# collection parameters the game sets from its sun every frame (the legacy sky domes read them)
SUN_DISTANCE = 12000000.0       # cm: a time of day manager's DistanceToSunOrMoon


def _live(t, name, x_holder):
    """The live value of a collection parameter the game keeps updated, or None."""
    if name in ("SunAndMoonModelDirectionalVector", "SunAndMoonModelWorldPosition", "SunlightYTransformVector"):
        g = t.nodes.new("ShaderNodeGroup"); g.node_tree = sun_group(); g.label = "World Sun"
        if name == "SunAndMoonModelDirectionalVector":
            return [g.outputs["Direction"]]
        if name == "SunlightYTransformVector":
            return [g.outputs["Side"]]
        far = t.nodes.new("ShaderNodeVectorMath"); far.operation = 'SCALE'
        far.inputs["Scale"].default_value = float(((day() or {}).get("actor") or {}).get("DistanceToSunOrMoon", SUN_DISTANCE))
        t.links.new(g.outputs["Direction"], far.inputs[0])
        return [far.outputs[0]]
    if name == "TimeOfDay_0-1" and day() is not None:
        x_holder[0] = x_holder[0] or _hour_fraction(t)
        return [x_holder[0]]
    return None


def _fill_collection(t):
    """The group's insides from its parameters' defaults (["mp_defaults"]) and the day's keys."""
    defaults = json.loads(t.get("mp_defaults") or "{}")
    keyed = ((day() or {}).get("collections") or {}).get(t.get("mp_path") or "") or {}
    t.nodes.clear()
    go = t.nodes.new("NodeGroupOutput"); go.location = (600, 0)
    x = None
    for i, (name, value) in enumerate(sorted(defaults.items())):
        y = -i * 220
        chans = keyed.get(name)
        holder = [x]
        live = _live(t, name, holder) if chans is None else None
        x = holder[0]
        if chans is not None:
            x = x or _hour_fraction(t)
            vals = [_curve(t, c, x, "%s %s" % (name, "RGBA"[k]) if len(chans) > 1 else name, (-300, y - 40 * k))
                    for k, c in enumerate(chans)]
        elif live is not None:
            vals = live
        else:
            vals = list(value) if isinstance(value, list) else [value]
        if isinstance(value, list) and len(vals) == 1 and not isinstance(vals[0], (int, float)):
            t.links.new(vals[0], go.inputs[name])
            v = t.nodes.new("ShaderNodeValue"); v.location = (200, y - 120); v.outputs[0].default_value = float(value[3] if len(value) > 3 else 1.0)
            t.links.new(v.outputs[0], go.inputs[name + " (A)"])
        elif isinstance(value, list):
            c = t.nodes.new("ShaderNodeCombineColor"); c.location = (200, y); c.label = name
            for k in range(3):
                v = vals[k] if k < len(vals) else 0.0
                if isinstance(v, (int, float)):
                    c.inputs[k].default_value = float(v)
                else:
                    t.links.new(v, c.inputs[k])
            t.links.new(c.outputs[0], go.inputs[name])
            a = vals[3] if len(vals) > 3 else 1.0
            if isinstance(a, (int, float)):
                v = t.nodes.new("ShaderNodeValue"); v.location = (200, y - 120); v.outputs[0].default_value = float(a)
                a = v.outputs[0]
            t.links.new(a, go.inputs[name + " (A)"])
        else:
            v = vals[0]
            if isinstance(v, (int, float)):
                n = t.nodes.new("ShaderNodeValue"); n.location = (200, y); n.label = name
                n.outputs[0].default_value = float(v)
                v = n.outputs[0]
            t.links.new(v, go.inputs[name])


def collection(tr, path, name, default):
    """A collection parameter (default: a float, or (r, g, b, a)) through its collection's group."""
    key = path.split(".")[0]
    gname = _collection_name(key)
    t = bpy.data.node_groups.get(gname)
    if t is not None and t.get("mp_path") not in (None, key):
        gname = gname + " (%s)" % key.split("/")[-2]
        t = bpy.data.node_groups.get(gname)
    if t is None:
        t = bpy.data.node_groups.new(gname, "ShaderNodeTree")
        t["mp_path"] = key
        t["mp_defaults"] = "{}"
    defaults = json.loads(t["mp_defaults"])
    vec = isinstance(default, (tuple, list))
    if name not in defaults:
        defaults[name] = [float(x) for x in tuple(default) + (1.0,) * (4 - len(default))] if vec else float(default)
        t["mp_defaults"] = json.dumps(defaults)
        if vec:
            t.interface.new_socket(name, in_out='OUTPUT', socket_type='NodeSocketColor')
            t.interface.new_socket(name + " (A)", in_out='OUTPUT', socket_type='NodeSocketFloat')
        else:
            t.interface.new_socket(name, in_out='OUTPUT', socket_type='NodeSocketFloat')
        _fill_collection(t)
    n = tr.node("ShaderNodeGroup", "%s (collection)" % name)
    n.node_tree = t
    if vec:
        return tr.with_alpha(Val(n.outputs[name], 3), Val(n.outputs[name + " (A)"], 1))
    return Val(n.outputs[name], 1)


def refresh_collections():
    """Every collection group, following the file's day now."""
    for t in bpy.data.node_groups:
        if t.name.startswith(COLLECTION) and "mp_defaults" in t:
            _fill_collection(t)


# ------------------------------------------------------------------ height fog over a material
def fog_ready():
    return bpy.data.node_groups.get(FOG) is not None


def _root_tree(mat):
    """An exact material's root group (the group node feeding its output), or None."""
    if not mat.get("mp_path") or not mat.node_tree:
        return None
    out = next((n for n in mat.node_tree.nodes if n.bl_idname == "ShaderNodeOutputMaterial" and n.is_active_output), None)
    if out is None or not out.inputs["Surface"].links:
        return None
    src = out.inputs["Surface"].links[0].from_node
    return src.node_tree if src.bl_idname == "ShaderNodeGroup" and src.node_tree else None


def _from(sock):
    return sock.links[0].from_socket if sock.is_linked else None


class _Fog:
    def __init__(self, tree, receiver=0.0, mirror=0.0):
        self.t = tree
        self._g = None
        self.receiver, self.mirror = receiver, mirror

    def node(self, kind, label=""):
        n = self.t.nodes.new(kind)
        n.label = label
        n[KEY_FOG] = 1
        return n

    def group(self):
        if self._g is None:
            self._g = self.node("ShaderNodeGroup", "Height Fog")
            self._g.node_tree = bpy.data.node_groups[FOG]
            if "Receiver Distance" in self._g.inputs:
                self._g.inputs["Receiver Distance"].default_value = self.receiver
            if "Mirror Below" in self._g.inputs:
                self._g.inputs["Mirror Below"].default_value = self.mirror
        return self._g

    def scale(self, sock):
        """The shader times the fog's transmittance."""
        black = self.node("ShaderNodeEmission", "fogged away")
        black.inputs["Color"].default_value = (0.0, 0.0, 0.0, 1.0)
        mix = self.node("ShaderNodeMixShader", "x fog factor")
        self.t.links.new(self.group().outputs["Factor"], mix.inputs[0])
        self.t.links.new(black.outputs[0], mix.inputs[1])
        self.t.links.new(sock, mix.inputs[2])
        return mix.outputs[0]

    def full(self, sock):
        """UE: colour x factor + the fog's own light."""
        em = self.node("ShaderNodeEmission", "fog light")
        self.t.links.new(self.group().outputs["Fog Color"], em.inputs["Color"])
        add = self.node("ShaderNodeAddShader", "fogged")
        self.t.links.new(self.scale(sock), add.inputs[0])
        self.t.links.new(em.outputs[0], add.inputs[1])
        return add.outputs[0]

    def shader(self, sock, depth=0):
        """The shader at `sock`, fogged: only what is drawn - a see-through part keeps showing what is
        behind (already fogged itself); an additive one is dimmed, not lit."""
        node = sock.node
        L = self.t.links
        if depth > 8:
            return self.full(sock)
        if node.bl_idname == "ShaderNodeMixShader":
            a, b = _from(node.inputs[1]), _from(node.inputs[2])
            for see, other, inp in ((a, b, node.inputs[2]), (b, a, node.inputs[1])):
                if see is not None and see.node.bl_idname == "ShaderNodeBsdfTransparent" and other is not None:
                    L.new(self.shader(other, depth + 1), inp)
                    return sock
        if node.bl_idname == "ShaderNodeAddShader":
            a, b = _from(node.inputs[0]), _from(node.inputs[1])
            for see, other, inp in ((a, b, node.inputs[1]), (b, a, node.inputs[0])):
                if see is not None and see.node.bl_idname == "ShaderNodeBsdfTransparent" and other is not None:
                    L.new(self.scale(other), inp)
                    return sock
        if node.bl_idname == "ShaderNodeBsdfTransparent":
            return sock
        if node.bl_idname == "ShaderNodeBsdfPrincipled":
            alpha = node.inputs["Alpha"]
            if alpha.is_linked or alpha.default_value < 1.0:
                # its alpha becomes a mix with see-through, so only the surface is fogged
                mix = self.node("ShaderNodeMixShader", "alpha (fog)")
                tp = self.node("ShaderNodeBsdfTransparent", "see-through")
                if alpha.is_linked:
                    src = _from(alpha)
                    L.remove(alpha.links[0])
                    L.new(src, mix.inputs[0])
                else:
                    mix.inputs[0].default_value = alpha.default_value
                alpha.default_value = 1.0
                L.new(tp.outputs[0], mix.inputs[1])
                L.new(self.full(sock), mix.inputs[2])
                return mix.outputs[0]
        return self.full(sock)


def apply_fog(mat, receiver=0.0, mirror=0.0):
    """The file's height fog over an exact material (its root group, shared by its instances, once).
    False when there's no fog or nothing to fog."""
    if not fog_ready():
        return False
    tree = _root_tree(mat) if mat.get("mp_path") else None
    if tree is None:
        tree = mat.node_tree if mat.get("mp_tod") else None
    if tree is None or tree.get(KEY_FOG):
        return False
    if tree == mat.node_tree:
        out = next((n for n in tree.nodes if n.bl_idname == "ShaderNodeOutputMaterial" and n.is_active_output), None)
        target = out.inputs["Surface"] if out is not None else None
    else:
        out = next((n for n in tree.nodes if n.bl_idname == "NodeGroupOutput"), None)
        target = next((s for s in out.inputs if s.type == 'SHADER'), None) if out is not None else None
    src = _from(target) if target is not None else None
    if src is None:
        return False
    fog = _Fog(tree, receiver, mirror)
    tree.links.new(fog.shader(src), target)
    tree[KEY_FOG] = 1
    return True


def remove_fog(mat):
    """Undo apply_fog (the material's tree back as built)."""
    tree = _root_tree(mat) or (mat.node_tree if mat.get("mp_tod") else None)
    if tree is None or not tree.get(KEY_FOG):
        return False
    L = tree.links
    for n in [n for n in tree.nodes if n.get(KEY_FOG)]:
        if n.bl_idname == "ShaderNodeMixShader" and n.label == "alpha (fog)":
            # the alpha back on the Principled BSDF
            fac, surf = _from(n.inputs[0]), _from(n.inputs[2])
            bsdf = _unfog(surf)
            if bsdf is not None and bsdf.node.bl_idname == "ShaderNodeBsdfPrincipled":
                if fac is not None:
                    L.new(fac, bsdf.node.inputs["Alpha"])
                else:
                    bsdf.node.inputs["Alpha"].default_value = n.inputs[0].default_value
    for n in [n for n in tree.nodes if n.get(KEY_FOG) and n.bl_idname in ("ShaderNodeAddShader", "ShaderNodeMixShader")]:
        if n.bl_idname == "ShaderNodeMixShader" and n.label == "alpha (fog)":
            src = _unfog(_from(n.inputs[2]))
        else:
            src = _unfog(n.outputs[0])
        for link in list(n.outputs[0].links):
            if src is not None:
                L.new(src, link.to_socket)
    for n in [n for n in tree.nodes if n.get(KEY_FOG)]:
        tree.nodes.remove(n)
    del tree[KEY_FOG]
    return True


def _unfog(sock):
    """Through the fog's own nodes back to the shader they took."""
    while sock is not None and sock.node.get(KEY_FOG):
        n = sock.node
        if n.bl_idname == "ShaderNodeAddShader":
            sock = _from(n.inputs[0])
        elif n.bl_idname == "ShaderNodeMixShader":
            sock = _from(n.inputs[2])
        else:
            return None
    return sock
